### ISSUE TITLE
Discussion: Code Formatting

### ISSUE THREAD

**Issue by pepperoni505** [AsoboStudio/glTF-Blender-IO-MSFS#103]
Currently, we have no enforced code formatting. This thread will be used to discuss which style is best. My recommendation is the following:

Black Formater (https://github.com/psf/black)
pylint (https://github.com/PyCQA/pylint)

**Comment by lpierabella** [comment]
I'm ok with those packages.
[here ](https://towardsdatascience.com/keep-your-code-clean-using-black-pylint-git-hooks-pre-commit-baf6991f7376)is a good article that also explains how to configure hooks that check for code style
I have some doubts about the Licenses of these 2 package..I'll check internally if they fi our SDK license
