### ISSUE TITLE
Is it possible to correct the default values for when selecting a msfs material in Blender?

### ISSUE THREAD

**Issue by Ariebaba** [AsoboStudio/glTF-Blender-IO-MSFS#105]
Now everybody has to change values when selecting a material like glass. You have to change the alpha of the base color, etc. I would be nice, if possible, to have the values be on a default value that works and then change them to your liking later. Thx

**Comment by Mikeaat** [comment]
i think this is the same issue like #89

**Comment by Ariebaba** [comment]
Not entirely but close enough. Thx for pointing in the right direction.
