### ISSUE TITLE
Windshield Material - migration missing alpha value

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#110]
### Current Behavior

The alpha values for windshield material is not being carried over in windshield migration..  it remains as 1.0

### Expected Behavior

Carry over the alpha value from the Legacy exporter albedo_tint node. (base color)

### Steps To Reproduce

open a model with windshield material - migrate windshield - see that the windshield shows all the textures - no transparency.

### Environment

```markdown
- OS:10
- Blender:3.1
- glTF-Blender-IO-MSFS:1.1.4
```

### Anything else?

before:
![DA40CGDFQ_April 4, 2022_11h54m38s](https://user-images.githubusercontent.com/19254353/161583587-de82d3cd-470b-4bb4-bfb0-07117c3e6355.png)

after:

![DA40CGDFQ_April 4, 2022_11h54m58s](https://user-images.githubusercontent.com/19254353/161583614-00cf7582-ec00-47db-b0db-4d802979a6f2.png)

**Comment by PhysicsTeacher1** [comment]
Please see #107 comments.  I'll verify that this is also fixed.  More soon.

**Comment by lpierabella** [comment]
Hi @ronh991 can you please provide a file to repro the issue?

**Comment by lpierabella** [comment]
it should be fixed in f572ad0a7d461daa0218f0a5eb6bc6b6d5c09813

**Comment by ronh991** [comment]
now causes error.

Python: Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_panel.py", line 90, in execute
    if mat.msfs_color_alpha_mix:
AttributeError: 'Material' object has no attribute 'msfs_color_alpha_mix'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_panel.py", line 90, in execute
    if mat.msfs_color_alpha_mix:
AttributeError: 'Material' object has no attribute 'msfs_color_alpha_mix'

**Comment by lpierabella** [comment]
sorry ..my mistake, apparently having the Vitus exporter and the MSFS IO installed ended up with properties serialized in a different manner.

**Comment by ronh991** [comment]
Yes I use two different blender programs - 3.0 has legacy exporter and 3.1.2 has the new asobo exporter.  I find that you can't just enable and disable each exporter.  You have to remove them.

**Comment by PhysicsTeacher1** [comment]
... and restart Blender.  I've been caught by this.

**Comment by lpierabella** [comment]
is it still the case?

**Comment by ronh991** [comment]
wait I did not see the fix migrate brnch updated an hour ago

**Comment by ronh991** [comment]
fixed in migrate branch
