### ISSUE TITLE
Decal material - blend factors not carried over in migration

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#116]
### Current Behavior

The blend factors are set to zero, while they should reflect the current blend factors in the panel data. and custom values panel.

### Expected Behavior

reflect the values found in custom panel for blend factors.

### Steps To Reproduce

use legacy exporte with decal material, set blend factors to 1.0 open this model in ASOBO 1.1.5 exporter and migrate decal msfs material.  See that blend factors are set to zero.

### Environment

```markdown
- OS:10
- Blender:3.1.2
- glTF-Blender-IO-MSFS:1.1.5
```

### Anything else?

![DA40CGDFQ_April 11, 2022_11h45m22s](https://user-images.githubusercontent.com/19254353/162782536-2488c995-87b5-4296-bbe0-e192e134195d.png)
![DA40CGDFQ_April 11, 2022_11h45m39s](https://user-images.githubusercontent.com/19254353/162782554-5d67b49f-3d49-410b-9c3a-8acdea2d1515.png)

**Comment by scheny** [comment]
I have the same problem. All decals are invisible in MSFS.

**Comment by realModsWanted** [comment]
Same problem here. Decal texture is invisible.

**Comment by pepperoni505** [comment]
#128 fixes migration, and #126 fixes new decals

**Comment by ronh991** [comment]
Agree fixed
