### ISSUE TITLE
After plugin activation, Blender's Import/Export menu do not show an option for MSFS .glTF

### ISSUE THREAD

**Issue by jonstanley** [AsoboStudio/glTF-Blender-IO-MSFS#120]
### Current Behavior

Blender version 3.1.2, glTF-Blender-IO-MSFS version 1.1.5

After plugin installation & activation (Edit > Preferences > Add-ons), glTF-Blender-IO-MSFS does not show up as module for Import/Export

### Expected Behavior

After plugin installation & activation (Edit > Preferences > Add-ons), glTF-Blender-IO-MSFS SHOULD show up as an alternative Importer/Exporter separately from the bundled glTF module

### Steps To Reproduce

1. Windows 11 x64, Blender 3.1.2 clean install
2. Extract plugin to Blender's add-on folder
3. Activate plugin in Preferences > Add-ons
4. New module should show in Importer/Exporter

### Environment

```markdown
OS: Windows 11
Blender: 3.1.2
glTF-Blender-IO-MSFS: 1.1.5
```

### Anything else?

N/A

**Comment by Wombii** [comment]
With this exporter it's not showing up as a separate one like blender2msfs, but has the extension available in the stock gltf exporter. There is also a new multi-export option. 
![image](https://user-images.githubusercontent.com/60835350/163092529-b04efbad-49c5-41a2-a9ac-525a898c4aae.png)
![image](https://user-images.githubusercontent.com/60835350/163092546-806b96c2-fc23-4259-a009-2258ce285aa4.png)

**Comment by jonstanley** [comment]
Awesome for exporting... what about importing? I tried an MSFS2020 file that I've imported without issue in the past in Blender 2.x with the FBW glTF add-on, and now it just fails...

**Comment by Wombii** [comment]
That is my experience too with importing. I don't know if it's supposed to be ready to do that yet, so I haven't reported it as an issue. I get the error Extension MSFT_texture_dds is not available on this addon version when trying to import a default plane model.
![image](https://user-images.githubusercontent.com/60835350/163099988-797059dd-cf37-41ec-9717-82c2d734562e.png)

**Comment by jonstanley** [comment]
Right, that's the error I get too. Was hoping there would be feature parity at least with the FBW glTF 2.0 add-on. Hope devs can answer... 🙏

**Comment by pepperoni505** [comment]
> Right, that's the error I get too. Was hoping there would be feature parity at least with the FBW glTF 2.0 add-on. Hope devs can answer... 🙏

See #121

**Comment by jonstanley** [comment]
Okay, so the tool is basically split now... will have a play later, so will close this for now
