### ISSUE TITLE
Blender Light Color Picker panel disagrees with MSFS Light Parameter Color Picker panel

### ISSUE THREAD

**Issue by PhysicsTeacher1** [AsoboStudio/glTF-Blender-IO-MSFS#123]
### Current Behavior

With the new MSFS Light Parameters panel in 1.1.5, the two Color Picker controls disagree.

### Expected Behavior

Both panels should agree regardless of which one the change was in.

### Steps To Reproduce

(Version 1.1.5)
1. Create a plane and give it a flat white material.
2. Create a Blender spotlight and point it at the plane (viewable in Rendered mode).
3. Using the original (Blender) Color Picker, set the color to a distinct color.
4. Now, using the Color Picker in the MSFS Light Params panel, use its Color Picker to set another color.
5. Export the light-plane pair and observe the resulting color.

### Environment

```markdown
- OS: Windows 10 Home
- Blender:3.1.0
- glTF-Blender-IO-MSFS:1.1.5
```

### Anything else?

I believe that simply syncing the two Color Pickers whenever one changes would be the simplest solution.  This, of course, adds more work for the Migration process.
The Blender panel must remain, of course, since not everyone uses the exporter.
The MSFS Light Params panel is a very welcome addition.  Thank you again!

**Comment by pepperoni505** [comment]
This is strange. There is no color picker present in the MSFS light panel. Did you accidentally install PR #114?

**Comment by PhysicsTeacher1** [comment]
Right you are!  I simply copied over 1.1.5 and didn't get rid of the extra file from my looking at #114.  My error there.  I'm now strictly 1.1.5.  I'll close this.  Thanks for catching this.
