### ISSUE TITLE
Emissive Color Picker without an Emissive Texture does not provide an emissive material

### ISSUE THREAD

**Issue by PhysicsTeacher1** [AsoboStudio/glTF-Blender-IO-MSFS#125]
### Current Behavior

I am unable to create an emissive material that emits unless there is an Emissive Texture present.

### Expected Behavior

Create a new material slot and add an emissive material to a mapped part of an object, say a streetlight luminaire or to an entire object.
Invoke the MSFS Material Params-Standard, and change the Emissive color from black to pure white using the Color Picker.
When viewed in Material Preview mode in Blender, the color of the area mapped should reflect the color of the Emissive Color Picker.
The Emissive Factor is defaulted to 1.00, so the material should now glow.

### Steps To Reproduce

Exporter 1.1.5, Windows 10 Home, Blender 3.1
1. Create an object with several faces, and, in Edit Mode, select a face you want to make into an emitter.
2. Invoke MSFS Material Params-Standard, and advance the Emissive Color color picker to full white or any other color.  Note that the designated face viewed in Material Preview does not change.
3. Slide the Emissive Scale control over its full range, and observe that the designated face intensity is not affected.
4. Switch to the Shading viewport preset and expand the Emissive Scale node to see that the node is tracking the Emissive Scale slider as expected.
5. If you have Node Wrangler Installed, look at the output of the Emissive Texture node and see all black.  This then has one Emission Multiplier node at 0 inhibiting any emission output.

### Environment

```markdown
- OS:Windows 10 Home
- Blender:3.1
- glTF-Blender-IO-MSFS:1.1.5
```

### Anything else?

The problem can be best analyzed in the Shading viewport preset.  It appears that the Emissive Multiplier node is taking any value from the Emissive RGB node and multiplying it by 0, the output from the unused Emissive Texture node.
Workaround:
Add an emissive texture such as a mask designed to make only certain windows on a building light up at night.  Alternately, you can create a pure white image and assign that image to the Emissive Texture slot.  Now the Emissive Scale value will control the strength of the Emission input of the Principled BSDF node - the input of which is now not black.
This entire chain works properly and as designed when there is an Emissive Texture present that is not entirely black.
Possible Fix:
Pattern the Color Picker RGB node and the Emissive Texture node reconnection after the Base Color RGB and Base Color Texture node tree.  That involves some connection code, I think, but there will be no need for the additional Detail Color logic.  I assume the scheme used in Blender2MSFS is unacceptable since it tied the Emissive Color Picker directly to the Principles BSDF node unless an emissive texture was present.

**Comment by lpierabella** [comment]
hi, @PhysicsTeacher1 can you please confirm me if the issue is solved? thanks

**Comment by PhysicsTeacher1** [comment]
Yes, the issue is solved.  That was a lot of code to change.  Thank you very much!
Issue 132 is still a problem, however:  The emissive texture still glows when Day/Night Cycle is asserted.
