### ISSUE TITLE
Some basic questions (maybe Bugs)

### ISSUE THREAD

**Issue by chwilluweit** [AsoboStudio/glTF-Blender-IO-MSFS#127]
Hi,

first of all, thank you so much for maintaining this im-/exporter! I previously used one of the predecessors (seemingly not maintained anymore), which had some issues. Some of these remained in your version, but maybe the problem is on my side:

1. When loading a base color texture in the plugin, it will be interpreted as "non color" by default. Is this correct? Until now i used sRGB-Encoding which seems to be the way, MSFS interprets the textures.
**EDIT: I just found in the MSFS SDK Documentation, that base color shall be linear. This means, when i create textures (currently using GIMP), i have to set the encoding to 8bit-linear RGB, is that correct?**

3. The normal maps in MSFS are interpreted according to DirectX, whereas in Blender (at least on linux) it is OpenGL. This results in different behaviour of normal textures in MSFS and Blender. I used a workaround, namely manually adding a "RGB Curves" Node in Blenders shader and using it to invert the green channel of the normal texture.

4.  It would be really nice to have some kind of "ambient occlusion preview"-option. I figured, this might be possible by "mixing" the albedo/base color with the occlusion texture. A more advanced version would use some diffentiation between direct light sources and ambient light sources in blenders "Shading Workspace".

As you might have noticed, i would like to build my scenery objects in blender and have a preview on how it will look like in MSFS. I'm not a pro in 3d-modelling for games, so maybe i have misunderstood something. Would like to hear from you!

Thanks,
Christopher

**Comment by lpierabella** [comment]
Hi @chwilluweit 
1- you are right on the first question your texture should be linear
2 - currently MSFS only supports DirectX normal map, you should generate and works only with DirectX normal map,
to have a correct preview in blender we have to change the shader tree so that the axis are inverted and Blender preview works DirectX input textures, you can raise a bug for it
3- indeed we should preview the occlusion you can add a feature request for it

**Comment by y-khodja** [comment]
Hello,

This should be updated with the new exporter version.

Thank you for your report !
