### ISSUE TITLE
Hasn't the light rotation bug been fixed?

### ISSUE THREAD

**Issue by realModsWanted** [AsoboStudio/glTF-Blender-IO-MSFS#129]
### Current Behavior

When exporting an object with a light-object (in my case a sportlight) the exported light in the gltf is rotated by -90° on the X-axis.
So to get the correct orientation I have to turn the light by +90° on the axis an then export.
**Pls see attached picture**.

### Expected Behavior

Light-objects should be exported with the same orientation as set in Blender.

### Steps To Reproduce

1. Create a random object, cube for example.
2. Add a spotlight.
3. Turn the spotlight into your desired direction.
4. Export.
5. Check in MSFS20.

### Environment

```markdown
- OS: Windows 11
- Blender: 3.1.0
- glTF-Blender-IO-MSFS: 1.1.5
```

### Anything else?

![spotlight-wrong-direction](https://user-images.githubusercontent.com/98099299/164227546-33b9e5ee-cee3-43ea-9758-25c043e25d91.jpg)

**Comment by pepperoni505** [comment]
This has been fixed in the latest `main` branch. Please try that

**Comment by realModsWanted** [comment]
> This has been fixed in the latest `main` branch. Please try that

Thank you for the info Jack. I am reaching my GitHub limts here. How do I get to the main branach? I thought, this here is the official one, isn't it?

**Comment by pepperoni505** [comment]
Great! This issue can be closed when we push a new release
