### ISSUE TITLE
MSFS Material params issue

### ISSUE THREAD

**Issue by Marcoh-Fs** [AsoboStudio/glTF-Blender-IO-MSFS#131]
### Current Behavior

I've installed Blender 3.1 and the new exporter 1.1.5 yesterday and i could export a multi lod object (some has trouble and some not), but my problem is :

The material utility "MSFS Material params" don't work properly.

As you can see in the picture attached. When i select for a new box a basic Standard materail, nothing is created in the shading menu. If i had albedo texture or whatever other texture, noting is created and nothinh is connected.

I also open a object created whith Blender 3.0 and MSFStoolkit 0.40.2.5. It's open correctly, but if i want to change something in the material,
MSFS Material Params say to migrate Material Data. 
I tried to migrate but i've got a error message, and finaly the migrated material has nothing inside and is same has the first one.

I've completely reinstalled Blender and the exporter, but it's same as the first time.
So it's unusable in this state.

![Desktop Screenshot 2022 04 20 - 12 31 21 42](https://user-images.githubusercontent.com/104088131/164271007-25660b8f-060d-407d-87df-1c0c2d6df241.png)
?

### Expected Behavior

I espect to import old Materials made with MSFSToolkit properly, without error message.
I espect also to be able to create MSFS Materials for news objects.

### Steps To Reproduce

Open Blender 3.1.2
Open an object made with MSFStookit 0.40.2
              - MSFS material has : 
              - Albedo texture
              - Occlusion, roughtness, metallic texture
              - Normal texture 
Launch "Migrate Material Data"  
See error message on sceen capture below.
                       
![Desktop Screenshot 2022 04 20 - 12 40 07 15](https://user-images.githubusercontent.com/104088131/164270828-9d10ba91-7e52-4014-abf3-f473fbf51108.png)
 

### Environment

```markdown
- OS:Windows 11
- Blender:3.1.2
- glTF-Blender-IO-MSFS:1.1.5
```

### Anything else?

You can test with the Blender example belo
[Yeu_Feu-est_mhg.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8523082/Yeu_Feu-est_mhg.zip)
w

**Comment by Marcoh-Fs** [comment]
Hello, 
I found the problem.
My Blender is set to French Language, so "Principled BDSF" is named "BDSF Guidé". The migration tool don't find the "principled bDSF" and stop to migrate.

After set language to english, the migration is correct and objects are shown correctly, even objects with detailled textures are shown less correctly than before (bit glossy and darky than it should).

Is there a solution to implement other languages than English ?

**Comment by lpierabella** [comment]
@Marcoh-Fs can you please confirm the issue is solved?

**Comment by Marcoh-Fs** [comment]
Yes, solved. I was thinking that using the button Close with comment was closing and solving the thread.

**Comment by Marcoh-Fs** [comment]
I follow you link and discovered you have modify 3 files. I've copied this 3 files and put they in my  folder addons (in scripts).
I've tried to set the language to french and create ou convert materials. It's work now.

Thanks a lot.

You can close it
