### ISSUE TITLE
day/night switch for emissive not working 

### ISSUE THREAD

**Issue by mamu82** [AsoboStudio/glTF-Blender-IO-MSFS#132]
### Current Behavior

When adding an emissive texture, with the day/night switch enabled, the texture stay lit all day long

this is because in the gltf, in materials section,  the extension is not used

current code:

"extensions" : {},

### Expected Behavior

right code

"extensions" : {
                "ASOBO_material_day_night_switch" : {
                    "enabled" : true
                }
            },

### Steps To Reproduce

add a emissive texture
export 
look at the materials section of the gltf 

### Environment

```markdown
- OS:win 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.5
```

**Comment by PhysicsTeacher1** [comment]
Thanks, MaMu.  I was just noting that also when a punctual light is not set to flash or to rotate, it will, indeed, follow the Day/Night cycle, but when it has either a rotation rate (for a spot, of course) it is on all the time.  Also, I was in the middle of checking out putting a flash rate on an emissive texture, and I think that also does not follow the Day/Night cycle.
Good find on the code.

**Comment by PhysicsTeacher1** [comment]
Thank you in advance.  This exporter is a delight to use.

**Comment by lpierabella** [comment]
fixed in [last commit](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/commit/05f00f00c9adea211504fb89d9d880492061ceb2)
