### ISSUE TITLE
Only one xml is needed

### ISSUE THREAD

**Issue by Marcoh-Fs** [AsoboStudio/glTF-Blender-IO-MSFS#134]
### Current Behavior

Is it possible to generate only one XML with all the LODS included in rether than one XML by LOD.

It wood be more simple.

### Expected Behavior

Only one XML for multi-lods objects

### Steps To Reproduce

When launching Multi-Export glTF 2.0

### Environment

```markdown
- OS:Windows 11
- Blender: 3.1.2
- glTF-Blender-IO-MSFS:1.1.5
```

**Comment by mamu82** [comment]
This was already adressed in on of the earliest release


To make It work like we were used to with the former exporter,
Create collections with the name

Object_LOD00
Object_LOD01
....
Object_LOD04

In the exporter, select Grouped by collection

Click Reload Lod a couple of times

Should work

The band of the xml Will be "Object", and Will contains all the lods

**Comment by realModsWanted** [comment]
You can also make it like this and it works fine.

![image](https://user-images.githubusercontent.com/98099299/164428864-6eeb7530-02a8-4b6c-8a6d-52a51fb905a5.png)

![image](https://user-images.githubusercontent.com/98099299/164428949-6100c652-e2fd-4be2-a9b3-6c56bba5a549.png)

![image](https://user-images.githubusercontent.com/98099299/164428998-fcc7c563-a5a9-4222-bb64-ceec0d9d8687.png)
