### ISSUE TITLE
Cylinder & Sphere Collision wrong sizes

### ISSUE THREAD

**Issue by realModsWanted** [AsoboStudio/glTF-Blender-IO-MSFS#137]
### Current Behavior

Two issues with the two mentioned colliders.
1. Cylinder and sphere colliders do export with a factor.
2. Shape of the cylinder collider does not rotate in Blender but exports with the correct rotation.

**Cylinder**
- For a desired diameter of 0.55m, you have to type in Blender 0.055m on the X an Y --> so it looks like it is exporting as a factor of 10, dimension of Z axis seems to be fine.
- When you rotate the collider in Blender, you don't see the shape rotating, just the small axis within the shape. But gets exported correct.

**Sphere**
- For a desired diameter of 0.3m, you have to type in Blender 0.03m. But still in MSFS it shows in the collision debug an r of 0.270 which is a diameter of 0.54m... no idea where these numbers are coming from.

### Expected Behavior

Export correct size and rotation of cillisions.

### Steps To Reproduce

1. Create a mesh (for example a cube).
2. Add a collider (cylinder or sphere).
3. Type in the desired sizes (cylinder X&Y must be the same size) Z seems to work correct. For sphere all 3 numbers must be the same (X,Y,Z).
4. Export
5. Check size in MSFS.

### Environment

```markdown
- OS: Windows 11
- Blender: 3.1.0
- glTF-Blender-IO-MSFS: 1.1.5 (main branch)
```

### Anything else?

![cylinder-sphere-collision-wrong-size](https://user-images.githubusercontent.com/98099299/164766427-84d6d978-cdee-46a9-a060-f1a246226fc7.jpg)

**Comment by pepperoni505** [comment]
Hi,

I'll look into this. We've had lots of issues with collision meshes not being sized correctly. Can you please provide a blend file?
