### ISSUE TITLE
negative scale ignored during build of model (displacement of mirrored objects)

### ISSUE THREAD

**Issue by moonphone** [AsoboStudio/glTF-Blender-IO-MSFS#138]
### Current Behavior

In case the glTF has objects with negative scales set, they will be ignored during build.
![image](https://user-images.githubusercontent.com/104312523/165161757-d61b5989-4b2f-4bbf-b629-0274ad41d37e.png)

As a result objects within the built model are transformed incorrectly. 

### Expected Behavior

Same transformation of 3d objects

- [x] blender file
- [x] glTF export
- [ ] MSFS 2020 build model 

### Steps To Reproduce

1. Duplicate Link of any Object within your blender scene/collection
2. Mirror the duplicate => it will get a negative scale
3. Export glTF
4. View glTF within any viewer => result is OK
5. Build the package (Dev mode MSFS 2020)
6. The duplicate will be transformed incorrectly

### Environment

```markdown
- OS: Windows 10
- Blender: 3.1 and 3.2 Alpha
- glTF-Blender-IO-MSFS: 1.1.5
- MSFS SDK: 0.18.0
```

### Anything else?

This is not an issue of this addon more like the "MSFS 2020 SDK"

**Comment by moonphone** [comment]
As mentioned, the exporter is ok 👍 I thought participants of this project might forward it or just give a hint how to handle this. The "duplicate link" => "mirror" or mirroring objects in general is something common, I think.

**Comment by lpierabella** [comment]
@moonphone I understand your issue but this is a more generic problem/feature request.
I invite you to post this on the official DevSupport.
As a consequence, I'm closing this issue.
Thanks for your contribution.
