### ISSUE TITLE
The presets tabs export as the name "Preset 1" instead of the name of the input

### ISSUE THREAD

**Issue by btronquo** [AsoboStudio/glTF-Blender-IO-MSFS#140]
### Current Behavior

![image](https://user-images.githubusercontent.com/5455001/165312315-3a996c50-de90-4421-8747-77652309b2b3.png)

The presets tabs export files as the name "Preset 1" instead of the name of the input

### Expected Behavior

A correct naming of the exported files

### Steps To Reproduce

- create a cube
- add a preset and name it "toto"
- export it via the export button at the botton

It seems that the files are exported with the name "Preset 1" instead of "toto"

### Environment

```markdown
- OS: win10
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.6
```

**Comment by pepperoni505** [comment]
That is a workaround, but the file naming should match the name specified by the user. Will fix this soon

**Comment by lpierabella** [comment]
well, the name here is actually pretty useless.
The base idea was to use a name to identify a group of presets like it is done in 3dsmax 
![image](https://user-images.githubusercontent.com/77288191/166455765-4557a955-a0c1-442d-9b49-eccd48735f44.png)
You can see that even in this plane, made by the internal Asobo team the name of the preset is useless
We could consider removing it in favour of a name for a group of presets
