### ISSUE TITLE
Can't export textures or materials without strange discoloration

### ISSUE THREAD

**Issue by superspuud** [AsoboStudio/glTF-Blender-IO-MSFS#142]
This seems to be specific to one model, but I can't cure  it. 

On the left in the photos is the same model exported with the original exporter, on the right is with this one. 

Both textures and materials either have a weird green/purple/rainbow tinge, or they're too dark. There also seem to be some strange mesh issues as well. 

Changing from a texture to RGB doesn't cure it. Using MSFS standard materials instead doesn't either. 

Is there a setting I'm missing? Nothing I change works. 

<img width="679" alt="test3" src="https://user-images.githubusercontent.com/104085999/166528981-45626442-e40a-4f79-ad28-34430cacbc23.png">

<img width="571" alt="test2" src="https://user-images.githubusercontent.com/104085999/166530051-58c1ef6c-c069-47b6-aefe-45280fc5936c.png">

<img width="627" alt="test1" src="https://user-images.githubusercontent.com/104085999/166531076-978afa7d-27ec-4611-a3cc-cec712845b9a.png">

<img width="541" alt="test4" src="https://user-images.githubusercontent.com/104085999/166531852-fc0e583e-10c6-4145-8925-951a512d851a.png">

**Comment by realModsWanted** [comment]
Did you migrate the materials when you loaded your project? There is a button on the right in the materials window (Sorry, I`m not sitting infront of the pc with Blender installed, otherwise I could name it)... this button says something like "import material data" or "migrate material data" or something like this. This could be a solution regarding the discoloration, because it looks like your COMP texture isn`t read correctly.
Also check in the sahader panel if the correct BSDF shader is set.

Regarding the mesh errors. I would check if the scale is reset or not, as you might know, blender gets sometimes funky with that. Also I would check if the are maybe some modifiers which are not applied, which might distort the mesh on export. You don`t have to apply them in Blender, just click the checkbox in the exporter "apply modifiers".

If nothing helps, I would create in the same project just a cube and apply the material you have the problem with, to the cube. Export that cube and check the result in MSFS. I think you could then troubleshoot a bit if it is a materials or a mesh or both issue.

If nothing helps, I think the Devs might want to have a look at that blend file.

**Comment by superspuud** [comment]
None of the materials were MSFS standard, just normal ones. Making them native MSFS standard to the plugin doesn't change anything. 

Only one has a normal texture. All the others are just the diffuse colour. And changing that colour from a texture to RGB doesn't make any difference to these weird tinges. 

Everything looks fine in Blender and it exports completely normallly with the original exporter from Vitus. I am a bit mystified. 

Also when attempting to build with this model only I'm getting this most of the time and it's only happening when using this plugin. 

<img width="308" alt="g" src="https://user-images.githubusercontent.com/104085999/166672526-099c5da3-4459-43d5-b9b1-9f103fd2904d.png">

Time to forget it I think.

**Comment by pepperoni505** [comment]
Can you send the blend file and glTF file please?

**Comment by lyonheart001** [comment]
Looks like you have Pearessence on those materials.  You can see a rainbow effect.

**Comment by pepperoni505** [comment]
> Looks like you have Pearessence on those materials.  You can see a rainbow effect.

It's probably not enabled. We ran into this issue at FlyByWire, but could not accurately reproduce it. Sending the blend and glTF files are the best way to find what's causing it

**Comment by lpierabella** [comment]
you should send us both the GLTFs, old and new ones...in order to compare
Thanks

**Comment by ronh991** [comment]
What version of blender are you using and what version of the exporter.  looking at the blend file it's marked with 3.0.
Also this looks like an issue I had with not migrating MSFS materials, so the shader node structure is not as expected.  Is there any way you can use the MSFS node structure and get the result you require?

**Comment by Ariebaba** [comment]
I have discolouration also when I use UVPackmaster. To get rid of it I have to manually remove the geometry attributes from the object on the Object Data Properties Tab.

**Comment by y-khodja** [comment]
Hello, 

Have you enabled flighsim material standard for all your materials ?

**Comment by ozpolonski** [comment]
Did we ever find a work around for this?
I'm getting the rainbow effect, even with all textures removed.

I unfortunately didn't migrate the materials. But I have set them to disabled and then changed them to their new state (standard/glass etc). All textures seem to be working well, but specifically the wing, and the spinner frost show this rainbow texture. The rudder also has some imperfections. 
The UVs seem to be ok and the textures also seem to be good. But this rainbow pattern seems to sit above the textures.

With textures
![SS 000686](https://user-images.githubusercontent.com/74175203/213096893-a4dbe3aa-60e8-44bf-b33c-cffef09efff9.png)

textures removed
![SS 000690](https://user-images.githubusercontent.com/74175203/213096913-0183e58e-9de7-4199-9b70-cb815a46d767.png)

**Comment by ozpolonski** [comment]
With no materials or no textures - ie: plain 3d model, the issue still persists. Unsure of where to go from here.

![SS 000711](https://user-images.githubusercontent.com/74175203/214290225-d8cb2a24-22eb-41a3-9e58-b75c1226bafa.png)

**Comment by Wombii** [comment]
![image](https://user-images.githubusercontent.com/60835350/214290682-0e4b7017-5352-4925-b471-3c9fe29c00ba.png)

Try removing the Vertex Colors info. The exporter/sim doesn't handle that well and gives that rainbow effect

**Comment by ozpolonski** [comment]
Thanks! I'll give it a go and report back.

**Comment by Wombii** [comment]
To clarify: In my experience I get those rainbow effects if I use vertex colors or vertex alpha and there's no detail texture selected. If I try to import an Asobo model (using the old FBW importer) I always have to delete the vertex color data.
