### ISSUE TITLE
Errors when I enable addon

### ISSUE THREAD

**Issue by RoscoHead** [AsoboStudio/glTF-Blender-IO-MSFS#143]
Hi, I just tried to install this addon, it installed OK but got errors when I tried to enable it, I've included a screenshot. Is there something else I need to do?
![enable](https://user-images.githubusercontent.com/86400867/166608417-a7abe700-b59d-4f2e-9943-0d171e5a16d3.jpg)

**Comment by RoscoHead** [comment]
PS: Using blender 2.90, addon 1.1.6

**Comment by pepperoni505** [comment]
Hi,

This addon explicitly only supports Blender 3.1 and newer. Please retry using the latest blender release.

Also, next time please use the provided issue template 😉

**Comment by RoscoHead** [comment]
Apologies, I didn't see that requirement, thanks.

**Comment by RoscoHead** [comment]
Well I installed 3.1, and I no longer get the error when I enable the addon, but no MSFS options appear on either my import or export menus? Sorry to be a pain, but I'm really a beginner with blender.

**Comment by realModsWanted** [comment]
Import: Use the normal Blender menu via "File -> Import -> gltf 2.0" .
Export: When in Blender, press the hotkey "n". This opens an additional menu on the right side of your viewport. You will see a tab called "Multi-Exporter". This is the way to export your projects to MSFS, don`t use the normal Blender Export option.

How to use the multiexporter -> read the instructions on github or just search for it on the internet. There is plenty information on this topic.

**Comment by lyonheart001** [comment]
RoscoHead, 

I dealt with this all day yesterday and I think I know what it is.
You need the stock version glTF import/export inside Blender that Blender comes with, as I think the SDK's use that (files in it) to function.

Thats my only guess.  

I redownloaded the newest Blenders (3.3 and 3.2) which had/come with, the glTF import/export (basic version that Blender has) and the error messages stopped.

Its also difficult to understand how some of these SDK's work compared with other Blender addons.  Usually you use the entire Zip file as the addon import.  For me, yesterday was a huge mess and a learning experience.  

Hope your SDK is now working.

Curious if you will have crashes.  My Blenders are crashing on export, but only on the interior model.

Also note, that your Materials may need to be 'Migrated'.  Check some of your Materials and see if there is a 'Migration' button appearing.

Bill Ortis
Lionheartcreations
