### ISSUE TITLE
Decal Material appears to make texture below transparent

### ISSUE THREAD

**Issue by PhysicsTeacher1** [AsoboStudio/glTF-Blender-IO-MSFS#146]
### Current Behavior

When a decal material is applied to a base textured surface, the decal material appears, but the material under it is turned transparent.
![Screenshot Decal Failure](https://user-images.githubusercontent.com/102252460/167125659-eb4215d4-77e2-4658-9907-bf933abce727.jpg)

### Expected Behavior

A decal is to be placed on one face of a cube.  The cube has been textured already and appears properly in the simulator.  I make up a decal using an image editor (Krita, in my case) and set the non-decal area to transparent (i.e. alpha mask).  I save the image as a .png file and as a .tif file.
I follow the discussion in the SDK manual for decals and, in edit mode, select a face of the textured cube for placement of the decal.  I create a new material slot in edit mode and assign it to one selected face of the cube.  I set that material slot to MSFS Meterial Params and the Type to Decal.
I follow the SDK manual instruction and load my decal texture into the Base Color slot.  I use the UV Editor to position the decal.  I expect the decal to appear with the main block texture underneath it, but the base texture behind the decal is transparent in the Blender 3D view - my base texture is not showing around the decal as expected.
I check that the Draw Order Offset of the base texture is 0 and then I set the Draw Order Offset of the  decal to a higher number so it will be drawn above the base texture.
I bring up the cube in the simulator Scenery Editor and place the cube object in a scene.
I expect to see the cube with texture on all six sides and my decal placed on the selected face.
What I see instead is my decal on a transparent surface, and, because that face is tranparent I see everything behind the cube faces in the rear.

### Steps To Reproduce

1. Create a cube.
2. UV unwrap and apply an image texture to the entire cube.
3. Create a decal image - one with color and an alpha layer to control transparency.  Save the image as both a .png and a .tif for later experimentation.
4. Select the cube and set Edit Mode.  UV unwrap one face, and add a material slot, assigning that slot to the selected face.
5. Load the decal image into the Base Color input as instructed.  Use UV Edit to place the decal properly.
6. Export the cube and invoke the compiler either with fspackagetool.exe or start the simulator and compile through the Project Editor.
7. Select a location and place the cube.
8. Note that the decal is placed on a totally transparent face, and, since the main material is not double-sided, you can see through the cube.

### Environment

```markdown
Computer: Dell G7 laptop
OS: Windows 10 Home
SDK: 0.18.0.0
Exporter: 1.1.6 (Release)
Blender: 3.1.0
Simulator: 1.25.7.0 Store, Basic Version
Years of experience with Blender: 6+
```

### Anything else?

It is entirely possible that I am doing something wrong, but I've spent a week now studying the problem.
I have watched and analyzed the node trees produced, and I see no difference between the Standard and the Decal node trees.
I have looked at the glTF files produced and see that the Draw Order Offset has been properly exported for each material.
I have been using simple .png images as my own "homebrew" decals on low LOD objects for a long time now with no problems.  Those materials were all Standard.  I have also used the same decal image saved as .tif.
I have used the Detail Color slot (RGB and Alpha) in the Standard type to great advantage with no trouble.
Is anyone using the Decal material successfully?  I can find very little on the subject, and I know there was no useable Decal material in the original (as improved by many) exporter.
I no longer have a license or working copy of 3DSMax to make comparisons.  Does Decal work there?
I will attach a .blend file and a couple of screenshots, hoping that will help.  I apologize for the size of the screenshots, but I wanted any labels to be readable.  I may also attach a package of my making.  In that package, the cube will be placed at the approach end of Rwy 34, KHPN on the centerline, but that may not be of use to you.
While playing around with rewiring the node tree, I noticed some instances where the mapped texture appeared as the pink checkerboard in the simulator, while appearing as a true decal in Blender, and I recalled someone having trouble with migrating windshield scratches. One attached screenshot in that post showed that pink checkerboard.
This is a truly versatile exporter - a much better UI than before, and I have re-exported many of my bridges with it while polishing them.  Thanks for all the hard work
[pt-modellib-decalfailuredemo.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8639734/pt-modellib-decalfailuredemo.zip)
[Test Decal Nodes.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8639738/Test.Decal.Nodes.zip)
.

**Comment by BrianDavos** [comment]
You're doing one thing wrong and that's applying the decal to the face which has the base material. A decal should be applied to a separate polygon to the main material. In edit mode, duplicate the face you want to apply the decal to and offset it by a millimetre or more from the original face. Then apply a decal material to that newly created face. 

Here's an example file:
[decal_example.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8639820/decal_example.zip)

**Comment by PhysicsTeacher1** [comment]
Yes, that's an old trick.  The implication of the SDK instructions is that
there are two or more draw calls for the dacaled face; that's why there is
a Draw Order setting.  That's what I'm asking.  If you look at the node
tree, the best way to apply an overlaid texture is to put the texture in
the Detail image slot.  I've used that a lot for added effects, but you
then have to route the Detail Alpha to the final node (called Base Color
Multiplier and then change its mode to Mix.  You also need to disconnect
the Alpha input to the Principled node.  This will give you two textures
overlaid on the face.  However, it does not export.  That's where the pink
checkerboard comes in.  I did not go into this in my writeup, since it is
peripheral.
I notice that your example did not have any texture at all, just a cube
with 7 faces.  If you intended to show a decal texture over another you
need to Pack them in the .blend file, then I would unpack them.  I'll add
some here to complete the example.
If the SDK implies that there will be two texture draw calls, ordered, then
I would like the exporter to work that way.  Your method works, but, as
implied by your two textures having the same Draw Order, it's not optimal
by a long shot.
Thanks for your attention to my issue, though.

**Comment by Mikeaat** [comment]
A node tree solution for this would be nice. A "decal" texture slot with a naming convention. So you can use multiple decals mixing it together in one blender material. :)

**Comment by PhysicsTeacher1** [comment]
I'm working on just that, but I think there's a fundamental problem: Blender can display two textures on one surface using a mask - either in Mask or Blend mode.  Multiple layers can be implemented in Blender using a chain of these node setups.  That's a simple graphics processor call, and the Detail Color entry does this for one layer as long as the underlying texture is an image.  However, the implication of the SDK Decal instruction page is that the Simulator can make multiple draw calls (implying an underlying mask/blend mechanism) on one surface.  That seems to me like a less processor-intensive solution than a long node chain or an entire extra surface that has to be treated as a separate object.
If someone could confirm that this multiple draw call mechanism exists, then it is worth creating a new Blender node that can 1) show the intended action in Blender but 2) export this as the data set needed to feed the multiple draw call mechanism.
So, the final requirement would be: Blender can display multiple, ordered textures in order but still export them so the Simulator mechanism can utilize them as separate, ordered draw calls utilizing their respective alphas.
Thanks, Mikeaat, for suggesting this.

**Comment by PhysicsTeacher1** [comment]
My apologies to BrianDavos: the old-fashioned way seems to be the only way.  If the simulator was able to do what I supposed it could from reading the Instructions and internally overlay multiple textures/decals on one surface/face at runtime, I would be happy.  I am able, however, to leave the extra faces co-planar with the base face and not have z-fighting if I am sure to use the Draw Order settings properly.  If I change the Draw Order of my to overlaid decals, their order reverses, as expected.  If I scale a face, however, the flickering comes back.  Attached is a picture showing the drawing order being reversed between the grunge and the text.  The Decal Material works as stated.
I withdraw my issue.
![Reversing Draw Order](https://user-images.githubusercontent.com/102252460/168429056-b0648bc6-932e-446c-a4f3-464fde02897c.jpg)
