### ISSUE TITLE
Import option with addon does not appear

### ISSUE THREAD

**Issue by Ghsotlydoggo** [AsoboStudio/glTF-Blender-IO-MSFS#148]
I cannot import with the addon it does not appear in the import option. I have tried a clean install of both blender and the addon.

**Comment by Pyscen312** [comment]
It would help if you tell us what version of Blender you installed the addon to.

**Comment by Dites33** [comment]
Same problem for me

Blender 3.1.2 / english
Addons in %AppData%\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs

Add on ACTIVATED

![image](https://user-images.githubusercontent.com/14044648/169603885-9b4bfcfd-a651-4b6a-82eb-d8394cfddc51.png)

Nothing in Import or Export menu

![image](https://user-images.githubusercontent.com/14044648/169604013-7dd7bb32-b814-4ebc-be53-7911874ed2a5.png)

**Comment by chickyacker** [comment]
Same thing here, exactly as described above. Since the exporter did not show up in the export options I unstalled Blender 3.1 and the Asobo exporter for Blender 3.1, then reverted to Blender 3.0 with the Asobo exporter for Blender 3.0, following the install directions to the letter, exited Blender and even rebooted, and the Asosbo exporter still does not show up in the Blender 3.0 export options after reboot, yet it shows as an active addon in the Blender preferences.

**Comment by realModsWanted** [comment]
**IMPORT**

The import function of the plugin relies on the standard plugin for the gltf format, which comes with blender as standard. Check it's activated in the Add-ons menu in Blender.
Also check that the Asobo exporter plugin is installed (according to the Description) and activated in Add-ons in Blender. Don't just copy the downloaded zip file into Blender and expect it to work, you have to unzip it first and copy the correct folder to your addons directory in Blender, if not already done.
![image](https://user-images.githubusercontent.com/98099299/169862892-88ca1ea2-7cf3-426d-bfc9-513ad7cd3278.png)

When both are installed and activated, to import a file, you go to...
![image](https://user-images.githubusercontent.com/98099299/169863856-8c0c10e2-52eb-42c0-b231-9d2979375217.png)

Then in the next import window on the right hand side must be "Importer Extensions -> MSFS Extensions" -> Make sure it is ticked "Enabled".
![image](https://user-images.githubusercontent.com/98099299/169864129-de44e042-0899-45c4-b5db-43bf38aa29df.png)

This way you have to import files / objects.

**EXPORT**

When you have created your model/objects, in Blender press th "N" key. This will open a menu on the right hand side in your 3d viewport. Look for "Multi-Export glTF 2.0" in the tabs. This is the Exporter. You can read the documentation on how to use it.
![image](https://user-images.githubusercontent.com/98099299/169865192-985425e3-bc85-4259-9f25-8596056a57a0.png)

**Comment by vpilotdesigns** [comment]
I have a problem importing with the standard plugin for models with DDS textures. It causes an error and does not import anything like the FBW blender addon did

**Comment by realModsWanted** [comment]
> I have a problem importing with the standard plugin for models with DDS textures. It causes an error and does not import anything like the FBW blender addon did

I think that should be under a new topic. Maybe something like "DDS textures support" or something like that.
