### ISSUE TITLE
Error: Extension MSFS_texture_dds is not available on this addon version

### ISSUE THREAD

**Issue by RoscoHead** [AsoboStudio/glTF-Blender-IO-MSFS#154]
### Current Behavior

When I try to import a MSFS gltf file, I get an error "Extension MSFS_texture_dds is not available on this addon version" and the model is not imported.

### Expected Behavior

Import 3D gltf model

### Steps To Reproduce

1. Install addon as per instructions
2. Enable addon
3. Choose File / Import / gltf
4. Choose gltf file, Import fails (even the stock c152 LOD0 fails)
![image](https://user-images.githubusercontent.com/86400867/171332615-7c0cf3a6-5da9-47d0-b2f0-3e69c908257b.png)

### Environment

```markdown
- OS: Windows 10 Pro 21H2
- Blender: 3.1.2
- glTF-Blender-IO-MSFS: 1.1.6
```

**Comment by pepperoni505** [comment]
Please see #151

**Comment by RoscoHead** [comment]
Thanks
