### ISSUE TITLE
GLASS material and alpha multiplier

### ISSUE THREAD

**Issue by Mariopilot808** [AsoboStudio/glTF-Blender-IO-MSFS#158]
### Current Behavior

In the shader tree, alpha is fed into the "Base color multiplier A". By default, the "value" is set at 0.5.

I imagine this value is controlled by the albedo texture, when present. In a lot of instances, the user will however implement no textures in a galss material.

This is not really a bug, but a suggestion.

### Expected Behavior

This parameter shall be available in the front-end for the user to set. it directly affects the transparency level of the glass material. 
Setting base color alpha to 0.01 (the minimum value, any lower and the glass disappears) is usually not enough to get a transparent enough color.
Setting this as well to 0.01 results in a very light glass.  Much fine tuning is now available.

### Steps To Reproduce

1. create a glass material
2. in the shader tree, edit the "value" in base color multiplier.
3. observe effect on material transparency.

### Environment

```markdown
- OS: Windows 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.16
```

**Comment by PhysicsTeacher1** [comment]
Agree.  Part of the Default Settings controversy.

**Comment by ronh991** [comment]
trying to understand your request.  I create a cube, then assign Glass as the material,  The Base Color A node is directly connected to the alpha on the BSDF - it's default is 1.0 in the value.  I see the Base Color Multiplier node as 0.5, however it is not connected to any other node, so will have no effect.  The Base color RGB node has it's alpha = 1.0, but will not affect anything.

Now linking the value out of the Base Color Multiplier node will take 1 and multiply by 0.5 for 0.5, but that's the same effect as setting the Base Color A node to 0.5

What am I not understanding in your request?

**Comment by Mariopilot808** [comment]
Tested this again. Placebo Effect,  please disregard this non-issue! As you said, this has no impact.
