### ISSUE TITLE
Typo in msfs_light.py

### ISSUE THREAD

**Issue by Cygnific** [AsoboStudio/glTF-Blender-IO-MSFS#159]
### Current Behavior

msfs_light.py:

blender_node.msfs_light_has_symmetry = extension.get("has_symmetry")

Asobo has it named and using "has_simmetry"

### Expected Behavior

Have "has_simmetry" exported,,

### Steps To Reproduce

Export a light and compare to Asobo model..

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

**Comment by ronh991** [comment]
Line 42 should be changed @pepperoni505 Should I do a PR, as Eric of ASOBO says this git can still be updated.

**Comment by y-khodja** [comment]
This has been fixed for SU12 ! 

Thank you for your report.
