### ISSUE TITLE
Texture export issue

### ISSUE THREAD

**Issue by pyreegue** [AsoboStudio/glTF-Blender-IO-MSFS#160]
### Current Behavior

When Image export is set to None it still exports the images and thus the model will not reload in the Scenery Editor like it does when exported with 3ds Max with the "Write Textures" box unchecked. 

### Expected Behavior

Textures should not be exported when Image Export is set to "None".

### Steps To Reproduce

In the settings tab in the Geometry section set Image to "NONE". Export. 

### Environment

```markdown
- OS: Win 11
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.5
```

**Comment by ronh991** [comment]
Looking at the code it seems that this feature is dependent on the Khronos blender core code (__init__.py).  And it seems they do not do anything with the dropdown selection.  (I may be wrong)
@pepperoni505 
lines 155, 545 and 785
Also the msfs_multi_export code has similar functionality.

**Comment by ronh991** [comment]
Further look into this, it seems the export is working correctly,  I textured a cube and exported. I set the geometry images to None and no textures are exported,  I set it back to automatic and they are exported.

Can you provide more detail on where you think this is going wrong.

**Comment by pyreegue** [comment]
> Further look into this, it seems the export is working correctly, I textured a cube and exported. I set the geometry images to None and no textures are exported, I set it back to automatic and they are exported.
> 
> Can you provide more detail on where you think this is going wrong.

Hello. Thanks for your investigation. Expected behavior is that when Image Export is set to "None", Images are not exported into the texture folder, but the materials are exported, which will allow object refresh in-sim with instant changes (Like with 3ds MAX). Right now if Image Export is set to None, the materials are not exported either, and that will mean the object will appear untextured in the simulator.

**Comment by ronh991** [comment]
I am not understanding the term "materials are not exported" do you mean missing in the gltf?  As there are no material files I believe.  Sorry not worked with scenery.

**Comment by ronh991** [comment]
Testing more . I find if you have the textures already in the texture folder you want they do not get over written, so I am unclear as to why the sim Scenery editor thinks that new textures have been added to the texture folder.

**Comment by pyreegue** [comment]
> Testing more . I find if you have the textures already in the texture folder you want they do not get over written, so I am unclear as to why the sim Scenery editor thinks that new textures have been added to the texture folder. Try leaving as Automatic.

When left in Auto it will still write the textures. What I mean by Materials not being Exported is that if you have a model in your scenery, compiled and placed, and then you re-export it with images set to "None", it will refresh in sim instantly but will not have said textures. If you uncheck the "Export Textures" box in 3ds max, it will export the model, export materials and it will refresh in sim instantly and textures will not vanish. Right now the plugin treats textures/materials identically and thinks it is the same thing.

**Comment by ronh991** [comment]
@AsoboEric Could you help me understand the issue here?  Why does the scenery editor treat models different than Aircraft? and is there a way to emulate the Write Textures checkbox in Blender?  Is there a different Build functionality?

**Comment by Wombii** [comment]
Background info: 
Since some time last year the sim stopped being able to fluently reload scenery models when exported with textures in the project editor or scenery editor. When exported with textures the console will inform that it has detected new gltf+bin files, then new png files, then inform that it can't load a png file. 
If you then open the gltf file in a text editor and save it the sim will detect only the "new" gltf file, convert the associated png files to dds and reload the model.

**Comment by y-khodja** [comment]
Hello all,

I have tested what you asked for, the blender exporter already does what you are asking for in Blender 3.3, if you set materials to export and texture to none. We have the materials information in the gltf and not the textures (see the figures bellow). 

I am not sure to get your repro steps.

![image](https://user-images.githubusercontent.com/114567493/232441026-050ecf3c-3b84-4ea2-b7a5-899de85408d2.png)
![image](https://user-images.githubusercontent.com/114567493/232441072-fbc6a954-b335-4337-be0d-017ac433cfc2.png)
