### ISSUE TITLE
Emissive Scale can not be set to a value greater than 1.

### ISSUE THREAD

**Issue by pyreegue** [AsoboStudio/glTF-Blender-IO-MSFS#161]
### Current Behavior

Emissive Scale can not be set to a value greater than 1, in 3ds it can be set up to 100. (So does mention the SDK Manual). Currently it can not be set higher than 1.

### Expected Behavior

Allow values of 0-100

### Steps To Reproduce

Try to set emissive scale higher than 1.

### Environment

```markdown
- OS: Win 11
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.6
```

**Comment by y-khodja** [comment]
Hello,

It's fixed here: 
Merge pull request [#180](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/issues/180) from ronh991/emissive-scale-gt-1.0

Thank you !
