### ISSUE TITLE
Lights exported by 1.1.6 unrecognized in Blender 3.2

### ISSUE THREAD

**Issue by PhysicsTeacher1** [AsoboStudio/glTF-Blender-IO-MSFS#162]
### Current Behavior

Punctual lights exported from Blender 3.1 using 1.1.6 compile with no problems.  Same lights exported from Blender 3.2 with 1.1.6 give compile error  "required extension not supported: KHR_lights_punctual".

### Expected Behavior

Punctual lights exported with Punctual Lights ticked in Settings should compile properly.

### Steps To Reproduce

1. Create scene with some punctual lights - point and spot.
2. Export from properly configured (exporter 1.1.6) Blender version 3.1.
3. Compile in simulator (live, not external (untried yet)) and verify proper compilation.
4. Exit Blender 3.1 and open Blender 3.2.1.  Reopen light scene.
5. Export using 1.1.6 and verify that export was OK.
6. Compile in simulator and note that error  "required extension not supported: KHR_lights_punctual" is thrown.

### Environment

```markdown
- OS: Windows 10 Home
- Blender:3.1 and 3.2.1
- glTF-Blender-IO-MSFS:1.1.6
```

### Anything else?

Note that the Khronos glTF exporter shipped with Blender 3.1 is version 1.8.19 while version shipped with Blender 3.2.1 is version 3.2.43.
Your staff are remarkable!  I hope this is not too big a problem.  Thanks for all you do!

**Comment by collinbrady** [comment]
Do we have any traction on this one? Not sure if this is related:

I'm on Blender 3.1.2 and my lights are not compiling when they were working with previous forked exporters. Here's compiling errors for just the lights using the latest glTF-Blender-IO-MSFS exporter:

![asobo-blender-export-lights](https://user-images.githubusercontent.com/6147914/209180666-0e869aef-afcf-4165-be21-d764aac69aab.jpg)

**Comment by ronh991** [comment]
@collinbrady If you uncheck the Use Asbob_unique_id_Extension, does that fix things?
![DA40CGDFQ_2022 12 23_11h20m01s_08](https://user-images.githubusercontent.com/19254353/209366903-d4718fe9-2cbf-45a6-8f70-1cd6507f047f.png)

**Comment by ronh991** [comment]
@collinbrady 
![DA40CGDFQ_2022 12 23_11h53m45s_09](https://user-images.githubusercontent.com/19254353/209372657-0f592438-7d25-401e-bf13-5a48429a9695.png)

**Comment by collinbrady** [comment]
Ah thank you so so much. I couldn't find a direct answer to this one with those error terms - this worked!

So that option - looks like it's for "the glTF merge feature to merge/combine multiple glTF"?

I assume I may never be using that one, I'm unclear what it is for based on the sparse documentation.

Regardless, thank you!
