### ISSUE TITLE
Compile error by proper exported .gltf

### ISSUE THREAD

**Issue by wodecffb** [AsoboStudio/glTF-Blender-IO-MSFS#163]
Current Behavior

Point and Spot lights and exported from Blender 3.1 using 1.1.6 compile with no problems. If I compile the Object with fspackagetool I got some errors: 
Compiling GLTF data file EDHK_Tower.gltf...
Node without Unique ID while using the unique_id extension, nodes[4] : 'PointFW1_Orientation'
Node without Unique ID while using the unique_id extension, nodes[7] : 'Point_Orientation'
Node without Unique ID while using the unique_id extension, nodes[26] : 'SpotFWR_Orientation'
Node without Unique ID while using the unique_id extension, nodes[30] : 'SpotFWL_Orientation'
GltfCompiler | Failed to load model data from file. I open the .gltf in Visualstudio Code serarch for PointFW1_Orientation and find this:
{
            "name" : "PointFW1_Orientation",
            "rotation" : [
                -0.7071067690849304,
                0,
                0,
                0.7071067690849304
            ]
        },

If i insert the follow lines:
{
            **"extensions" : {
                "ASOBO_unique_id" : {
                    "id" : "PointFW1_Orientation"
                }
            },**    
            "name" : "PointFW1_Orientation",
            "rotation" : [
                -0.7071067690849304,
                0,
                0,
                0.7071067690849304
            ]
        },

the compiler error has gone.

Environment

- OS: Windows 10 Pro
- Blender:3.1 and 3.2.1
- glTF-Blender-IO-MSFS:1.1.6

**Comment by y-khodja** [comment]
Hello ! 

I added a check for this option in the multiExporter view. You should see it in the settings view as shown in the image down bellow ! 

Thank you 

![image](https://user-images.githubusercontent.com/114567493/206164180-f27a409b-0e8d-4034-9318-c6741b237c61.png)

**Comment by wodecffb** [comment]
Thank you
