### ISSUE TITLE
not working in Blender3.3

### ISSUE THREAD

**Issue by leanoon** [AsoboStudio/glTF-Blender-IO-MSFS#164]
### Current Behavior

create a simple cube, and export by using this addon,

then, error report

++++++++++++++++++++++++++++++++++++++++++++++++++++++
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 171, in execute
    MSFS_OT_MultiExportGLTF2.export(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 45, in export
    bpy.ops.export_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "export_displacement" unrecognized

### Expected Behavior

in blender 3.2.2 , just work fine as always.

### Steps To Reproduce

1.open blender (normal or in admin mode)
2.create a simple mesh such as a cube
3.add a material
4.try to export
5.encounter error
![image](https://user-images.githubusercontent.com/16299740/189467281-d22cd587-81d8-40c7-af91-f847e0a14a84.png)

### Environment

```markdown
- OS:WIN11
- Blender:3.3
- glTF-Blender-IO-MSFS:1.1.6
```

**Comment by ronh991** [comment]
Blender 3.3 has a breaking change for COMP textures.  The node name and input/outputs have been renamed and are not compatible with the ASOBO export - or for that matter the legacy Vitus one and other derived from that code.

**Comment by leanoon** [comment]
> Blender 3.3 has a breaking change for COMP textures. The node name and input/outputs have been renamed and are not compatible with the ASOBO export - or for that matter the legacy Vitus one and other derived from that code.
> 
> I know most likely that would not be your problem, but just sayin 3.3 has broken the exporter as it is.

wow, thank you, seems i need to wait for a while

**Comment by alex1954ku** [comment]
Hello.  When will this problem be solved?
++++++++++++++++++++++++++++++++++++++++++++++++++++++
Error: Python: Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 171, in execute
MSFS_OT_MultiExportGLTF2.export(
File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 45, in export
bpy.ops.export_scene.gltf(
File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in call
ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "export_displacement" unrecognized

**Comment by alex1954ku** [comment]
The author probably abandoned the project. Does not answer questions. Thanks

**Comment by tml1024** [comment]
> The author probably abandoned the project. Does not answer questions. Thanks

Yeah, this does not look good.

**Comment by jugOS-19** [comment]
I don't know if this is the solution but it is working for me for very basic scenery:
- If you read the documentation, Blender 3.3 doesn't support de displacement export anymore (I have very little knowledge of Blender so I don't know what displacement is).
- The error is in the msfs_multi_export.py (python source code), so open it with any text editor and look for the export_displacement flag (around line 75)
- Comment that line and save the file
- The export should work now (at least, that error is bypassed)

**Comment by y-khodja** [comment]
Fixed in https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/commit/ed4fa7447b27eab330d5a0596b5b1c727d1a28ca
