### ISSUE TITLE
Inactive collection exported regardless of settings

### ISSUE THREAD

**Issue by erasam** [AsoboStudio/glTF-Blender-IO-MSFS#166]
### Current Behavior

A nested inactive collection is exported regardless of the Active Collection is set in the Include settings

Actually inactive collections (not nested) are corectly not exported (if not selected in the Objects list (when grouped by collections)

### Expected Behavior

All inactive collections should not be exported if the Active Collection is set

### Steps To Reproduce

Just follow the description of the issue

### Environment

```markdown
- OS: Win 10
- Blender: Blender 3.1
- glTF-Blender-IO-MSFS: Release 1.6
```

**Comment by y-khodja** [comment]
Hello,

Can you give a specific example where this is not working ? I tried to repro by exporting with the multi-exporter and it seems to work perfectly.
