### ISSUE TITLE
MS Material - Disabled actions?

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#167]
### Current Behavior

If you change a MSFS material from say standard to disabled, the values for the parameters of the nodes are saved.  Is this designed behavior?  I would assume you would set all the material parameters back to their default values.  So you could start over with defaults.  even going into the shader screeena nd manually deleting the nodes there will keep the parameters.

### Expected Behavior

If you set the MSFS material to disabled, the parameters for all the nodes are set to default values.

### Steps To Reproduce

Make a MSFS material - standard.
Set the metallic factor to something other than 1.0 - 0.3
Set the Roughness factor to .5
Save the file
Set the MSFS material to disabled. note all the MSFS node disappear - so assumed all the parameters would be erased also.
set the MSFS material back to standard. - see the metallic factor and the roughness factor back to previous values.

### Environment

```markdown
- OS:windows 10
- Blender:3.1
- glTF-Blender-IO-MSFS:1.6
```

**Comment by y-khodja** [comment]
Hello,

It's fixed in the new release 1.3.1 ! 

Thank you for your report
