### ISSUE TITLE
Can't export common/shared collections

### ISSUE THREAD

**Issue by SFSimDev** [AsoboStudio/glTF-Blender-IO-MSFS#168]
Hi,

This may or not be a bug so please let me know.

We usually export with a shared collection of VFX and attachment points selected. E.g.

Effects
LOD00
LOD01
..etc

Is there a way of doing this in the plugin without having to copy the shared objects into the LOD collection?

Output using the tool

Effects.xml
LOD00.xml
LOD01.xml
..etc

The workaround is to duplicate the Effects into each LOD Collection but this seems counterintuitive and also takes longer. Can the tool export a shared/common collection or are we using it wrong?

Thanks for reading

Chris

**Comment by Wombii** [comment]
You can do custom export setups like that through the "presets" tab instead of the "objects" tab.
![image](https://user-images.githubusercontent.com/60835350/197390125-d05f933b-088b-447b-9203-6c2718efc9d7.png)

**Comment by SFSimDev** [comment]
> You can do custom export setups like that through the "presets" tab instead of the "objects" tab. ![image](https://user-images.githubusercontent.com/60835350/197390125-d05f933b-088b-447b-9203-6c2718efc9d7.png)

Brilliant, thanks for this I'll take a look :)
