### ISSUE TITLE
Any Chance on a time frame for when we get a Blender 3.3 Exporter update?

### ISSUE THREAD

**Issue by lyonheart001** [AsoboStudio/glTF-Blender-IO-MSFS#169]
Hello Team Asobo,

Do you have a time frame on when we might recieve a new exporter that can export Blender 3.3 and 3.4 models?

Supposedly there are better UVW tools in Blenders 3.3 and also 3.4 Beta.  

Perhaps we could do a Beta release of a new exporter and start getting this running and testing it?

Bill
Lionheart Creations

**Comment by FlyByTim** [comment]
Also interested!

**Comment by ronh991** [comment]
Work has restarted - this issue can be closed please.
