### ISSUE TITLE
Exporter  Error - console window - Color channelmetallic

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#17]
Getting the following error on export of Testplane
14:49:04 | WARNING: Image '<bpy_struct, Image("testplanefroma_metallic.png") at 0x000001C6AF26F208>' has no color channels and cannot be exported.

**Comment by ronh991** [comment]
still error in commit 1d8ef641567e97de1fabbaf9413c252a9c932cdf

**Comment by pepperoni505** [comment]
@ronh991 Are you still having this issue? IIRC I think it was a strange Blender caching issue

**Comment by lpierabella** [comment]
isn't this related to old material shader tree? 
can you link a test file in case it is still the case?

**Comment by ronh991** [comment]
Possible - legacy data in blend model issue.  This error no longer appears during export of newer blend file.
