### ISSUE TITLE
Blender Version Notation in this release

### ISSUE THREAD

**Issue by lyonheart001** [AsoboStudio/glTF-Blender-IO-MSFS#171]
Hello, 

I do not see a 'Blender Version Requirement' in the imformation on this SDK Kit.  Could you let us know which version of Blender it works with?  For instance, does it only work on Blender 3.2 or lower, or can it work with both 3.2, and 3.3 and 3.4?  (I believe 3.3 and 3.4 are pretty much the same, but they do have an issue with the COMP maps in 3.3 on up).

Kind regards and keep up the great work.  Thank you for an SDK for Blender.  In my view, Blender is far superior to Max.

Bill Ortis
Lionheart Creations

**Comment by y-khodja** [comment]
Hello, 

The curent exporter works only with Blender 3.3 LTS. 

Thank you !
