### ISSUE TITLE
Import export option not visible

### ISSUE THREAD

**Issue by nebj00la** [AsoboStudio/glTF-Blender-IO-MSFS#172]
It's very possible that I'm missing something here, but I can't get the import/export items to show up after installing version 1.1.5 or 1.1.6 with Blender 3.1.

Import / Export option should be visible.

1. Import io_scene_gltf2_msfs folder via zip method or manual folder copy.
2. Enable addon.
3. Click File->Export.
4. Option is not visible.

- OS: Windows 11
- Blender: 3.1.0
- glTF-Blender-IO-MSFS: 1.1.6

**Comment by nebj00la** [comment]
![blender-export-menu](https://user-images.githubusercontent.com/6364521/199748047-4b85c1ae-db9c-45aa-91ff-8c31a3a86837.png)

**Comment by EvenAR** [comment]
Where did you find it, @nebj00la ?

**Comment by nebj00la** [comment]
> Where did you find it, @nebj00la ?

@EvenAR Enable the plugin, and then hit the "N" key. It brings up a new menu, where you'll see the following:

![image](https://user-images.githubusercontent.com/6364521/200435283-e32944e0-ca73-44ed-b5a7-1028f1a48afe.png)
