### ISSUE TITLE
Can no longer successfully export windshield material

### ISSUE THREAD

**Issue by Michael-Cependa** [AsoboStudio/glTF-Blender-IO-MSFS#173]
Since SU11 and/or the related SDK update I can no long get the windshield material to export properly.  The SDK package builder started requiring me to put my textures in incorrect slots.  (Otherwise, the model won't load them in the sim and shows a pink checkerboard.) 

Eventually I discovered where it wants them but the windshield won't display properly when I place the textures in the required slots.  Without painting the vertices, the windshield displays about 80% opaque.  If I paint the vertices all red, then the windshield becomes completely  transparent.  Any green vertices cause massive areas of heavily opaque windscreen. There is no middle ground with the transparency and neither dirt nor scratches display at all.  However, the rain and ice do display properly although the ice looks a little off.  Before SU11 the windscreen displayed correctly and at the time I hadn't got around to painting the vertices.

I've attached a screenshot showing how the SDK is requiring me to place the textures.  If I don't set them up this way (which is not how I had them before and obviously incorrect) the package builder console will say that two of them are in "incompatible" slots.  The icing bump map doesn't cause a problem, just the other two. I am using Asobo provided textures. 

![windshield](https://user-images.githubusercontent.com/106225584/204201489-46e5c349-2c18-465f-9d2b-84e83a0fa0e8.jpg)

**Comment by y-khodja** [comment]
Hello,

Can you send us your blend file, GLTF(s) and your repro steps to have more informations ?

**Comment by y-khodja** [comment]
Hello, 

It has been fixed in the new release 1.3.1 !

Thank you for your report !
