### ISSUE TITLE
Shape keys support

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#174]
Shape keys are not being exported and impossible to use.
Please enable this to deform mehses.

ps. apply modifier at export should not apply shape keys!

![image](https://user-images.githubusercontent.com/93551041/204251020-3f7af7b8-1ac5-4f9e-b22b-c0a2f27b2401.png)

Thank you

**Comment by y-khodja** [comment]
Hello @tonypez ,

Unfortunately morph targets are not supported in game for now. The official exporter gltf Blender supports them and you will get the targets in the primitive like this: 

 ```
{
    "primitives": [
        {
            "attributes": {
                "NORMAL": 23,
                "POSITION": 22,
                "TANGENT": 24,
                "TEXCOORD_0": 25
            },
            "indices": 21,
            "material": 3,
            "targets": [
                {
                    "NORMAL": 33,
                    "POSITION": 32,
                    "TANGENT": 34
                },
                {
                    "NORMAL": 43,
                    "POSITION": 42,
                    "TANGENT": 44
                }
            ]
        }
    ],
    "weights": [0, 0.5]
}
```
It won't be interpreated in game.

If you want to change the apply modifier, please report your issue in the official exporter for Blender : https://github.com/KhronosGroup/glTF-Blender-IO

Thank you for your report !
