### ISSUE TITLE
SSS Material export issue

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#176]
SSS material is not exporting anymore with this exporter, it was previously working.

![image](https://user-images.githubusercontent.com/93551041/204252052-c52a106f-6f7c-470e-b225-cf9b6e93980f.png)

**Comment by Michael-Cependa** [comment]
I could never get it working and I when I raised the issue here I was informed it isn't supported.

**Comment by Michael-Cependa** [comment]
I'm sure it does, but I need to be able to export it.  Hand editing the model file is not something I want to get into.

**Comment by tonypez** [comment]
I think what FrogBucket wanted to say is that SSS is supported from the game and you can prove it by editing the text, just our exporter is broken and doesn't export it for some reason, we need Asobo to fix it.

**Comment by Michael-Cependa** [comment]
Understood.  I never doubted the sim supported it -- I interpreted Asobo's reply to mean the exporter didn't presently support it.  What I meant to say was simply that I will wait for the exporter to get updated it rather than get into hand editing model files.  Didn't mean to sound flippant if that's how it came across.

**Comment by rhumbaflappy** [comment]
The Hair material also does not export a glTF. It is essentially the same material as SSS.
`  "materials": [
    {
      "name": "Hair",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          1.0,
          1.0,
          1.0,
          1.0
        ],
        "roughnessFactor": 1.0,
        "metallicFactor": 1.0,
        "baseColorTexture": {
          "index": 0
        },
        "metallicRoughnessTexture": {
          "index": 1
        }
      },
      "emissiveFactor": [
        0.0,
        0.0,
        0.0
      ],
      "normalTexture": {
        "index": 2
      },
      "occlusionTexture": {
        "index": 1
      },
      "doubleSided": true,
      "extensions": {
        "ASOBO_material_anisotropic": {
          "wetnessAOTexture": {
            "index": 3
          }
        },
        "ASOBO_material_SSS": {
          "SSSColor": [
            1.0,
            1.0,
            1.0,
            1.0
          ]
        }
      }
    }
  ]`
