### ISSUE TITLE
Group by NLA Track - not working

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#178]
If the option "Group by NLA Track" is unchecked, the exporter is not going to export any animations.

By having this option always turned on, a lot of animations can end up mixing, please make it possible to use this option:
![image](https://user-images.githubusercontent.com/93551041/204253253-c52803bf-cfc0-4f5e-a0cf-c0101fb599ec.png)

**Comment by y-khodja** [comment]
Hello,
I suppose it's the same issue as : #179
