### ISSUE TITLE
Animation NLA - mixing up (IMPORTANT)

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#179]
Hello there,

there an important issue to solve with blender exporter regarding animations.
Blender does not support animation groups like 3DSmax.

It is impossible in blender to export an armature which has multiple bones with several NLA animations without these mixing up in game.

example 1: 
**Wing flex**
To make the wings to flex, we need an armature with multiple bones (as the SDK suggests), some bones are deforming the wing and some other are rotating the flaps.
The result is 1 armature with multiple bones/animations (wing flex + flaps+ slats)
As soon as you have this armature with multiple animations, this is not working in game, the animations end up mixing together instead of playing separately, for example when the wing is flexing, the flaps are moving too or viceversa.

example 2:
**Human skinned mesh**
you have a human armature with multiple bones, the human should move the arms with the first NLA and the legs with the second NLA.
the human animations will end up mixing in game, when moving the arms, the legs are going to move too.

Exmaple 3: 
**Helicopter rotor animation**
Some components of the rotor mechanism needs complex movements such as the rods connecting to other pieces which have animations themselves, these rods are supposed to make 3 different movements, that means they need 3NLA.
As soon as you assign 3NLA to this object or bone, they will end up mixing in game.

All NLA were baked.

this is an armature with multiple tracks, creating the issue:
![image](https://user-images.githubusercontent.com/93551041/204256935-5e749135-8635-4baf-96a5-391cde76bc5f.png)

If you need an example, I can prepare one.

Please give this issue the maximum priority, because it's Impossible to make anything serious without this working.
Merci.

**Comment by y-khodja** [comment]
Hello,

Can you send us a blend file as example to test with your repro steps. 

Thank you !

**Comment by tonypez** [comment]
> Hello,
> 
> Can you send us a blend file as example to test with your repro steps.
> 
> Thank you !

Hello y-khodja, good to read from you!

I have just prepared a dummy blend file, a package and a video explaination for you regarding this issue.
the scenario I am showing here is simple and could be solved with empties instead of an armature but, that is not the case in many other more complex scenarios.

You are going to find 2 blend files, they are identical except the fact that one of the 2 has baked NLA frames.
The video is explaining you the issue, you can see how the result in game looks different than in blender, the pieces are out of place the animations do only move within a restricted range instead of the full extension.

The file I am trying to attach to this reply is larger than 25 mb, I had to upload it via Wetranswer, here the link to dowload:


**Download link**
[https://wetransfer.com/downloads/1871dfe441361ba7fba73bfeeb4f9e6620221129164909/c1b6747e853aa5696984afa0b5e7273d20221129164927/816618](https://wetransfer.com/downloads/1871dfe441361ba7fba73bfeeb4f9e6620221129164909/c1b6747e853aa5696984afa0b5e7273d20221129164927/816618?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)
1 item
NLA_MIXING.zip
81.2 MB

Thank you!

**Comment by lyonheart001** [comment]
Hello @tonypez , 

JonX has a good tutorial which shows how to setup a joystick Armature which will have 2 animations on it.  Its on YouTube.  He exports and builds it in Blender, I think 3.3, not sure.

https://youtu.be/UIGI8ZjV4yA

Bill
LHC

**Comment by Michael-Cependa** [comment]
I was able to get my wing flex animations working correctly today.  if you uncheck the channel muting boxes in the NLA editor opposite the animation names, the wing animations will work with wing flex in the sim.  They won't animate in Blender however while the boxes are unchecked.  Using Blender 3.1.2 with the latest Asobo exporter.

**Comment by tonypez** [comment]
> I was able to get my wing flex animations working correctly today. if you uncheck the channel muting boxes in the NLA editor opposite the animation names, the wing animations will work with wing flex in the sim. They won't animate in Blender however while the boxes are unchecked. Using Blender 3.1.2 with the latest Asobo exporter.

Hello Michael, 
I am happy to hear it worked in your case.
I just tried on the example linked above, and this didn't solve the issue. You can download the zip above and try yourself.
How many NLA do you have on your armature?

I need the specific case linked above to work without "mixing" or "halved NLA lenght".
If anyone thinks to have tje solution, please download the sample data attached in the first post and try yourself.

**Comment by Wombii** [comment]
Have you tried adding an NLA track in the first slot called "default" with every bone keyframed in the rest pose? The exported armature from blender seems move relative to the rest pose and the first NLA track.
I tried your Armature_mix_non_baked_NLA.blend file. Reset the rest pose, added a default track, redid the other animations. Works for me in the sim.
![image](https://user-images.githubusercontent.com/60835350/206747815-c5f1fa89-fde4-48f9-9d10-bde054090451.png)

https://www.youtube.com/watch?v=wgoFV9GGum8

[Armature_mix_non_baked_NLA.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10196498/Armature_mix_non_baked_NLA.zip)

**Comment by tonypez** [comment]
> Have you tried adding an NLA track in the first slot called "default" with every bone keyframed in the rest pose? The exported armature from blender seems move relative to the rest pose and the first NLA track. I tried your Armature_mix_non_baked_NLA.blend file. Reset the rest pose, added a default track, redid the other animations. Works for me in the sim. ![image](https://user-images.githubusercontent.com/60835350/206747815-c5f1fa89-fde4-48f9-9d10-bde054090451.png)
> 
> https://www.youtube.com/watch?v=wgoFV9GGum8
> 
> [Armature_mix_non_baked_NLA.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10196498/Armature_mix_non_baked_NLA.zip)

Hi Wombii

thank you for trying this out, that looks really good.
I previously tried to add the "default state" with few frames only and it didn't work, you actually baked all frames of the default state which I didn't before, that seems smart, I am going to try it out.

**Comment by Michael-Cependa** [comment]
My wing armature presently has two animated bones working -- one for an aileron and one for a spoiler p;anel.  They flex with the wing correctly and animate independently.  As you the problem arises only when there is more than one animation on the same armature.  Unchecking the channel mixing boxes was the missing link for me to get it working with this exporter.  I tried everything else I could think of and only that one thing stopped the animations moving together. 

I have set up my wing as in the example found in this thread at fsdeveloper:  https://fsdeveloper.com/forum/threads/having-trouble-with-wing-flex-and-blender-to-msfs-exporter.450538/#post-910273

Look at the example blend file by Bancal.

**Comment by tonypez** [comment]
hello @y-khodja ,
thanks to @Wombii, we have the solution to the issue, although I found additional problems here, I try to explain what remains to be solved.
Adding the "default track" is necessary to make the animation to look correctly in game but:
- exporting the file with blender 3.2, all animations are mixing
- exporting the animation with blender 3.1, all animations are mixing
- exporting with blender 3.1.2, all works fine,

The issue is the mainly the blender release, please make this to work for blender 3.3 LTS (the right solution is the one from blender 3.1.2 version).

Thank you @Wombii for good solution.

@y-khodja Thank you for taking care of the issue, hopefully you can fix this for good since it takes a lot precious times for devs to find out where the problem is.

**Comment by y-khodja** [comment]
@tonypez Hello, 
I see ! I will try to make it work for the last release of blender. I will on the other hand take a look on the difference between these version to see if it's possible to make it work.

@Wombii Thank you for your support !
