### ISSUE TITLE
Exporter error - Console window - missing export settings in code

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#18]
getting the following error on export of test plane
14:48:47 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
gather_material_hook fails on <io_scene_gltf2_msfs.glTF2ExportUserExtension object at 0x000001C6AA43D370>
gather_texture_info() missing 1 required positional argument: 'export_settings'

**Comment by pepperoni505** [comment]
This should be fixed in #11

**Comment by ronh991** [comment]
gather_texture_info() missing 1 required positional argument: 'export_settings' has be fixed, however gather_material_hook fails on <io_scene_gltf2_msfs.glTF2ExportUserExtension object at 0x000001C6AA43D370> message is still seen.  The export does work in the sim.  Testplane no longer CTD sim.

**Comment by pepperoni505** [comment]
This is also fixed in #26
