### ISSUE TITLE
Is it working in Blender 3.4

### ISSUE THREAD

**Issue by mroschk** [AsoboStudio/glTF-Blender-IO-MSFS#183]
Hello,
as the Title says, is it working in Blender 3.4 ?

Matthias

**Comment by alex1954ku** [comment]
Hello. It doesn't work for me!?
![Export_Error](https://user-images.githubusercontent.com/48827822/208144527-87a8c205-05a2-44f1-992a-42195a2e1f1d.jpg)

**Comment by ronh991** [comment]
No there is a new breaking change to blender 3.4 for the MixRGB node.  It has been renamed to Mix, and the input and output indices are different.  This is similar to the Breaking change for 3.3 where the SeparateRGB node has changed also,

The ASOBO exporter is currently only compatible with Blender 3.1.2 and 3.2

**Comment by mroschk** [comment]
Hello,
thanks a lot for the answer, so i must not wonder :-)

I think there will be a update comming...

Matthias

**Comment by y-khodja** [comment]
Hello, 

We have to stick to Blender 3.3 for now as it's the latest LTS version of blender. We can't assure that everything would work with other versions of blender.

Thank you !
