### ISSUE TITLE
2 Animations issues with blender 3.1.2

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#184]
hello there,

I found another 2 animation issues, again frustrating because of blender versions.
the following issues are existing when exporting from blender 3.1.2 while they do not exist when exporting the same file from blender 3.2

**Issue 1) - Blender bones constraints**
given a rigged mesh (skinned mesh) like a human body, which is using **blender bone constraints**, for example IK constraint or Child of bone constraints (which are essential for animation making), the exporter is ignoring the baked NLA and showing me the T-pose (completely ignoring the constraints and the pose from blender)

![image](https://user-images.githubusercontent.com/93551041/208501387-135bd603-1193-4b9f-93b5-9ae9cf957e72.png)

Exporting the same identical file with blender 3.2 instead, the human is in the right pose and the animation is working

![image](https://user-images.githubusercontent.com/93551041/208498916-a4f4ff87-950e-4224-9589-391c2d0133b9.png)

This is currently blocking my workflow, after I got the animation mixing issue solved (reported to you in the other thread you already resolved, the solution was to use blender 3.1.2).
Using blender 3.1.2 version I do not have the mixing NLA issue anymore but have now this new blender constraints issue which is even worse making animations not usable

This is where the constraints are located in Blender:
![image](https://user-images.githubusercontent.com/93551041/208504395-5201b730-bc38-4e15-8b10-ac355a0a0ab4.png)

**A few additional info:**
- I tried baking the NLA with visual keys and deleted all constraints from the armature (still does not work even if it should).
- I tried with single NLA and multiple NLA stack, also with a default_State NLA
- it's working fine with blender 3.2, so the issue is clearly blender 3.1.2 and not the model

**Issue 2) - Animation with scale**
Given a skinned mesh like a simple sphere rigged to a bone:
![image](https://user-images.githubusercontent.com/93551041/208503219-09726816-6b1b-4812-bdad-75d15ff91173.png)

If that central bone has a scale animation from 0.1 to 1 size, (imagine an inflating balloon going from little to big and the big position is the default pose), the exporting results looks wrong in game using blender 3.1.2
The animation in game starts from scale 1 to 10x (from the big position to an even bigger one which is not existing in blender)

Exporting the same file with blender 3.2, the animation will look correct, inflating from 0.1 scale upto 1.0 size (from the tiny balloon to the default size one).

We are forced to work with Blender 3.1.2 because it comes with more benefits when using the Asobo exporter but... some stuff like these animation issues are unfortunately a big limitation. 
Hopefully we can get a quick fix to all these animations issue, I really need them to work.

Thank you

**Comment by tonypez** [comment]
is there any debug activity going on? any chance to get the issue above fixed soon?
I hope in a quick fix, this is important to keep moving with projects.
Thank you.

**Comment by y-khodja** [comment]
Hello !

Can you send me your Blend files to get the repro ? 

Thank you

**Comment by tonypez** [comment]
> Hello !
> 
> Can you send me your Blend files to get the repro ?
> 
> Thank you
[Animations_Issues_report.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10479892/Animations_Issues_report.zip)

Hello Y-khodja,

I have just created the 2 blend files that recreate the error and relative package file to test in game.

The 2 issues are explained in the post above. Just as a reminder, if you export with blender 3.1.2 the animations won't work correctly in game while if you export with blender 3.2, these will work correctly.

We are forced to use Blender 3.1.2 because it is the current supported version and it comes with additional advantages, unfortunately with this version we have animations issues that can't be solved, hopefully you can drop us a fix soon.

Thank you

**Comment by y-khodja** [comment]
We have released a new version of the exporter supported by Blender 3.3 you should use this one from now on as it's intended for an LTS version of Blender. 

> > Hello !
> > Can you send me your Blend files to get the repro ?
> > Thank you
> > [Animations_Issues_report.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10479892/Animations_Issues_report.zip)
> 
> Hello Y-khodja,
> 
> I have just created the 2 blend files that recreate the error and relative package file to test in game.
> 
> The 2 issues are explained in the post above. Just as a reminder, if you export with blender 3.1.2 the animations won't work correctly in game while if you export with blender 3.2, these will work correctly.
> 
> We are forced to use Blender 3.1.2 because it is the current supported version and it comes with additional advantages, unfortunately with this version we have animations issues that can't be solved, hopefully you can drop us a fix soon.
> 
> Thank you

**Comment by tonypez** [comment]
> We have released a new version of the exporter supported by Blender 3.3 you should use this one from now on as it's intended for an LTS version of Blender.
> 
> > > Hello !
> > > Can you send me your Blend files to get the repro ?
> > > Thank you
> > > [Animations_Issues_report.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10479892/Animations_Issues_report.zip)
> > 
> > 
> > Hello Y-khodja,
> > I have just created the 2 blend files that recreate the error and relative package file to test in game.
> > The 2 issues are explained in the post above. Just as a reminder, if you export with blender 3.1.2 the animations won't work correctly in game while if you export with blender 3.2, these will work correctly.
> > We are forced to use Blender 3.1.2 because it is the current supported version and it comes with additional advantages, unfortunately with this version we have animations issues that can't be solved, hopefully you can drop us a fix soon.
> > Thank you

Hello Y-Khodja,

thank you for mentioning the new exporter.
I am now running tests with 3.3 and relative msfs exporter version.
good and bad news:
the good news is that the 2 issues listed above are working with 3.3 version
the bad news is that other things that were working with before are now causing "export fail", that means the main project is not exportable anymore with 3.3.

I am going to try to isolate the issue and report them as a separate 3.3 threads.
The first one i found is that the export failes when a specific animation "action" exists in the blend file even if not exported (this is exporting with 3.1.2)
