### ISSUE TITLE
Can't get it to install on Blender 3.2

### ISSUE THREAD

**Issue by Kelleytoons** [AsoboStudio/glTF-Blender-IO-MSFS#185]
Oddly enough I got this to install on Blender 3.4 (wouldn't import without errors, though) but when I installed Blender 3.2 and followed the instructions to copy to the right add on directory it SHOWED UP in the plugins, but would not show up when I went to import it.

It's weird enough that I thought I'd create a video just in case no one quite believed me (oh, and I've exited and entered Blender multiple times).

https://www.youtube.com/watch?v=ZzYETe_ViIQ

**Comment by ronh991** [comment]
There is no import module in the ASOBO exporter.  You are seeing the Khronos importer.  That does not work with MSFS files.

**Comment by ronh991** [comment]
OOps sorry I mis-spoke there is an importer. Just use the gltf 2.0 selection.

**Comment by Kelleytoons** [comment]
It works to get the Asobo Cessna 172 in?  I don't think so (I couldn't get it to work in 3.1.2).

What file are you loading in?

**Comment by ronh991** [comment]
Ah, seems the importer only works with files that have been saved with the ASOBO blender exporter.  Default aircraft are 3DS Max, so there is some slight mismatch in array sizes, according to the error I get.  Importing my own aircraft works.
