### ISSUE TITLE
Doesn't export linked objects.

### ISSUE THREAD

**Issue by rantonet** [AsoboStudio/glTF-Blender-IO-MSFS#186]
### Current Behavior

The plugin doesn't exports linked object. It's possible to add this features?

### Expected Behavior

The pulgin doesn't exports linked object. It's possible to add this features?

### Steps To Reproduce

Export

### Environment

```markdown
- OS:Windows 11
- Blender: 3.1.2
- glTF-Blender-IO-MSFS: 1.1.6
```

**Comment by y-khodja** [comment]
Hello, 

For this kind of issues you should ask here: https://github.com/KhronosGroup/glTF-Blender-IO. It concerns the official exporter of Blender and not the MSFS add-on. The MSFS add-on only adds extensions in the resulted glTF given by the official exporter to make it work in the sim. 

You should know that the MSFS exporter works with Blender 3.3 LTS only for now, we don't support other versions.

Thank you for your reports !
