### ISSUE TITLE
Long Compilation Time

### ISSUE THREAD

**Issue by lyonheart001** [AsoboStudio/glTF-Blender-IO-MSFS#187]
### Current Behavior

Hello Team Asobo, 

I am using a modified version of this SDK that works with Blender 3.4.  It works mainly with 3.3 but I find it works great with Blender 3.4 also.
When I compile models in the Blender 3.2 system with the older version SDK compiler, it compiles lightning fast.
When I compile with the new SDK in Blender 3.4 or 3.3, the compile times take quite a while, perhaps 3 to 5 minutes.  I believe this is the new Khronos update.

Its kind of a shame that the older Blender 3.2 SDK that was running fine but just couldnt also work in Blender 3.3/3.4.  Its so fast....  Time is radically important when building these models all day long, 6 days a week.  If you build 100 or 300 times a day, adding all those times up per build is 'expensive' time wise.  Could we 'possibly' make a version of the Blender2MSFS Exporter using the older one that compiled fast, and could export Blender 3.3 and 3.4 files/scenes?

Just a humble idea and request.

Bill
Lionheart Creations

### Expected Behavior

Slow build time, export time.
Build a model in Blender 3.1 or 3.2 and export.
Make a model that works in Blender 3.3 or 3.4, use the new exporter using the updated Khronos coding update and note that it now takes minutes instead of perhaps 4 seconds.  Radical time jump.

### Steps To Reproduce

Select parts
Run export glTF2 Blender2MSFS
Note export time; about 3 to 5 minutes, varying on exterior or interior models.

### Environment

```markdown
- OS:10
- Blender:3.4
- glTF-Blender-IO-MSFS:  Ron Experimental test version using newest Khronos build.
```

### Anything else?

please think about it.

**Comment by lyonheart001** [comment]
I wonder...   if only...  we could somehow adapt a version of the SDK exporter that runs excellent in 3.1 and 3.2 so that it will work with Blender 3.3 and 3.4... 

It works amazingly well...  Can that be done?  It works with the planes, getting them into MSFS.  We could keep it 'quiet' and silently fix it for the new Blender versions, and we would have our 'fast speed' exports...  And for those that want the new version with slower exporting and nice menu's for materials, we would have that as well... 

I for one need a faster export.  This is insane waiting MINUTES for a single export and have many to do at a time.  I am used to waiting 5 seconds for a plane to export.

**Comment by pepperoni505** [comment]
Hi Bill,

I'm sorry, but Asobo doesn't have control over the Khronos addon. It simply "extends" certain features during export and doesn't modify the Khronos code in any way.

I understand that you're asking if it's possible to use the 3.1/3.2 Khronos code with the current versions of Blender, but I'm afraid this is not possible. The majority of the code in the addon relies on recent updates to Blender and would not be compatible with older versions. Additionally, the Khronos exporter would most likely not work at all due to the reliance on newer features and deprecations in Blender.

I recommend submitting an issue on the Khronos repo. It might be helpful to include a minimal reproduction of the issue without the addon, as they don't provide support for third-party addons.

**Comment by lyonheart001** [comment]
> Hi Bill,
> 
> I'm sorry, but Asobo doesn't have control over the Khronos addon. It simply "extends" certain features during export and doesn't modify the Khronos code in any way.
> 
> I understand that you're asking if it's possible to use the 3.1/3.2 Khronos code with the current versions of Blender, but I'm afraid this is not possible. The majority of the code in the addon relies on recent updates to Blender and would not be compatible with older versions. Additionally, the Khronos exporter would most likely not work at all due to the reliance on newer features and deprecations in Blender.
> 
> I recommend submitting an issue on the Khronos repo. It might be helpful to include a minimal reproduction of the issue without the addon, as they don't provide support for third-party addons.

Many thanks, Pepperoni505.  That helps me to understand it better.  I just build planes and want so bad for the SDK to be as good as possible.

It is so odd that an update would bring down performance that much.  It was working so fine.

**Comment by tml1024** [comment]
Heh. Back when I was still working more actively on my add-on aircraft, export times of a couple of minutes was the norm. And I was fine with that. Then at some stage it started taking several dozens of minutes, or more. That's when I lost interest somewhat. (Also, vacation intervened and when returning from vacation I did not manage to re-kindle my interest... Maybe later this year, when retired.)

**Comment by lyonheart001** [comment]
> Just a marginal note. Back when I was still working more actively on my add-on aircraft, export times of a couple of minutes was the norm. And I was fine with that. Then at some stage it started taking several dozens of minutes, or more. That's when I lost interest somewhat. (Also, vacation intervened and when returning from vacation I did not manage to re-kindle my interest... Maybe later this year, when retired.)

I know what you mean...  Compile times really play havoc with work effort when they take a long time.  Very bad on productivity.

**Comment by lyonheart001** [comment]
> Hi Bill,
> 
> I'm sorry, but Asobo doesn't have control over the Khronos addon. It simply "extends" certain features during export and doesn't modify the Khronos code in any way.
> 
> I understand that you're asking if it's possible to use the 3.1/3.2 Khronos code with the current versions of Blender, but I'm afraid this is not possible. The majority of the code in the addon relies on recent updates to Blender and would not be compatible with older versions. Additionally, the Khronos exporter would most likely not work at all due to the reliance on newer features and deprecations in Blender.
> 
> I recommend submitting an issue on the Khronos repo. It might be helpful to include a minimal reproduction of the issue without the addon, as they don't provide support for third-party addons.

I tried to find a place to ask questions to Khronos about the new code taking so long to compile, couldnt even sign into a new account at their site for some reason.  But, I just noticed they have a GitHub account here, so I might try asking there.

**Comment by pepperoni505** [comment]
> > Hi Bill,
> 
> > 
> 
> > I'm sorry, but Asobo doesn't have control over the Khronos addon. It simply "extends" certain features during export and doesn't modify the Khronos code in any way.
> 
> > 
> 
> > I understand that you're asking if it's possible to use the 3.1/3.2 Khronos code with the current versions of Blender, but I'm afraid this is not possible. The majority of the code in the addon relies on recent updates to Blender and would not be compatible with older versions. Additionally, the Khronos exporter would most likely not work at all due to the reliance on newer features and deprecations in Blender.
> 
> > 
> 
> > I recommend submitting an issue on the Khronos repo. It might be helpful to include a minimal reproduction of the issue without the addon, as they don't provide support for third-party addons.
> 
> 
> 
> I tried to find a place to ask questions to Khronos about the new code taking so long to compile, couldnt even sign into a new account at their site for some reason.  But, I just noticed they have a GitHub account here, so I might try asking there.


Yes, please open an issue on their GitHub repository.

**Comment by lyonheart001** [comment]
It just occurred to me, this GitHub page is based on the SDK for Blender 3.1.  I am using a  test 'research and development' version of the SDK that runs 3.3 / 3.4.  So this probably should not have been posted here.  My humble apologies.
