### ISSUE TITLE
Just a question: Would it be better to base the work on the upstream Khronos glTF exporter-importer instead?

### ISSUE THREAD

**Issue by tml1024** [AsoboStudio/glTF-Blender-IO-MSFS#2]
I.e. https://github.com/KhronosGroup/glTF-Blender-IO . I wonder if that project would accept patches to export/import the MSFS flavour of glTF? Or is the MSFS glTF so different that having support for it in the official glTF 2.0 exporter-importer would lead to a horrible mess?

**Comment by lpierabella** [comment]
the MSFS exporter will expand the Official one, the user will not have to choose and reinstall an entire exporter
but only the plugin that "extend" the Khronos plugin 
as intended by Khronos group [here](https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/example-addons/example_gltf_extension)

**Comment by tml1024** [comment]
Ah, excellent! Thanks.
