### ISSUE TITLE
Texture path name - path of uri for texture file name

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#20]
The texture file name includes the path of the texture.  This should not be required.  possible issue with sim, but not in all cases.

**Comment by pepperoni505** [comment]
Can't recreate this. Can you send an example file?

**Comment by lpierabella** [comment]
should be [fixed](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/commit/1d8ef641567e97de1fabbaf9413c252a9c932cdf)
@ronh991 if you have other issues let me know

**Comment by ronh991** [comment]
Fixed - Jan 17 main branch update
