### ISSUE TITLE
Exporter 1.1.7 Pre-release with blender 3.3 - issues

### ISSUE THREAD

**Issue by tonypez** [AsoboStudio/glTF-Blender-IO-MSFS#202]
Hello there,

I am running tests with the new 1.1.7 exporter with relative Blender 3.3 and I encountered a couple issues so far that stop our workflow:

**1)  Export failure with 1.17**
The new exporter fails to export the main assembly file, I isolated the issue to a single "animation action".
If this "action" exists in blender (even if not exported), the export will fail
the action "2" in picture, is the problem, even if this is not selected to be exported, the exporter will fail.
Deleting this action solves the issue, but to spot what the issue was, I had to isolate this action among thousands of them.
![image](https://user-images.githubusercontent.com/93551041/214584245-dfaae56b-2e5a-45f0-924a-dd31c7191a18.png)

A blend file is attached here for this error
[Export_Fail_Action_issue.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10500083/Export_Fail_Action_issue.zip)

**2) Export times**

with **blender 3.1.2 and exporter 1.1.6**
Complex Interior export = 2 min
Complex Exterior export = 1 min

with **Blender 3.3 and exporter 1.1.7**
Complex Interior export = 55 min
Complex Exterior export = 6 min

the new exporter 1.1.7. exporting time makes the new exporter with blender 3.3, unusable for production.
3.1.2 has unfortunately missing features, therefore also not that useful in the meantime.

I can send the download link to a dummy file to prove the export times if needed (please send me an email to receive it):

There are more issues to come that wasn't able to isolate yet.

**Comment by ronh991** [comment]
Your second issue is is due to a core blender change to the way animation are done.  Blender has changed this from version 3.1 to 3.2+. You need to remain at Blender 3.1 for models developed in 3.1,  Only new projects started in blender 3.3 will export faster.

The exporter version 1.1.7 (1.3.0) will work with blender 3.1 and 3.2+

**Comment by ronh991** [comment]
For your first issue. was this file made in Blender 3.1 and you now try to export in 3.3?  I can reproduce the problem in 3.3.  I can export the blend file in Blender 3.1 with the 1.3.0 (1.1.7) version of the exporter in Blender 3.1

**Comment by ronh991** [comment]
May we use this blend file as an example to Khronos of the issue.  The errors seem to point directly to current khronos code not being compatible with blend files fromBlender 3.1

**Comment by tonypez** [comment]
> May we use this blend file as an example to Khronos of the issue. The errors seem to point directly to current khronos code not being compatible with blend files fromBlender 3.1

Hi Rohn,

to be honest, the whole assembly with animations was initially created with Blender 3.2 and exporter 1.1.6 until 80% of completion.
The export times were already long very with blender 3.2 and exporter 1.1.6

We then basically moved to from 3.2 to 3.1.2 because export times were under 1 min time instead of 1h, also other exporter limitations were not existing with 3.1.2.

The issue is we cannot finish the project with blender 3.1.2 because the Asobo exporter has 1.1.6 missing features when it comes to export animated skinned meshes (there is another thread where I explain these here: https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/issues/184)

We need blender 3.3 and exporter 1.1.7 to be as performant as Blender 3.1.2 and exporter 1.1.6

**Comment by ronh991** [comment]
We are attempting to figure out why the export times are so long.  We believe it's an issue with how Blender/Khronos have changed the animations internal to the blend file.  I am in the same boat, long exports.

The exporter ver 1.3.0 will work with Blender 3.1.2 - There is only a single shader node name change  for 3.3 and we check what version blender you are running.  Is it the ASOBO exporter missing the skinned mesh features or is it Khronos gltf core Blender missing that feature.

**Comment by ronh991** [comment]
May we use your blend file that you gave us above to show khronos/Blender group an issue with 3.1 to 3.4 file problems.

**Comment by tonypez** [comment]
> May we use your blend file that you gave us above to show khronos/Blender group an issue with 3.1 to 3.4 file problems.

The blend file above is the not the entire aircraft assembly, it's just a surface, the export times there are very fast.

I cannot share with them a confidential assembly, I would need to create a dummy of it.

**Comment by ronh991** [comment]
I just want to show them that blender 3.3.3 errors out while blender 3.1.2 works when exporting the gltf.  You blend file above exports with 3.1 but has an error with 3.3

**Comment by tonypez** [comment]
> I just want to show them that blender 3.3.3 errors out while blender 3.1.2 works when exporting the gltf. You blend file above exports with 3.1 but has an error with 3.3

Feel free to share it, I am actually almost done with creating a dummy from the main assembly, this file takes very long to export.
I would need the guy's email to send him the data privately, you can send that to me as a private msg

**Comment by ronh991** [comment]
I see you have left a post on the khronos thread, that's the guy we are trying to convince that there is an issue.

**Comment by tonypez** [comment]
Hi there, any improvement on the export timing?

Blender 3.3 is now officially supported by Asobo but to export a complete assembly takes more than 1hour...
the same file on blender 3.1 takes less than 2 minutes.

please support this.

**Comment by y-khodja** [comment]
Hello, 

Export timing is handled by io_scene_glTF official exporter, we only add extensions to some parts of the final gltf so that it is compatible with Microsoft Flight Simulator. For now we need to stick to Blender 3.3 because it's the last Long Term Support version they have.

Thank you for your report.
