### ISSUE TITLE
MSFS Standard Material doesn't show Vertex Colors and Ambient Occulusion

### ISSUE THREAD

**Issue by MrTheBull** [AsoboStudio/glTF-Blender-IO-MSFS#203]
### Current Behavior

![2023-01-25_21-20-55](https://user-images.githubusercontent.com/123577078/214618579-31fb5cbf-82b0-48af-b0e8-0f9c54b106f0.png)

Standard Material doesn't show meshes vertex colors, also it doesn't show AO from Occulution Map (Blue channel)

### Expected Behavior

![2023-01-25_21-22-03](https://user-images.githubusercontent.com/123577078/214619166-cb9a2109-e691-43d5-bc9a-4453a0712b35.png)

### Steps To Reproduce

![2023-01-25_21-32-51](https://user-images.githubusercontent.com/123577078/214621252-96a4f26d-a315-4658-b725-f497172fb9ea.png)

Can add a vertex color node and mix it with the Base Texture to fix the visibility in viewport

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS: 1.3.0
```

**Comment by ronh991** [comment]
You cannot modify the node structure of the shader nodes.  The exporter will not look at these nodes and export the data.

You can however set the vertex colors separately, but you must return the node structures to there expected values and configuration.

**Comment by MrTheBull** [comment]
> 

The game reads vertex colors and AO, the issue is that material preview in blender is not showing it as ingame. If somebody can fix this in material nodes would be great.

**Comment by ronh991** [comment]
Can you provide a blend file.  As the vertex colors work for me with icing and fingerprints scratches etc.  AO is in the texture channel.  So it should all be working.

**Comment by almazmannanov** [comment]
@ronh991 
I think what he means is that it would be nice to have Vertex color nodes connected in MSFS material nodes, so we will vertex color blended with textures in Blender viewport
In MSFS 2020 Vertex color working the same way, it does multiply itself with the texture (Both face and vertice method works)

Here is an example
Blender 3.1.2 (in blender 3.2+ Vertex color node was renamed into Color atribute)
https://drive.google.com/file/d/1y4nga4ckVMsTU3Ri89aymwbrtGl5QzPG/view?usp=share_link

**Comment by ronh991** [comment]
@almazmannanov I downloaded your file.  This works as you describe, however once you , say modify the color node the exporter will rebuild the node structure and remove the link from Multiply to the BSDF, as expected.

Just be aware if you change any shader nodes - they may or may not export correctly. And you will not see your model represented in the sim correctly.

Users - Just be aware of that fact.  The shader node structure should be returned to the original ASOBO schema.

![DA40CGDFQ_2023 01 26_10h20m06s_30](https://user-images.githubusercontent.com/19254353/214875275-12fca061-6817-49ce-94dd-9c6b14b24446.png)

![DA40CGDFQ_2023 01 26_10h20m37s_31](https://user-images.githubusercontent.com/19254353/214875309-8c8750bd-da0d-498b-a74b-17c278237753.png)


![DA40CGDFQ_2023 01 26_10h19m18s_29](https://user-images.githubusercontent.com/19254353/214875340-91c97f1e-2c84-44c4-a1b4-1764cbd4ded5.png)

**Comment by y-khodja** [comment]
Hello,

As @ronh991 said, you can't modify the shader nodes, you need to set you parameters in the material UI only otherwise it won't be exported.

The schema is made to be rendered closest (following the shaders in-game) to the render in-game.

Thank you for your report,
