### ISSUE TITLE
Texture File Effects still exported after deletion

### ISSUE THREAD

**Issue by connomar** [AsoboStudio/glTF-Blender-IO-MSFS#204]
### Current Behavior

Setting Textures such Combination, Occulsion ,Roughness,Metallic Normal etc and changing one's mind does not stop the exporter from writing the information to the gltf file.

i.e. Add a Normal Texture using Open and browse.  Decide it doesn't look right and choose to delete it using the X.

On Compiling, the Normal data is still recorded in the gltf file.

### Expected Behavior

When clicking X against any Texture, all references to that texture file should be removed.

### Steps To Reproduce

Windows 10
Blender 3.1
io_scene_gltf2_msfs 1.3.0

Create a new texture and add Base Color and Normal files.
Export
Delete the Normal File.
Export

Normal part of the texture remains.

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

### Anything else?

![image](https://user-images.githubusercontent.com/58862730/215374361-f2be5da9-f389-40f3-a2f5-829a38932ca3.png)

Note: The removal of the Normal File from the MSFS Material Parameters HAS NOT removed the normal effect from the Blender View.

**Comment by tjburni** [comment]
We had a similar issue a few days ago but havent found a solution yet.
Did you find some sort of workaround / fix?

**Comment by y-khodja** [comment]
Hello,

It has been fixed in the new release 1.3.1 !

Thank you for your report !
