### ISSUE TITLE
Extension MSFT_texture_dds not avalible on this add on version

### ISSUE THREAD

**Issue by twrixxed** [AsoboStudio/glTF-Blender-IO-MSFS#205]
### Current Behavior

![image](https://user-images.githubusercontent.com/84193409/216432642-2e7d7f83-251c-4821-98fc-2d460dbec3c1.png)

i watched this youtube tutorial on how to do this multiple times and have tried all versions of the add on and supported blender versions and it still wont work and i have no idea why

### Expected Behavior

1

### Steps To Reproduce

1

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

**Comment by mamu82** [comment]
The Asobo plugin has never supported importing already compiled .gltf files for copyright reasons


There are other plug-in you can use to accomplish the task

**Comment by y-khodja** [comment]
I confirm that the Asobo plugin has never supported importing already compiled .gltf files from MSFS to Blender! 

Thank you for your report !
