### ISSUE TITLE
Albedo textures displaying purple on some objects within blender viewport

### ISSUE THREAD

**Issue by Bazingabill** [AsoboStudio/glTF-Blender-IO-MSFS#208]
### Current Behavior

Textures have been applied correctly using the side menu under the materials tab in the 'Standard' property of MSFS materials. 

Although textures display purple on certain materials and objects. 

### Expected Behavior

Applying the textures to the material and assign the material to the already unwrapped object and it should display the texture without problems. 

### Steps To Reproduce

Standrd process of importing textures into a material. Its only with certain objects. (NOT ALL ARE BROKEN)

### Environment

```markdown
- OS:Windows 11
- Blender:Version 3.3.3
- glTF-Blender-IO-MSFS:Latest version
```

### Anything else?

Textures display correctly in material preview but in render mode they appear purple as shown in attachements.
![image](https://user-images.githubusercontent.com/42667480/217206054-a3ec99ed-0dc6-4b6c-a417-7dacca72d3f7.png)
![image](https://user-images.githubusercontent.com/42667480/217206148-c5879f9f-60ea-4bee-bdb9-4e323f254956.png)

**Comment by lyonheart001** [comment]
This happens to me, but Blender will sometimes create a second material, and that one cannot be found.  For instance, on this one, check your textures.  Blender might have renamed it 'hanger_edge_paint.001' adding in a .001 for some reason.  I have found duplicates up to .003 before.  I dont know what causes that.  I retype the name, taking off the .001 and that usually fixes the issue in MSFS.

**Comment by Bazingabill** [comment]
> 

Didn't fix it, its weird because i was able to make the textures work normally if i use a stock cube. But these objects don't work. Older versions of the addon also have this problem.

**Comment by ronh991** [comment]
Sorry for the late response.  Have you tried, purging orphan data, and also doing a missing files report.  Then do a find missing files.  This is a Blender option in the File menu.

File CleanUp, then select "Unused Data blocks", sometimes you also need to use "recursive Unused Data Blocks"

Then do a Window - Toggle SYstem Console - this opens a cmd window form Blender
Then do a File - External Data and select "Report  missing files"

Then do a File - External Data and Find missing files, navigationg to where the missing files are.

![DA40CGDFQ_2023 03 09_10h20m09s_04](https://user-images.githubusercontent.com/19254353/224069950-27dd842c-c6e9-4dfd-bbd5-e1edda6c114f.png)

![DA40CGDFQ_2023 03 09_10h20m51s_06](https://user-images.githubusercontent.com/19254353/224069978-aa372aba-3c29-4b63-9502-45b0cfa27f39.png)



![DA40CGDFQ_2023 03 09_10h20m23s_05](https://user-images.githubusercontent.com/19254353/224070020-dadaa597-df6e-48e0-b8c8-632d6d91bb8f.png)
