### ISSUE TITLE
Projected Mesh invisible when exported with official blender addon

### ISSUE THREAD

**Issue by vpilotdesigns** [AsoboStudio/glTF-Blender-IO-MSFS#209]
### Current Behavior

After applying all transforms to a plane, I export it but once in the sdk editor, when added to the project as a projectedmesh, it can be seen for about a second then it becomes invisible. If I open the model with modelconverterx it looks good.

### Expected Behavior

Visible at all times

### Steps To Reproduce

1. Export plane (projectedmesh)
2. Load in sdk project

### Environment

```markdown
- OS:Win 11
- Blender: 3.1.2
- glTF-Blender-IO-MSFS: 1.1.6
```

### Anything else?

When exported with the old non official blender addon the projected mesh works fine but I cannot get custom properties to be exported.

**Comment by y-khodja** [comment]
Hello,

We already gave you an answer on devsupport here : https://devsupport.flightsimulator.com/questions/14493/projected-mesh-invisible-when-exported-with-offici.html

Thank you for your feedback !

**Comment by vpilotdesigns** [comment]
I am still having the same issue. When I export it is not visible in the simulator. Even if I re create the materials
