### ISSUE TITLE
XML File not generated

### ISSUE THREAD

**Issue by ghosh9691** [AsoboStudio/glTF-Blender-IO-MSFS#210]
### Current Behavior

When any 3D object is exported using this plugin, it is creating the .bin and the .glTF files, but is not generating the .xml file that is required in order to bring the model into MSFS 2020.

### Expected Behavior

The .xml file should also be generated with export format glTF Separate.

### Steps To Reproduce

1. Open Blender 3.3.3 or below
2. Ensure Asobo exporter 1.3.0 is installed and activated along with default glTF exporter
3. Delete the camera and light, leaving only the default cube
4. Select the cube and click File/Export/glTF 2.0
5. Specify the folder and in format select "glTF Separate"
6. Specify a texture folder
7. Ensure "MSFS Extensions" is checked
8. Click button "Export glTF 2.0" to generate the export files

### Environment

```markdown
- OS: Windows 11
- Blender: 3.3.3
- glTF-Blender-IO-MSFS:1.3.0
```

### Anything else?

[cube.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10688344/cube.zip)

**Comment by y-khodja** [comment]
Hello,

To get the generated XML with your export, you need to export your model with the multiExporter here:
![image](https://user-images.githubusercontent.com/114567493/217772851-c5d58845-3d48-4164-bfe1-cc6a5ba39484.png)

You need to click on reload LODs the objects presents in you scene will be loaded : 
![image](https://user-images.githubusercontent.com/114567493/217773230-56a7ac1d-98b5-412b-8e9c-521d361ec62a.png)

After that tick the object you want to export by giving it a path and make sure to have generate XML ticked for it.

Thank you for your feedback !

**Comment by ghosh9691** [comment]
Thank you, @y-khodja! This works. It would be great if this could be documented somewhere as I have not found such documentation. Also, as a suggestion, it would be of great help if the exporter could create the folders if they did not already exist.
