### ISSUE TITLE
Export is not possible, always the same failure

### ISSUE THREAD

**Issue by heli3009** [AsoboStudio/glTF-Blender-IO-MSFS#211]
### Current Behavior

Hello everyone, I've already watched various videos but I can't export my Blender models. The same error keeps coming up and unfortunately I don't know what to do next.
Can someone help me? A screenshot is attached.
Or is there a German manual?

Thank you

![blender_failure](https://user-images.githubusercontent.com/125308872/218558552-68bb7ffa-b678-431e-9d66-799ef39b481e.png)

### Expected Behavior

It's a bit confusing at the moment, the old tool was easier.

### Steps To Reproduce

![blender_failure1](https://user-images.githubusercontent.com/125308872/218561582-c933a345-b685-474a-a3d1-5b264c018107.png)
![blender_failure2](https://user-images.githubusercontent.com/125308872/218561602-3a182dd5-7ca8-4d88-a576-32294f7e3ed0.png)
![blender_failure3](https://user-images.githubusercontent.com/125308872/218561619-e7e26a16-cfd4-4180-bd8f-0b84da32d9e5.png)

The only thing that works is the xml file.

### Environment

```markdown
- OS: Win11
- Blender: 3.1.0
- glTF-Blender-IO-MSFS: 1.3.0
```

**Comment by btronquo** [comment]
Hello.
You should read the readme file ;)
![image](https://user-images.githubusercontent.com/5455001/218575019-caa71b4b-29ee-4397-a1e0-0dcfdbd2f548.png)

**Comment by Wombii** [comment]
I am not the OP, but the sentence "compatible with Blender 3.3.x and below" implies their Blender 3.1.0 should work as that is below 3.3.x

**Comment by btronquo** [comment]
@Wombii 
You're right :) 
The readme will be updated

**Comment by ronh991** [comment]
It should be compatible with blender 3.1.x - How ever it looks like you removed the Khoronos core code - or it's not enabled.  Read the install procedure carefully in the read me.  You should have two gltf add-ons showing and.  Remove the legacy version you had before.
