### ISSUE TITLE
emissive strenght ineffective

### ISSUE THREAD

**Issue by mamu82** [AsoboStudio/glTF-Blender-IO-MSFS#213]
### Current Behavior

when using emission strenght, the plugin writes this in the gltf 
"extensions" : {
                "KHR_materials_emissive_strength" : {
                    "emissiveStrength" : 50
                },

the sim compiler doens't recognize the   "KHR_materials_emissive_strength", so ignores it, and render the object using
the emissive factor only

 "emissiveFactor" : [
                0.039222881373034056,
                1,
                0
            ],

### Expected Behavior

the compiler should recognize the   "KHR_materials_emissive_strength" or the final gltf values for 
emissiveFactor should be multiplied by the emissive strengh 

### Steps To Reproduce

blender 3.3.3.
add emissive material
set strenght
look at the gltf 
compile, look for yellow warning
see the result in the sim, no emissive strenght

### Environment

```markdown
- OS:win11
- Blender:3.3.3
- glTF-Blender-IO-MSFS:1.3.0
```

**Comment by 4evercool** [comment]
Confirm this.

**Comment by btronquo** [comment]
Hi, 

Did you use the "Emissive Scale" input ? 
No repro on my side :/

**Comment by 4evercool** [comment]
Yes, i tried to get the effect described here in the SDK docs:
![image](https://user-images.githubusercontent.com/1355660/223987672-783b530a-a2ee-49b9-95f3-dc1d31c2a871.png)

The emissive scale is set to 100 in the two lights near the roof in the screenshot below, but there is no bloom effect at all.
![image](https://user-images.githubusercontent.com/1355660/223988166-7a5d5e76-fda5-40b2-b7e7-6cbca60cffe2.png)

**Comment by mamu82** [comment]
> Hi,
> 
> Did you use the "Emissive Scale" input ? No repro on my side :/

> Hi, 
> 
> Did you use the "Emissive Scale" input ? 
> No repro on my side :/

Here is a video showing when using the emissive scale, the khr emissive property is written in the gltf 
That property is not recognised by the sim compiler, so the emissiveFactor won't be multiplied by the kronos emissionStrenght 

https://youtu.be/SHHp1BkzUR4?t=11m30s

**Comment by btronquo** [comment]
Reset your Emissive settings in the surface section and try now to only use **Emissive Color**, and **Emissive Scale** that are in the section "MSFS Material Params"  and tell me if it's better ;)

![image](https://user-images.githubusercontent.com/5455001/224279098-73c8081b-12bf-43a9-bc2f-4ffd429804d9.png)

![image](https://user-images.githubusercontent.com/5455001/224279169-5be0119e-be59-4447-98b4-e7ba1ba242bd.png)

**Comment by 4evercool** [comment]
Boris,

That's exactly my setup.
![image](https://user-images.githubusercontent.com/1355660/224280521-7e143186-eb18-4b06-a45f-46fbfd8db5f1.png)
![image](https://user-images.githubusercontent.com/1355660/224280572-3b555bc8-0621-4014-b22f-db1af266aef0.png)

With this setup this is what comes up in the gltf:
![image](https://user-images.githubusercontent.com/1355660/224280803-67ec049a-4a0d-4d73-b9be-81cabbbd6a5f.png)
![image](https://user-images.githubusercontent.com/1355660/224280905-d62048f4-c5ef-424e-bc42-24cbda210a0c.png)

The bloom effect only works when the emissiveFactor is set to 100, 100, 100. The sim compiler throws a warning at the "KHR_materials_emissive_strength" as unsupported extension.

**Comment by btronquo** [comment]
Ok I see, it's only when the emissive scale (strength) value is greater than 1.0
We will investigate :) 
Thanks

**Comment by 4evercool** [comment]
Yeah, right, I was just going to mention this :). The "KHR_materials_emissive_strength" comes up when the emissive scale is greater than 1.0 even it's just  a hundredth after the dot, like 1.03.

**Comment by btronquo** [comment]
I'm not sure we can fix this as it's hardcoded in the Khronos gltf addon we use to generate the GLTF  ^^

![image](https://user-images.githubusercontent.com/5455001/224285577-ffc5557e-c8b4-4ddf-91f8-c3d0b4e63864.png)

**Comment by mamu82** [comment]
The core of the problem is that the Asobo plugin is built on top of the Khronos one, and the gltf 2.0 specs prevents the emissionFactor to be over 1.0 (the previous implementation 1.1.6. tried to multiply the emissionFactor values per the emissiveStrenght but the Khronos was clamping them)

I guess the only viable solution is via the compiler, when detecting emissionStrenght, do the math behind the scene and aplly to the emissionFactor

**Comment by romandesign** [comment]
It must be possible to brute-force rewrite a line in .glTF code after the export, right? Why not do it after the fact, after the file is exported? Inelegant, but it would be a way to override the Khronos plugin. This is a serious issue, it makes us go and modify every LOD glTF file for any model that is re-exported, and that's a lot of work, and easy to forget and kill the glow that was working fine...
FWIW The bloom effect works below 100 too, anything from about 20-30 produces some effect, sometimes it's better than a full-scale 100. Still, it's impossible to do unless we manually edit all .glTF LOD files every time...

**Comment by romandesign** [comment]
Well, for now I had to do a workaround. It's crude, and I used ChatGPT because I'm a designer, not a coder. Still took a while. anyway, the idea is that I normally wouldn't use Emission Factor that's non-0 and non-1. So I kind of trick it by setting it to the following:

# Emissive Scale = 0.5 = R Bloom
# Emissive Scale = 0.6 = G Bloom
# Emissive Scale = 0.7 = B Bloom
# Emissive Scale = 0.8 = W Bloom

And then run script once, after the export. No need to manually search all LODs and remember what I need to change. Just in case someone can use it, here it is:

`import bpy
import os
import json

def find_emissive_factor(data):
    if "materials" in data:
        for material in data["materials"]:
            if "emissiveFactor" in material:
                return material["emissiveFactor"]
    return None

def map_emissive_factor(old_emissive_factor):
    old_emissive_str = ", ".join(str(x) for x in old_emissive_factor)

    if old_emissive_str == "0.25, 0.25, 0.25":
        return [30, 1, 1]
    elif old_emissive_str == "0.30000001192092896, 0.30000001192092896, 0.30000001192092896":
        return [0, 30, 0]
    elif old_emissive_str == "0.3499999940395355, 0.3499999940395355, 0.3499999940395355":
        return [0, 0, 30]
    elif old_emissive_str == "0.4000000059604645, 0.4000000059604645, 0.4000000059604645":
        return [20, 20, 20]
    else:
        # Check for other representations of the values
        if old_emissive_factor == [0.25, 0.25, 0.25]:
            return [30, 1, 1]
        elif old_emissive_factor == [0.30000001192092896, 0.30000001192092896, 0.30000001192092896]:
            return [0, 30, 0]
        elif old_emissive_factor == [0.3499999940395355, 0.3499999940395355, 0.3499999940395355]:
            return [0, 0, 30]
        elif old_emissive_factor == [0.4000000059604645, 0.4000000059604645, 0.44000000059604645]:
            return [20, 20, 20]
        else:
            return old_emissive_factor

def change_emissive_factor(filepath, new_emissive_factor):
    with open(filepath, 'r') as file:
        data = json.load(file)

    old_emissive_factor = find_emissive_factor(data)
    if old_emissive_factor:
        new_emissive_factor = map_emissive_factor(old_emissive_factor)

        # Update emissiveFactor wherever it's found in materials
        if "materials" in data:
            for material in data["materials"]:
                if "emissiveFactor" in material:
                    material["emissiveFactor"] = new_emissive_factor

        # Also update emissiveFactor wherever it's found in nodes
        if "nodes" in data:
            for node in data["nodes"]:
                if "emissiveFactor" in node:
                    node["emissiveFactor"] = new_emissive_factor

        with open(filepath, 'w') as file:
            json.dump(data, file, indent=4)

        print(f"Changed emissive factor for {filepath}")
    else:
        print(f"Old emissive factor not found in {filepath}. Skipping...")

def main():
    # Set the path where the .glTF files are located
    gltf_folder_path = "D:/MSFS Projects/Vancouver Island/MSFS/PackageSources/VIPackModelLib/VIPackModel/"
# Emissive Scale = 0.5 = R Bloom
# Emissive Scale = 0.6 = G Bloom
# Emissive Scale = 0.7 = B Bloom
# Emissive Scale = 0.8 = W Bloom

    for collection in bpy.data.collections:
        if "LOD" in collection.name:
            gltf_filename = collection.name + ".glTF"
            gltf_filepath = os.path.join(gltf_folder_path, gltf_filename)

            if os.path.exists(gltf_filepath):
                change_emissive_factor(gltf_filepath, [30, 0, 0])
            else:
                print(f"File not found: {gltf_filename}")

if __name__ == "__main__":
    main()
`

**Comment by romandesign** [comment]
Here is the script
