### ISSUE TITLE
Cylinder Collider does not export the correct length.

### ISSUE THREAD

**Issue by realModsWanted** [AsoboStudio/glTF-Blender-IO-MSFS#216]
### Current Behavior

I know, you had a lot of issues with colliders and made some fantastic fixes. But unfortunately there is still one bug with the cylinder collider. As the title says, it does not export in the correct length. It looks to me like it export just the half length.

See this picture
![cylinder-collision-wrong-length](https://user-images.githubusercontent.com/98099299/221376819-102c9066-9791-4b27-b236-c1da5ad208cf.jpg)

In the lower picture is the Blender 3.3.0 LTS viewport.
In the upper is the same part in MSFS.

### Expected Behavior

Export cylinder collider in the correct length.

### Steps To Reproduce

1. Create object
2. Create cylinder collider
3. Export
4. Have a look in MSFS

### Environment

```markdown
- OS: Windows 10 Pro x64
- Blender: 3.3.0 LTS
- glTF-Blender-IO-MSFS: 1.3 (updated 14. Feb. 2023 @ 11:27AM )
```

### Anything else?

Thanks for your work guys!

**Comment by ronh991** [comment]
Check that the scale is set to 1.0 for the cylinder object - sometimes if the scale is not set to 1,0 the exported mesh will show scaled back by the value in the blend file.

to scale an object select the object and then press CTRL+A and select scale.  note the scale on the pic is 3.427

before scale

![DA40_CGDFQ_2023 06 26_9h29m40s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/051fe6f1-1ae6-4a09-8100-19b97a61c1a1)


after scale applied

![DA40_CGDFQ_2023 06 26_9h30m3s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/fc7f2191-c254-41b1-81fc-dedbfcc87ce4)

**Comment by y-khodja** [comment]
Hello,

We can't seem to repro this issue, is it still a valid one ?

Thank you for your report
