### ISSUE TITLE
Emissive scale description is incorrect in msfs_material_props.py

### ISSUE THREAD

**Issue by 4evercool** [AsoboStudio/glTF-Blender-IO-MSFS#218]
### Current Behavior

Emissive scale description in msfs_material_props.py reads:

description="The roughness of the material. A value of 1.0 means the material is completely rough. A value of 0.0 means the material is completely smooth. This value is linear. If a metallicRoughnessTexture is specified, this value is multiplied with the roughness texel values.",

### Expected Behavior

Description to conform to what the emissive scale actually does.

### Steps To Reproduce

Open msfs_material_props.py in an editor and find the bpy.types.Material.msfs_emissive_scale = bpy.props.FloatProperty

### Environment

```markdown
- OS: Win 11
- Blender: 3.3.4
- glTF-Blender-IO-MSFS: 1.3.0
```

**Comment by y-khodja** [comment]
Fixed in :https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/pull/219

Thank you for your report !
