### ISSUE TITLE
Windshield icing, dirt (ASOBO_Detail_map) not exporting

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#22]
![DA40CGDFQ_January 19, 2022_11h51m30s](https://user-images.githubusercontent.com/19254353/150179451-a007eb81-900d-40ff-a103-417378a8cc8a.png)

missing ASOBO_detail_map in windshield texture slots. (main branch test)
commit 547df62a9fbeafae9282814e5c7c1e9beeeca629

**Comment by pepperoni505** [comment]
This should also be fixed in #11
