### ISSUE TITLE
impossible to export the ambient lights

### ISSUE THREAD

**Issue by Cristian9898** [AsoboStudio/glTF-Blender-IO-MSFS#221]
### Current Behavior

I try to export ambient lights and at the same time flashing lights from a control tower, but it does not export it.
![Captura de pantalla 2023-03-28 203517](https://user-images.githubusercontent.com/127247653/228335209-063b0b50-1075-4cfc-a7e2-28c3b0954390.png)
![Captura de pantalla 2023-03-28 203553](https://user-images.githubusercontent.com/127247653/228335214-862f665d-0cf9-485f-98d4-adab1a4f11dd.png)

### Expected Behavior

when I export it and implement it in the msfs2020, nothing lights up and the flashing animation does not work.

### Steps To Reproduce

create a cube, then create a points light, upload the emission to the light, select all and then export.
![Captura de pantalla 2023-03-28 204003](https://user-images.githubusercontent.com/127247653/228336145-868aa840-d3a8-4fd0-975c-4ea7a48b707c.png)

### Environment

```markdown
- OS:Windows 11
- Blender:3.3.5 LTS
- glTF-Blender-IO-MSFS: 1.3.0
```

**Comment by vpilotdesigns** [comment]
![image](https://user-images.githubusercontent.com/71776971/228395417-b4431bed-ea82-41b5-8f80-2329fe21a39a.png)
Is Punctual Lights checked?

**Comment by Cristian9898** [comment]
I always check and have it like this
![Captura de pantalla 2023-03-29 030023](https://user-images.githubusercontent.com/127247653/228399730-d419e743-825f-4d5e-858f-b6061eda82de.png)

**Comment by y-khodja** [comment]
Hello,

I have test to export lights with both 3.3.2 and 3.3.5 versions of blender but i d'ont see any error in the exporter and the lights are exported in the gltf 
![image](https://user-images.githubusercontent.com/114567493/232416230-89d4c624-4db7-480e-b9dd-cbae4959a59a.png)

Can you send us your blend file to check what could be the reason for that ?
Thank you !
