### ISSUE TITLE
No Object in Editor Visible from export. (Not Even a Cube) 

### ISSUE THREAD

**Issue by Keastey** [AsoboStudio/glTF-Blender-IO-MSFS#223]
### Current Behavior

1.)(Blender 3.1) Basic cube, Base Colour; Red. Collection rename to 'Cube"
(MulitExport glTF 2.0) Export Settings: 
![image](https://user-images.githubusercontent.com/131501071/233754442-1e7f20dc-b806-4108-b7be-f58e6a25892f.png)
![image](https://user-images.githubusercontent.com/131501071/233754471-6baf2dd4-b130-4a9e-b3c6-6a98b2c530db.png)

2.)Export to ModelLib Folder /Cube

3.)In SDK Editor:

Object has name 'Cube' Node is placeable. But Object is Invisible. 

![image](https://user-images.githubusercontent.com/131501071/233754420-5a4ff7b1-1bc8-40e8-a999-175c8565ae25.png)

I've Tried in Blender Version 2.8, 2.9, 3.3.5, 3.5 Same results.
I've Tried with an imported .obj
I've Tried re-texturing the .obj with 1024x1024 albedo & Normal.

Same results.

I've Tried checking Tangents
I've Tried Checking all Geometry Settings.

### Expected Behavior

Object to be visible in-game 

### Steps To Reproduce

n/a

### Environment

```markdown
- OS: x64 windows 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: 3.1.0
```

**Comment by mamu82** [comment]
Maybe some plugin conflicts?

Try with a clean, portable standalone Blender installation


This one for the plugin version 1.1.6
https://download.blender.org/release/Blender3.1/blender-3.1.2-windows-x64.zip 

This one for plugin versions 1.3.0 (current one)
https://download.blender.org/release/Blender3.3/blender-3.3.3-windows-x64.zip

**Comment by Keastey** [comment]
Just tried Blender 3.3.3 w/ 1.3.3 plugin. Same results.
Export Settings:
![image](https://user-images.githubusercontent.com/131501071/234126612-05eb1ad6-1986-47a2-84ab-9c474d58e84c.png)
![image](https://user-images.githubusercontent.com/131501071/234126674-63cfd790-87f3-4e13-b507-d923e96e932f.png)

am I installing the plugin correctly? edit/Preferences/install/io_scene_gltf2_msfs.zip 
![image](https://user-images.githubusercontent.com/131501071/234127061-416a3547-52ba-4840-82af-c3145b85917f.png)

**Comment by y-khodja** [comment]
Hello,

You can't use the gltf exporter MSFS without the legacy one in blender, you need to have it check to export proprely. As for your problem, i think you are changing your shader from the BSDF directly, you need to use the MSFS Material Params down here to get your values exported. Changing from the Surface panel won't work.
![image](https://user-images.githubusercontent.com/114567493/234275225-f410c7fe-7553-4c8c-a645-1ec662daf990.png)

Thank you for your report!

**Comment by ronh991** [comment]
The first pic of the 1.3 exporter in the edit preferences looks ok, and I see the gltf base Khronos enabled also.  However It is NOT enabled in the pic you show with the errors.

The errors also make reference to a Downloads folder.  So I believe your install has an issue.  Please follow the instructions on how to install.

**Comment by Keastey** [comment]
> Hello,
> 
> You can't use the gltf exporter MSFS without the legacy one in blender, you need to have it check to export proprely. As for your problem, i think you are changing your shader from the BSDF directly, you need to use the MSFS Material Params down here to get your values exported. Changing from the Surface panel won't work. ![image](https://user-images.githubusercontent.com/114567493/234275225-f410c7fe-7553-4c8c-a645-1ec662daf990.png)
> 
> Thank you for your report!

Hi,

What is legacy 1? Here's a screenshot of what legacy i have enabled.
![Blender Legacy](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/26c1507b-4978-4686-929c-b365dc15a204)
I Changed the Base colour within MSFS Material parameters. And it Works! Thanks.

**Comment by Keastey** [comment]
> The first pic of the 1.3 exporter in the edit preferences looks ok, and I see the gltf base Khronos enabled also. However It is NOT enabled in the pic you show with the errors.
> 
> The errors also make reference to a Downloads folder. So I believe your install has an issue. Please follow the instructions on how to install.

**Hi. Noted. And Enabled. What's the difference between the Two? Why are there Two?** 

![gltf](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/2509c9c7-7c2b-4cc0-b83d-896b22278a87)

Now It's Visible within the SDK editor! Thanks

![MSFS Screen Capture Cube](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/b0146802-45a1-435c-bd12-d583a14dd89c)

**Comment by Keastey** [comment]
**Could Someone check my export settings**

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/fa3fb097-d104-42e8-a7ad-804ababff584)
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/de50c46c-23e6-4e1a-83ca-15534899ca47)

**Comment by Keastey** [comment]
**Export Error's**

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/8582996f-0934-464a-9137-b0678bb5e0d7)

**Comment by Keastey** [comment]
**Could someone please help me with this error i have no idea what it means**
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/56ea6a18-0b36-4a89-a15b-7b2b39ad8d08)

**Comment by y-khodja** [comment]
Hello, 

There is a new release of the MSFS exporter 1.3.1, you should install it and test to export your model with this one.

Thank you for your report !
