### ISSUE TITLE
msfs blender export problem

### ISSUE THREAD

**Issue by Faize34** [AsoboStudio/glTF-Blender-IO-MSFS#224]
Hi,
I have Blender version 3.3.1, I have lexport version 1.3.0.
I read the description well, on the other hand I don't have in msfs material migrate data. Also in file/export, I don't have the msfs export line. I do have the MSFS export tab in the toolbar, but I can't find in setting which file to export my project to. I think I am doing something wrong. Can you help me?
Best regards

**Comment by y-khodja** [comment]
Hello, 

I am not sure to understand your issue. If you have downloaded the msfs exporter you need to enabled it in Blender with Edit->Preferences ->Add-ons then you install the zip dowloaded from the release. The instruction are explained here: https://github.com/AsoboStudio/glTF-Blender-IO-MSFS

I hope it helps !

**Comment by Faize34** [comment]
Thank you for the answer, I did download as indicated in the instructions, but as I told you, I do not have in file/export the display of gtf2 msfs, so I cannot configure my export to MSFS. If you want a screenshot?

**Comment by y-khodja** [comment]
You can either use the multiexporter here using either the objects panel to export blender objects in different Gltfs or the presets one to group objects in collections:
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/a0988249-60c6-4b6c-9301-b0471dfcecbc)

Or activate the MSFS Extensions in the export gltf parameter panel here:
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/2b59079c-4e1a-4a1e-96c1-a90dfe16d65a)

Hope this can help !

**Comment by Keastey** [comment]
@Faize34 Your best to use Blender Version 3.3.5 w/ Asobo 1.3.0

**Comment by LGBudd** [comment]
I also have what I believe to be this same problem, but I've installed Blender 3.3.6 and the Microsoft Flight Simulator (MSFS) glTF Extension 1.3.0. The extension is checked as enabled, yet it is unavailable when File Import or File Export is selected.

I've tried removing the Extension and reinstalling (several times) with variations explained [here](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS). This includes using the "Install" with a zip (io_scene_gltf2_msfs.zip) and a manual install to C:\Users\Asus\AppData\Roaming\Blender Foundation\Blend\3.3\scripts\addons\io_scene_gltf2_msfs_init_.py

I've also closed Blender and re-opened it after doing each install. It's made no difference.

I can install and use the SketchUp Importer as well as other extensions, with no problems.

**Comment by y-khodja** [comment]
Have you tried to export a cube with the Microsoft Flight Simulator material set to it?

**Comment by LGBudd** [comment]
I tried importing with File--> Import --> glTF 2.0 and see, under Importer Extensions, that MSFS Extensions Enabled is checked. Is this the same import capability as if there was another entry under File --> Import which names the MSFS Extension directly?

I also see when attempting to File --> Export --> glTF 2.0 under Operator Presets, Exporter Extensions, MSFS Extensions is Enabled (by default) and Enable ASOBO_unique_ID is unchecked. Again, is this the same as having the ability to select the MSFS Extension directly from the Export submenu? For models, should Enable ASOBO_unique_ID be checked?

Thank you.

**Comment by y-khodja** [comment]
Hello,

I'm sorry, i'm not sure to get everything. The plugin adds a check to enable or disable export dedicated to Microsoft Flight Simulator. If you enabled it you get a glTF dedicated to the Sim and if you disable it you will get a glTF dedicated to any other softwares or needs. 

You can refer to the documentation here for more informations: https://docs.flightsimulator.com/html/Asset_Creation/Blender_Plugin/The_Blender_Plugin.htm?rhhlterm=blender&rhsearch=blender  

I hope this helps,
Thank you for your report

**Comment by LGBudd** [comment]
Thank you very much, @y-khodja! Although I've read much of the SDK documentation, I hadn't seen the Blender Plugin page. That should help greatly.
