### ISSUE TITLE
empty_object in the simulator

### ISSUE THREAD

**Issue by Dobro8** [AsoboStudio/glTF-Blender-IO-MSFS#227]
Hello ,

Blender 3.36
Export : 1.31 ,1.30

for some reason, all my exports give me an "empty" object (small Cube) in the simulator

I have no error when importing in the simulator console

I have no error when exporting with Blender 

![bug_affichage_3d_objet](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/52855142/8839935b-2dd0-4c92-9839-9ffbbf538a51)
![my_config](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/52855142/b73568d2-19d5-43ce-84dc-95454598a325)

**Comment by Dobro8** [comment]
the Blend 
[hangar_rond.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/11529363/hangar_rond.zip)

**Comment by Dobro8** [comment]
sorry, the same Blend, with packaged textures 
[hangar_rond.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/11529389/hangar_rond.zip)

**Comment by ronh991** [comment]
> the Blend, with packaged textures [hangar_rond.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/11529389/hangar_rond.zip)
> 
> PS:why not put the addon in Blender 3.5.1?

Blender 3.4 and higher have breaking changes in the shader nodes.  Need to resolve that.

**Comment by ronh991** [comment]
> the Blend, with packaged textures [hangar_rond.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/11529389/hangar_rond.zip)
> 
> PS:why not put the addon in Blender 3.5.1?

Maybe your scenery project is not set up - Your hanger works for me. Use SimpleScenery as a start.

![DA40CGDFQ_2023 05 22_16h59m39s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/ba0a0ce9-8e64-45df-8e1b-6596d5f2732c)

**Comment by Dobro8** [comment]
that's what it was! Thanks  :o)

**Comment by Dobro8** [comment]
I started from a copy of the "SimpleScenery_example" files

so from scratch, I was able to put back some of my old objects, (because the addon seemed to work last week)
so the old objects converted, still work very well 
but all those that I make since 3 days, do not work any more ! 

I made a little video to show you what's going on:

https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/52855142/5b50de2e-b151-4a96-9ee7-c716bdef088c

**Comment by Dobro8** [comment]
don't worry, if I'm the only one reporting this problem
but if it happens to others, then there is a residual bug somewhere

**Comment by y-khodja** [comment]
Hello !

I have tested with your scene with Blender 3.3.6 and the latest version of the exporter, on my side it works. Do you have your textures exported in the right folder ? Or maybe clean et rebuild your package ? 

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/1ff0ead3-ec83-476e-84b0-d3d74d89f4cb)

**Comment by Dobro8** [comment]
Thank you, I ended up completely redoing my shed
on Blender, because the mesh was not so good ...LOL

I also completely redid my textures from Zero
(I used Stable Diffusion ... :o) ) 
but nothing works ! 

I erase everything each time, I start from scratch, I even tried several versions of the export addon, and even several versions of the SDK ! 

the Blender addon is well set (Texture+mesh) and the Asobo box is checked

the "Multi Export" addon is well set too ///

I tested the normal export, and also to export by the Blender export, it doesn't change anything for me 

something strange is happening ...
yesterday and the day before yesterday I had an object that didn't work either ...
then surprisingly, it passes today ... I didn't change anything in this object ... (I'm going to go crazy LOL )  

in the meantime, my hangar has a much better mesh (with Quads) 
I still don't have a solution, but I'll find it eventually, I'm not giving up !! ha ha ha ! 
Thanks for your tests, there is surely an incompatibility, somewhere, I will find ;o)
I'll come and tell you ... Thank you very much again 

Translated with www.DeepL.com/Translator (free version)

**Comment by Dobro8** [comment]
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/52855142/8957a8ae-39a4-4fa0-9882-6fa637751627)

**Comment by Dobro8** [comment]
ronh991 you are right, it seems, that I have to triangulate the object before the export
if I believe the first Warning 
..
The second Warning, is a bit more obscure for me 
I use indeed 2 images (a diffuse and a Normal Map image)



the console Blender :
***********************************************************************************************************************************
09:02:42 | INFO: Draco mesh compression is available, use library at D:\Blender\stable\blender-3.3.6+lts.948f8298b982\3.3\python\lib\site-packages\extern_draco.dll
09:02:43 | INFO: Starting glTF 2.0 export
09:02:43 | INFO: Extracting primitive: Cylinder
09:02:43 | WARNING: Could not calculate tangents. Please try to triangulate the mesh first.
09:02:43 | INFO: Primitives created: 2
09:02:43 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
09:02:43 | INFO: Finished glTF 2.0 export in 0.01529693603515625 s
**********************************************************************************************************************************

**Comment by Dobro8** [comment]
here is the Zip archive of the result that
[modelLib.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/11553030/modelLib.zip)
 the Genere addon
you will see, maybe the error 
it is extracted from my file /ModelLib

**Comment by y-khodja** [comment]
Hello,

Just tested with yout modelib in the SimpleScenerySample. It still works. 

Try to follow these steps:
1. Open your project when you are in the main menu. 
2. Clean and build your package from there.
3. Launch your freeflight.
4. Then open the Scenery Editor and try to load your model.

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/383a1697-576c-4dfc-be11-dcb59c5ce74c)

**Comment by Dobro8** [comment]
no sorry, still not working ..

**Comment by Dobro8** [comment]
[Uploading Dobro_LFKL.zip…]()
all source Project

**Comment by Dobro8** [comment]
and the ALL Source Project:
[Dobro_LFKL.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/11554829/Dobro_LFKL.zip)

**Comment by Dobro8** [comment]
This is it!! I found the problem 

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/52855142/98f98cf9-1163-48bf-8a6d-242181bbd1b9)

**Comment by Dobro8** [comment]
it's because of the following FlightSimulator addons :
https://flightsim.to/file/2605/we-love-vfr-region-1
https://flightsim.to/file/16674/we-love-vfr-region-2
https://flightsim.to/file/52211/we-love-vfr-region-3

it's because of the following FlightSimulator addons :

they add a lot of objects in the world (VFR)
I guess it creates a conflict ...

if you disable these addons, then export/import works fine !

**Comment by Dobro8** [comment]
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/52855142/68112751-7b0b-4227-9af4-44624f9c4aa7)

**Comment by y-khodja** [comment]
Great ! Your welcome !
