### ISSUE TITLE
Can't export XML file

### ISSUE THREAD

**Issue by RodoxVR** [AsoboStudio/glTF-Blender-IO-MSFS#234]
### Current Behavior

I don't have the option to create an xml file, i only have the glTF and bin files (using FlightSim Blender glTF 2.0 Importer and Exporter from Asobo) and the addon is correctly installed on blender 3.3.3 LTS, what am i missing?

In fact i don't have the MSFS tab at all, only the MSFS extension tab at the bottom when exporting from blender.

### Expected Behavior

only exports glTF and bin file, no XML option available

### Steps To Reproduce

1. install this addon on blender 3.3.3 LTS
2. go to file >> export >> as glTF file, 
3. click on separate glTF and bin file + textures
4. No MSFS tab with XML or GUID file creation is there.

### Environment

```markdown
- OS: windows 11
- Blender: 3.3.3 LTS or 3.3.5 both tested.
- glTF-Blender-IO-MSFS: 1.3.0
```

### Anything else?
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/108250924/cd785c3a-00d8-4c5f-a2a9-f7498bd65213)

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/108250924/2035cd93-d5c1-4baf-bf63-325bda970047)

_No response_

**Comment by mamu82** [comment]
To have the xml you shouldn't use file/export
Instead
use the muliexport window (the same you are showing with the settings) , in the objects tab select Generate XML, select the export folder and click the export button, you're done

As an advice, start using msfs standard materials rather than images applied to the base color

**Comment by RodoxVR** [comment]
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/108250924/8d039342-4435-45f4-ab69-3994b71e50b1)

In the multi export menu under object like u mentioned i also don't see the Generate XML.

**Comment by RodoxVR** [comment]
Cool, i see it now. It's there when i select grouped by collections, Thanks this helps alot !
