### ISSUE TITLE
Object not showing in editor

### ISSUE THREAD

**Issue by RodoxVR** [AsoboStudio/glTF-Blender-IO-MSFS#235]
### Current Behavior

Trying to export a bridge to MSFS that i created in blender but not showing up in the editor from MSFS,

Can anyone help me with that, ive linked the project and the blend file at the bottom.

Thanks.

### Expected Behavior

does not show under objects in editor

### Steps To Reproduce

nvt

### Environment

```markdown
- OS: windows 11
- Blender: 3.3.5 LTS
- glTF-Blender-IO-MSFS: 1.3.0
```

### Anything else?

Here's my project and blend file:
https://mega.nz/folder/2aRUiQRS#IQB4FG6jrnAHDFsWGndr5g

**Comment by RodoxVR** [comment]
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/108250924/58cf9207-e5ab-4bcb-8482-11d8ac701475)

Only this when i run it with fpackagetool

**Comment by y-khodja** [comment]
Can you send me your package ? with your model exported.
