### ISSUE TITLE
Should I be able to use 1.3.1 (2023/6/8 download) to export compilable models?

### ISSUE THREAD

**Issue by PhysicsTeacher1** [AsoboStudio/glTF-Blender-IO-MSFS#237]
I use Blender 3.3.6 and exporter 1.3.0 for scenery with great success!  I had documented a behavior related to scenes, which I use to organize my work.  But, I decided to see first what improvements had been added to 1.3.1.  I liked the Limit To addition of Active Scene; that would solve my problem.  I am impressed by the clean-up of the material node tree and other things.  Thank you for your hard work!  I can export with 1.3.1 but I cannot compile unless I set Materials to Placeholder or None.  The only change I see in the .gltf is the addition of a line in extensions with ASOBO_material_detail_map.
A simple yes/no will suffice;  you can even tell me to take two aspirin and lie down until the feeling goes away.
Again, thank you!

**Comment by y-khodja** [comment]
Hello,

The 1.3.1 version is still in development, you will be able to use it when it's released 😄 ! So for now i recomand using 1.3.0 version.
