### ISSUE TITLE
Please change release version in the plugin 

### ISSUE THREAD

**Issue by mamu82** [AsoboStudio/glTF-Blender-IO-MSFS#247]
### Current Behavior
*** in the zip release ***
Init.py still 1.3.0

### Expected Behavior

Shoul be 1.3.1

### Steps To Reproduce
download the zip, 
code on github is ok
.

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

### Anything else?

.

**Comment by fweinrebe** [comment]
And also, the script indicated Blender 3.1 whereas the documentation shows it's only compatible with Blender 3.3 LTS

bl_info = {
    "name": "Microsoft Flight Simulator glTF Extension",
    "author": "Luca Pierabella, Wing42, pepperoni505, ronh991, tml1024, and others",
    "description": "This toolkit prepares your 3D assets to be used for Microsoft Flight Simulator",
    **"blender": (3, 1, 0),
    "version": (1,3,0),**
    "location": "File > Import-Export",
    "category": "Import-Export",
    "tracker_url": "https://github.com/AsoboStudio/glTF-Blender-IO-MSFS"
}


" The version 1.3.x is only compatible with Blender 3.3.x LTS. Other versions are not supported."

**Comment by y-khodja** [comment]
Hello,

It has been fixed !

Thank you for your report !
