### ISSUE TITLE
Problem installing addon v1.3.1 (but it's called 1.3.0 in the addon itself)

### ISSUE THREAD

**Issue by Flyingscool** [AsoboStudio/glTF-Blender-IO-MSFS#249]
### Current Behavior

I installed Blender 3.6
I followed the directions to install the addon
I got an error and it didn't activate

### Expected Behavior

I expected the addon to activate

### Steps To Reproduce

In Windows 10, install Blender 3.6
Copy the _io_scene_gltf2_msfs_ directory from the v1.3.1 zip file to C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons
Start Blender
Go to Edit/Preferences/addons/Community tab
search for gltf
only the _io_scene_gltf2_msfs_ came up
select the box next to it to activate it

I got an error ModuleNotFoundErro: No Module named 'io_scene_gltf2.blender.exp.gltf2_blender_gather_texture_info'

Restarted blender
Now a second addon showed up searching for gltf - _io_scene_gltf2_, and it is activated.
I still can't activate _io_scene_gltf2_msfs_

Quit and restart blender
Now the other addon is listed under Official and _not_ Community
Import-Export: glTF 2.0 format
The msfs addon still won't activate

### Environment

```markdown
- OS:Windows 10
- Blender: 3.6
- glTF-Blender-IO-MSFS: 1.3.1

Interestingly, it says it's 1.3.0 in Blender, but I downloaded the 1.3.1 version this evening on 7/2/2023
```

### Anything else?

![ScreenShot-230703-010610001](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/62926106/4d806731-c5d4-485a-b1fa-54f8264088a4)
![ScreenShot-230703-011829001](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/62926106/df9b225b-e6a3-4f05-bd5b-3c1ec10b5f26)

**Comment by vbazillio** [comment]
The version 1.3.x seems to be compatible with Blender 3.3.x and not 3.6.x ;)

**Comment by Flyingscool** [comment]
Ok, I'll try that.

**Comment by Flyingscool** [comment]
Worked in 3.3.8 msi install.

**Comment by Flyingscool** [comment]
I guess I missed that extra 3, I thought it said it worked with 3.x, didn't realize it works with 3.3.x
