### ISSUE TITLE
Not able to enable addon in blender

### ISSUE THREAD

**Issue by meeeeruri** [AsoboStudio/glTF-Blender-IO-MSFS#256]
### Current Behavior

issue
ModuleNotFoundError: No module named 'io_scene_gltf2.blender.exp.gltf2_blender_gather_texture_info'

### Expected Behavior

Enable addon

### Steps To Reproduce

blender 3.6, in blender preferences, after install, at stage to checkbox for enable the addon.

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

**Comment by JustinGlen75** [comment]
I seem to be having the same issue. Everytime I try to enable the plugin I get Traceback messages -- tried restarting Blender after install, still a no-go. I have the other, 3rd party GLTF importer installed? These shouldn't conflict right? I'm using Blender 3.6 on Windows 10.

**Comment by mamu82** [comment]
Blender 3.6 is not compatible with this addon:

The version 1.3.x is only compatible with Blender 3.3.x LTS. Other versions are not supported.
