### ISSUE TITLE
Not possible to create emission glow

### ISSUE THREAD

**Issue by romandesign** [AsoboStudio/glTF-Blender-IO-MSFS#258]
### Current Behavior

Increasing "Emissive Scale" above 1 should create a glow/halo effect in MSFS via increasing "emissive factor" in glTF file above 1: there is a very useful quirk/feature of MSFS - if in the following code the "emissiveFactor" goes beyond 1, for example especially if any of the RGB values is around 30 or higher, there is a nice "glow" around the area. This is how people make collision lights and other glowing lights on buildings. It's extremely useful, but it seems that it's not possible to do with the exporter. We have to manually modify the .gtLF file for each LOD after each export, because it gets overwritten, which is very tedious.

This is how the material works for a nice collision light - it has an image texture which is made brighter and has a mild halo / glow around it in MSFS:

`"emissiveFactor" : [
                30,
                0,
                0
            ],`

But if I just use the exporter, it looks like any emissive color only goes to 0.5 (so white is 0.5,0.5,0.5), and if "Emissive Scale" parameter is set above 1 (3, for example) it goes to 1 (so white is 1,1,1), and at some point the new parameter appears:

            `"extensions" : {
                "KHR_materials_emissive_strength" : {
                    "emissiveStrength" : 1.5
                },`

It looks brighter in Blender, but it's ignored by MSFS and has no glow/halo effect. I wento to the mas of 100 in Blender and there is no difference. Only going to 30+ inside the glTF file has that effect. We need this effect in the Blender/exporter somehow, even if it is not what the colour is supposed to be represented as. This is what makes lights realistic and similar to other lights in MSFS. It would be nice to have a way - maybe an "Emissive Scale" actually working towards adding those values instead of creating an extension values that do not work in MSFS?

### Expected Behavior

Increasing "Emissive Scale" above 1 should create a glow/halo effect in MSFS via increasing "emissive factor" in glTF file above 1.

### Steps To Reproduce

increase "Emissive Scale" to any value up to 100 - no glow/halo in MSFS. Edit glTF file for "emissiveFactor" to 30,0,0 for a 30x red value, and there is a nice glow/halo around the material.

### Environment

```markdown
- OS: Win11
- Blender: 3.3.8LTS
- glTF-Blender-IO-MSFS: 1.3.1
```

**Comment by mamu82** [comment]
bug still open :)
https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/issues/213
