### ISSUE TITLE
Problem producing the .xml file when using Preset tab

### ISSUE THREAD

**Issue by JohnVulcan** [AsoboStudio/glTF-Blender-IO-MSFS#268]
Using Blender 3.3.4 with glTF-Blender-IO-MSFS 1.3.1 and SDK 0.21.1.0

I am using the Preset tab, as I’d made extensive use of Blender collections in my model. Running glTF-Blender-IO-MSFS  with the Preset tab produced both the .gltf and .bin files which were created correctly - checked these in the 3D Viewer. Thinking that this might be correct, I tried adding them to my SDK project, but without the .xml file SDK simply ignored them.
So removed the collections in Blender and tried again using the Object tab, but this created another problem (as the PBR textures didn’t cover the whole model) however this did produce an .xml file which importantly contained a valid GUID. So edited this .xml file and added it to the original .gltf and .bin files (produced using the Preset tab) and exported all three into my MSFS project. This worked! The project built without producing errors, also able to create a new package, again without producing errors.
So it appears that the .xml file is required, but I cannot see how to produce one when using the Preset tab. What have I missed out or not understood please?

**Comment by JohnVulcan** [comment]
Many thanks for your very prompt reply Wombii, at least this confirms I'd done the right thing and I'll know what to do in the future.

**Comment by y-khodja** [comment]
Hello,

I confirm what @Wombii said, preset tab does not produce xml files. It's used to produce SimObjects, you will need to create an xml on your own. https://docs.flightsimulator.com/html/Content_Configuration/Models/Model_Definitions.htm this link to the SDK documentation should help you with that.

Thank you for your report !
