### ISSUE TITLE
Can't enable addon in Blender 3.6

### ISSUE THREAD

**Issue by axelhd** [AsoboStudio/glTF-Blender-IO-MSFS#270]
### Current Behavior

After installing the addon via the Blender Preferences tab I get an error when I try to enable it.

OCR

Traceback (most recent call last):
File Files\Blender Foundation\BIender line 333i in enable
mod = _ import (rnodule_name)
File msfsl_init epyll, line 216$ in «module>
from .io.rnsfs_import import Import
File line 18$ in •crnodule>
from .msfs material import MSFSMateriaI
File line 16/ in
from hlender„exp.gltf2 blender_gather_texture_info import
ModuleNotFoundError: No module named lio blender_gather texture infol

OCR END

![_gltf2blendermsfs](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/99671483/b4b7c949-e88e-4163-844e-33bf84805695)

### Expected Behavior

I expect it to enable the addon and tick the box

### Steps To Reproduce

Install blender 3.6
Open Edit -> Preferences -> Addons
Click Install and navigate to the 'io_scene_gltf2_msfs.zip' file.
Try to tick the box to enable the addon

### Environment

```markdown
- OS: Windows 10
- Blender: 3.6
- glTF-Blender-IO-MSFS: 0.4
```

**Comment by ronh991** [comment]
As per the read me file - it only works with 3.3.

There are breaking changes in Blender 3.6 as you see.
