### ISSUE TITLE
Extension MSFT_texture_dds is not available on this addon version

### ISSUE THREAD

**Issue by JUL3S1468** [AsoboStudio/glTF-Blender-IO-MSFS#272]
### Current Behavior

when i try to load a msfs gltf model i get this error:Extension MSFT_texture_dds is not available on this addon version
(i'm using blender 3.6)

### Expected Behavior

i would like to laod a msfs model

### Steps To Reproduce

a

### Environment

```markdown
- OS:window 11 familly
- Blender:3.6
- glTF-Blender-IO-MSFS:last version
```

**Comment by btronquo** [comment]
Try again with the correct blender version (3.1.x)

**Comment by y-khodja** [comment]
Hello,

This is mentioned in the readme :
⚠️ This plugin cannot import glTF files that have been built into a Microsoft Flight Simulator package through the Sim's Package Builder.
And:
⚠️ The version 1.3.x is only compatible with Blender 3.3.x LTS. Other versions are not supported.

Thank you for your report
