### ISSUE TITLE
Blender install issue

### ISSUE THREAD

**Issue by Antriv-art** [AsoboStudio/glTF-Blender-IO-MSFS#273]
![Blender Preferences 30_08_2023 2_11_00 PM](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/72861168/bdf14966-7aeb-42dc-b895-c824af28de08)
I am trying to install this plug in, but i keep getting this error, does anyone have any ideas on how to resolve it?

**Comment by vbazillio** [comment]
Because you’re on Blender 3.6? And this plugin works only on 3.3.x LTS ?
