### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by Alexbj26** [AsoboStudio/glTF-Blender-IO-MSFS#274]
### Current Behavior

![Screenshot 2023-09-04 140105](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/144029187/184a48ab-a615-4000-a3a0-cbe885344fd9)

Following error occurs after trying to activate add-on in Blender. Have tried the two most recent releases 1.3.1 and 1.3.0.

### Expected Behavior

Expected the add-on to activate after installing. Tried installing through Blender and by pasting into the addon file.

### Steps To Reproduce

1. download zip file.
2. Open blender, edit, preferences,  install add-on, select downloaded zip file, click to activate installed add-on.
3. Error occurs and traceback appears.

### Environment

```markdown
- OS:Windows 10
- Blender: 3.6.2
- glTF-Blender-IO-MSFS:1.3.1
```

**Comment by mamu82** [comment]
You need to use blender 3.3.x as per readme,
The error is showing you are trying to install on 3.6

**Comment by vapouryh** [comment]
Similar issue occurs when using blender version 3.3.10. As seen below.
![blender_issue](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/69804041/f489c1f8-50c7-491d-ad91-830f55d33a32)

**Comment by vapouryh** [comment]
Latest supported version seems to be blender 3.3.9 LTS.
