### ISSUE TITLE
Option to export missing

### ISSUE THREAD

**Issue by NicoVisagie** [AsoboStudio/glTF-Blender-IO-MSFS#276]
### Current Behavior

I have used the previous exporter named Blender2MSFS V0.41.4 with Blender V3.0. It had an option called “extended glTF for MSFS” under the export menu with which to export your scene with.

### Expected Behavior

I am using this addon with Blender V3.3 and I was expecting find a similar option under the export menu to export my scenes with, but there is nothing, The plugin is loaded. It shows in Blender when you open a blend file and it is physically installed; I have checked! It is only the export option that seems to be missing in the menu.

### Steps To Reproduce

Click FILE, go down to EXPORT. No export option, except for the one included in Blender by default. The last-mentioned export works, but it does not export in LOD's and it also does not ask or generate an XML file for you as the previous addon did.

### Environment

```markdown
- OS: Windows 11 (Build 22621)
- Blender: V3.3
- glTF-Blender-IO-MSFS: 1.3.2
```

**Comment by Losco-Nosciuto** [comment]
Because that's simply not how you export. With the new plugin you DON'T go through the export menu, but you press N, switch to the msgs plugin Tab and you can configure anything right there.

**Comment by ronh991** [comment]
Please note - you have two options to export - You can use the export gltf from the File Export menu or you can use the multi-exporter. (N key side menu in the 3D viewer) The multi-exporter requires that you have set up your blend file with collections and other settings.

If you used the legacy exporter and are use to File Export MSFS gltf then Just use File Export and gltf.  The core khronos code is now part of the MSFS exporter.

**Comment by NicoVisagie** [comment]
Thanks for the help, guys. I really appreciate it. I installed the plugin straight from the MSFS SDK; no docs are included in the folder. If you guys are the developers, then it will be a real good idea to have Microsoft include a read me for noobs like me, even if it is just a link to the docs! I am pretty sure there are more of us out there. :-)
