### ISSUE TITLE
Can't get the add-on to install on Blender

### ISSUE THREAD

**Issue by tillwylerson** [AsoboStudio/glTF-Blender-IO-MSFS#277]
### Current Behavior

Hi, I'm hoping this is the right place for this, apologies if not.

I have downloaded the latest release of the io_scene_gltf2_msfs.zip, unzipped and moved it to %appdata%\Blender Foundation\Blender\3.6\scripts\addons, but when I go to preferences in Blender and try to activate the addon by the check mark, I keep getting an error message. I have uninstalled and reinstalled Blender and removed/redownloaded the gltf file and it hasn't helped. I have attached a screenshot of the error message below.
![Screenshot (93)](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/146979321/ee5404fe-a480-4af9-b1d7-cfe5cee2d37d)

### Expected Behavior

I expected the add-on to install with no issue (only filling out this part as it is necessary)

### Steps To Reproduce

It's every time I try to install it.

### Environment

```markdown
- OS: Windows 10
- Blender: 3.6
- glTF-Blender-IO-MSFS: 1.3.2
```

**Comment by Wombii** [comment]
It's not compatible with Blender 3.6.
Per readme: "The version 1.3.x is only compatible with Blender 3.3.x LTS. Other versions are not supported."

**Comment by tillwylerson** [comment]
Well that explains that. Thank you.
