### ISSUE TITLE
add-on not showing up in file>import or export menu

### ISSUE THREAD

**Issue by tillwylerson** [AsoboStudio/glTF-Blender-IO-MSFS#278]
### Current Behavior

Hi, I posted earlier today with an issue I was having and was helped very quickly, but I've come up against another problem now. My original problem was that I was on Blender 3.6 so couldn't install the add-on. I have now got Blender 3.3 LTS and I could install the add-on fine and activate it in Blender preferences. I saved my preferences, quit and reopened blender but the addon isn't appearing in the import or export menu. I've put screenshots below.
![Screenshot (95)](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/146979321/912ff4e4-e216-4688-b105-d29035a8b96a)
![Screenshot (94)](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/146979321/6077c90d-3049-42ad-9b23-ca7dd3b649e7)

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

```markdown
- OS: Windows 10
- Blender: 3.3 LTS
- glTF-Blender-IO-MSFS: 1.3.2
```

**Comment by PhysicsTeacher1** [comment]
The new exporter has been really improved.  It is no longer in the Export
menu; it's a tab at the right of the 3D Viewport called Multiexport glTF
2.0.  You will find all of the original functionality there.

**Comment by tillwylerson** [comment]
Ah okay yes I've found that tab now, but I can only see options for exporting, how can I import the models into blender from the msfs files?

**Comment by tillwylerson** [comment]
Thank you for the help.
