### ISSUE TITLE
The Blender addon defaults to a base color value of 0.8

### ISSUE THREAD

**Issue by rhumbaflappy** [AsoboStudio/glTF-Blender-IO-MSFS#279]
### Current Behavior

The Blender addon defaults to a base color value of 0.8  This should be 1.0 or our models will display in MSFS at 80% of their actual brightness. Additionally, the max of the Base Color is set as 1.0. This might be better set as 2.0, allowing a material to become displayed at increased brightness. This lets a developer brighten a too-dark asset without resorting to altering his textures in a paint program.

### Expected Behavior

The current behavior is as it is programmed, but the value is just wrong.

### Steps To Reproduce

Create a cube, activate the MSFS material settings as Standard, and the base Color is set to 0.8 value.

### Environment

```markdown
- OS:
- Blender:
- glTF-Blender-IO-MSFS:
```

### Anything else?

Included is a corrected msfs_material_props.py

[msfs_material_props.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/12821250/msfs_material_props.zip)

**Comment by PhysicsTeacher1** [comment]
I've always altered the limits and defaults in my ow copy with each new release to suit my own work needs.  For example, this latest release, I believe, set the default Metallic to 1.00.  Perhaps this setup of defaults and ranges might be incorporated into the AddOn dropdown for this exporter.  Of course, someone at Asobo would need to put absolute outside values on the limit settings based on what the simulator can reasonably handle.
Just a suggestion.  Thanks for bringing this up, though.

**Comment by y-khodja** [comment]
Hello, 

This will be fixed in the next update.

Thank you for your report !
