### ISSUE TITLE
Exporter doesn't take collections in account

### ISSUE THREAD

**Issue by Losco-Nosciuto** [AsoboStudio/glTF-Blender-IO-MSFS#281]
### Current Behavior

Hello everyone. Today, after working all day on Blender, the exporter started acting weird. 

It started regardless of the settings used, in exporting all collections in all the LODs at once.

Means, I got a model with split Interiors / Exteriors collections. When I export (settings screenshots reported below) and whenever I export I get all LODS same in filesize. After inspecting them, all the single LODS contain ALL the models of ALL the LODS of ALL collections.

So instead of having: 

*Interiors_LOD00 - Containing the first LOD of the interiors model
*Interiors_LOD01 - Containing the second LOD of the interiors model
etc etc

what I get is

*Interiors_LOD00 - Containing ALL the LODS of ALL the models, both interiors and exteriors
*Interiors_LOD01 - Containing ALL the LODS of ALL the models, both interiors and exteriors
*Exteriors_LOD00 - Containing ALL the LODS of ALL the models, both interiors and exteriors
*Exteriors_LOD01 - Containing ALL the LODS of ALL the models, both interiors and exteriors

etc. etc.

Here you can see that the filesize for both interiors AND exteriors are the same, and a huge amount compared to the filesize it should be:

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/35420766/2ba28534-0ca2-40f3-a96d-c91357b78625)
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/35420766/d0a88174-3d7e-45de-953f-6aa9aa7ac763)

While the previous export (still made it today, so this has changed all of a sudden, and happens in ALL my models) is correct like shown below:

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/35420766/798b8972-7009-42bc-80f0-61a2a505be53)

Now, it can be seen by inspecting the GLTF that the model contains all LODS of all models:

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/35420766/05828d73-267f-4ac0-a179-cfb1911408f1)

This is supposed to be LOD00 of the INTERIORS, while it has LOD00, 01, 02 and 03 of both interiors and exteriors of the same model.

These are the settings used to export by now:
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/35420766/739139a2-37df-4df2-b239-c0847db49dd1)
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/35420766/6bcce183-2cca-454b-99e8-db4c79ea916c)

Any help would be appreciated since so far, exporting is not working at all

### Expected Behavior

LOD collections should export separately each one containing only the models based on each collection, resulting in smaller, and different file sizes. Each output file should contain ONLY the models of the related LOD as per indicated in the collections above.

### Steps To Reproduce

1- Create an LOD based model
2- export that model

### Environment

```markdown
- OS: Windows 11
- Blender: 3.3 LTS
- glTF-Blender-IO-MSFS: 1.3.2
```

### Anything else?

https://drive.google.com/drive/folders/18jy_SH5h4k4bVMJ12R5kA7whzcIaSbR0?usp=sharing

.blend file is zipped and saved here

**Comment by ronh991** [comment]
What version worked before?

**Comment by Losco-Nosciuto** [comment]
> What version worked before?

The same version I used. 

I didn't close blender, I didn't restart my PC, I didn't change any settings. It just happened out of the blue while I was updating materials made wit 1.3.0 to the 1.3.2 shader tree.

All of a suddenm is literally all of a sudden :D

**Comment by Losco-Nosciuto** [comment]
> What version worked before?

Just took a look at another model, and it exported fine even after changing the material (I just re-opened the Drop-down of the MSFS material properties and set it on Standard again so the shader tree gets re-generated)

Seems like it's something to do with that model itself. The weird thing about this is that, again it happened out of the blue, no reasons why. I didn't close Blender or change any export setting. I just pressed export and had this result, and woah, this is annoying 🤣

**Comment by Losco-Nosciuto** [comment]
Alright I might have found the issue @ronh991 @y-khodja . You have set the "selected objects" checkbox ON by default and non-editable. Seems like for some reason it went off.

Now, I guess the way the exporter works is by automating collections to be selected by LOD name and exported one collection at a time. Having that checkbox OFF might be the issue, causing the Exporter to gather LODs informations based on the collection names, but exporting all meshes in all LODs because of the missing property checkbox. Now, whatever caused that checkbox to disappear, I don't know but this is most likely to explain the weird behavior. Unfortunately I ain't at the PC now, it's something I noticed by comparing my settings screenshot with the ones from other issue reports down in the list. And seems coherent to what the issue is causing.

If you could investigate and give me (us actually, since someone might find this useful in the future) any way to re-enable that checkbox, it would be awesome 😎

Personally I tried reinstalling both blender and the add-on but seems like settings are stored in the .bled file. Also loading project with no UI had no effect on the export so I reckon the checkbox was still disabled.

Hope this narrows the issue down to a decent stage


Regards

Chris

**Comment by Losco-Nosciuto** [comment]
Regarding the above mentioned thing, I recall opening by mistake the Built-in Blender GLTF exporter, but closed it right after without changing a thing. 

Might this be that the two are linked somehow and, maybe the checkbox was disabled by defaulr in the built-in exporter, disabling as a consequence the one in the Adobo Proprietary Multi-Exporter?

**Comment by ronh991** [comment]
Ah this find is interesting.  I always use the separate regular exporter.  I was able to reproduce your issue with your blend file.  Thank-you for reporting this.

**Comment by ronh991** [comment]
The export menu is the other way to export your model. in individual LODs. That export selection has the core Khronos code merged with the ASOBO msfs code (as does the multi exporter) , so can us that way of exporting, as I mentioned above.

**Comment by Losco-Nosciuto** [comment]
> The export menu is the other way to export your model. in individual LODs. That export selection has the core Khronos code merged with the ASOBO msfs code (as does the multi exporter) , so can us that way of exporting, as I mentioned above.

Means that, enabling the checkbox in the standard GLTF exporter might revert back the "selected objects" checkbox status in the Multi-Exporter? Sorry for asking but can't be at the PC for 7 more hours :D

**Comment by ronh991** [comment]
I'm not sure I have to check the code.  I don't work for ASOBO, so maybe @y-khodja can answer and produce a fix.

**Comment by ronh991** [comment]
You can modify the Selected Objects setting and force the check box to be checked using the Blender data API screen.
https://youtu.be/juu0eTIrfzw

**Comment by Losco-Nosciuto** [comment]
> You can modify the Selected Objects setting and force the check box to be checked using the Blender data API screen. https://youtu.be/juu0eTIrfzw

Awesome! Thanks for the workaround, I'ma try that as soon as I get home! It was such a wired issue I really couldn't wrap my head around it 🤣 thanks again Rohn, you made my day ;)

**Comment by lonesparrow67** [comment]
Thanks for the workaround, I also started getting this issue after I downloaded the 1.3.1 (and still seeing in in 13.2) and have been racking my brain trying to figure out how to fix it, lol....
