### ISSUE TITLE
Can Not Install v1.3.2 In Blender 3.3.X

### ISSUE THREAD

**Issue by fleahead** [AsoboStudio/glTF-Blender-IO-MSFS#282]
### Current Behavior

1)  Downloaded "io_scene_gltf2_msfs.zip" from the github/Releases/1.3.2/Assets page
2)  Opened Blender 3.3.7 (I also tried in v3.3.2)
3)  Opened Edit/Preferences/Addons/Install
4)  Chose file " io_scene_gltf2_msfs.zip" in my Downloads folder
5)  Searched for "msfs" in the installed addons list with nothing found
6)  The addon is not on the list
7)  I looked in location   C:\Users\****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons
8)  Folder "io_scene_gltf2_msfs" is located there and everything is intact inside.

*  I also attempted to install the addon using the alternate method by manually placing the folder and I have the exact same results.
 
*  I have been working on this for 3 days now. I tried rebooting the PC after doing the install. I've tried several Blender 3.3.x versions but none work. I'm sure I must be making a stupid mistake somewhere, but this ain't rocket science.

### Expected Behavior

1)  Downloaded "io_scene_gltf2_msfs.zip" from the github/Releases/1.3.2/Assets page
2)  Opened Blender 3.3.7 (I also tried in v3.3.2)
3)  Opened Edit/Preferences/Addons/Install
4)  Chose file " io_scene_gltf2_msfs.zip" in my Downloads folder
5)  After instal complete enable the addon

### Steps To Reproduce

Same as Current behavior

### Environment

```markdown
- OS: Win 11
- Blender: 3.3.7
- glTF-Blender-IO-MSFS: 1.3.2
```

### Anything else?

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/17817307/29e1613c-b13c-46d9-b480-0966f102003e)

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/17817307/3a94aaa7-8b8d-43eb-bcfa-f646e2e1d076)

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/17817307/f21078bd-b0ec-4b26-8218-0c32b7b8378b)

**Comment by gvogele** [comment]
Hi, you have to push the install in Blender Preferences, then choose zip File and install.
Dont forget to activate after.

**Comment by fleahead** [comment]
That's exactly what my step #3 shows I did. Continue reading the steps.

**Comment by fleahead** [comment]
Solved:
This issue was caused by my PCMatic AintiVirus not being disabled
