### ISSUE TITLE
Any plans to upgrade this to work with Blender 4.0?

### ISSUE THREAD

**Issue by tml1024** [AsoboStudio/glTF-Blender-IO-MSFS#286]
### Current Behavior

The title says it all, really. Sure, 3.3 is just one year old. But Blender is advancing steadily and the upcoming 4.0 will have lots of interesting new functionality, some of which could be useful also for people making MSFS add-ons.

So, is upgrading this plugin to work with Blender 4.0 on the roadmap? I have no idea how hard it would/will be, but in case it is relatively straightforward, would you accept pull requests to implement it? (No promises that I would personally be able to do it, though.)

### Expected Behavior

The plugin should ideally work with the upcoming Blender 4.0.

### Steps To Reproduce

Not relevant.

### Environment

```markdown
Not relevant.
```

**Comment by ronh991** [comment]
Blender 4.0 has numerous changes to the shader node and specifically the BSDF node input linking names that are not compatible with the current exporter.  Also Khronos has modified the core code, in that any material that uses Detail BaseColor textures, like windshield break the sim build.  Seems the Khronos code looks at ALL the basecolor texture nodes and places them into the regular baseColor section of the PBRMetallicRoughness section in the gltf. While the ASOBO exporter places them in the correct extension section.

 I have asked Khorons a question regarding this and any help in finding a hook to use to block Kronos from doing this would be appreciated.
 
 https://github.com/KhronosGroup/glTF-Blender-IO/issues/2034

**Comment by y-khodja** [comment]
Hello, 

Unfortunatly for now we can upgrade it to LTS versions of Blender but not to not supported versions. Next update would be Blender 3.6.x not 4.0.

Thank you for your report.

**Comment by tml1024** [comment]
Also that is a step in the right direction, thanks!

**Comment by SirComand** [comment]
and how long it will take to be in version 4.0
