### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by mathurpc** [AsoboStudio/glTF-Blender-IO-MSFS#292]
### Current Behavior

I get a long error message when exporting to MSFS2020. I am using Windows 10 Home v22H2, Blender v3.3.5 and Exporter v1.3.2. My .blend file is attached
[Blender Export Error.docx](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/13690979/Blender.Export.Error.docx)

### Expected Behavior

The export function worked fine with Exporter v1.2. I switched to v1.35 because the lights were not getting exported. I saw a YouTube video by MyPhysicalWorld where it is mentioned that v1.3 of Exporter fixes this problem.

### Steps To Reproduce

Add Blender lights to an object and export.

### Environment

```markdown
- OS:Windows 10 Home v22H2
- Blender:v3.3.5
- glTF-Blender-IO-MSFS:Exporter v1.3.2
```

**Comment by mathurpc** [comment]
My .blend file is attached.
[Hangar.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/13690993/Hangar.zip)

**Comment by ronh991** [comment]
uncheck custom properties - does not work.  pickle error is the key here.

**Comment by y-khodja** [comment]
Hello,

Custom propreties can be checked when yoy export glTF not dedicated to MSFS. Otherwise it won't work. 

Thank you for your report

**Comment by mathurpc** [comment]
I am surprised that you decided to close this without finding out if the problem was solved.I had received the following message which I could not understand - “pickle error is the key” what does that mean?On Dec 18, 2023, at 9:51 AM, y-khodja ***@***.***> wrote:﻿
Closed #292 as completed.

**Comment by y-khodja** [comment]
Hello,

These errors are generated by the official Khronos Blender glTF exporter, if you have an issue with the official glTF Blender exporter you can open an issue here : https://github.com/KhronosGroup/glTF-Blender-IO . On the other hand your issue with the MSFS glTF Exporter is that you have custom properties checked and this option should not be checked if you want your export to work proprely with the MSFS add-on.

**Comment by mathurpc** [comment]
Thanks for the explanation. And yes, your suggestion worked - thanks for your help.On Dec 19, 2023, at 2:40 AM, y-khodja ***@***.***> wrote:﻿
Hello,
These errors are generated by the official Khronos Blender glTF exporter, if you have an issue with the official glTF Blender exporter you can open an issue here : https://github.com/KhronosGroup/glTF-Blender-IO . On the other hand your issue with the MSFS glTF Exporter is that you have custom properties checked and this option should not be checked if you want your export to work proprely with the MSFS add-on.
