### ISSUE TITLE
Problem with Asobo Exporter when using textures.

### ISSUE THREAD

**Issue by parpocel** [AsoboStudio/glTF-Blender-IO-MSFS#295]
Hi. From a couple of days I try to export a single cuboid with simple jpg texture (just base color). Unfortunatelly when I want to export this object I got error as showed below. Does anyone can sort out what is that about? I tried to follow one YT toutorials, when selected "Custom properties" caused an error, but in my case it's not working, just showing shorter Error log which you can see in the image. Any sort of hints would be appriciated.
![Screenshot 2023-12-24 114741](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/85748727/bab3cd23-9307-4a08-b08a-d4b18afe83e8)
![Screenshot 2023-12-24 114730](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/85748727/4efe7799-5ba9-43a3-b6f2-c96e5257fcbb)
![Screenshot 2023-12-24 114650](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/85748727/4240f239-ee4a-4dcd-b461-7d0d135359a3)

**Comment by ronh991** [comment]
you have three dots in textures folder textbox

use

../texture

**Comment by parpocel** [comment]
Nice. Thank you very much. Now works perfect :)
