### ISSUE TITLE
Help Wanted! What does this mean?

### ISSUE THREAD

**Issue by Keastey** [AsoboStudio/glTF-Blender-IO-MSFS#300]
![Screenshot (3)](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/131501071/8929b3ff-a95a-4e72-b61d-8abc37eb0090)

This model exported fine just 3 seconds ago. Showed in-game. I exported and it created 3 files 3Dobject, .bin, .xml. And I've done exactly  the same thing Opened saved blender file from working save. (only 3 s ago) highlights all objects under collection. Hit export. Error! and then only an xml. in the desired folder. Am I corrupting the GUID by exporting again?

**Comment by ronh991** [comment]
Looks like you are using Blender 2.91 - Not sure what version of the exporter you are using.  I know you said it worked before, but bea\cause you are working on your project things get changed that Blender 2.91 does not like.

**Comment by y-khodja** [comment]
Hello,

Can you send us your blend file ?

Thank you for your report !

**Comment by y-khodja** [comment]
Hello !

The plugin work only with Blender 3.3LTS and 3.6LTS, we can't guarantee the proper functioning of the plugin with other versions of Blender.

Thank you for your report
