### ISSUE TITLE
Blender 3.3.15 LTS with AsoboStudio / glTF-Blender-IO-MSFS Release 1.3.2

### ISSUE THREAD

**Issue by NikiLZDEV** [AsoboStudio/glTF-Blender-IO-MSFS#304]
### Current Behavior

Installed the IO-MSFS 1.3.2 through BLENDER.
Tried to open Cessna172SP_LOD00.gltf  
Trying to make my first MSFS 2020 livery for me ... and 
Extension MSFT_texture_dds is not available on this addon version ?!?

### Expected Behavior

To open a 3D model of C172.

### Steps To Reproduce

![Screenshot 2024-02-04 155153](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/158827466/0bc5280f-5b21-441a-9443-27f5542b0f46)
![Screenshot 2024-02-04 155153](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/158827466/2c0521c0-fb6a-4479-ba3f-0b740b20a990)

### Environment

```markdown
- OS:Windows 11
- Blender:3.3.15 LTS
- glTF-Blender-IO-MSFS:
```

**Comment by Wombii** [comment]
The asobo exporter does not support importing gltfs. It's for exporting only.

**Comment by NikiLZDEV** [comment]
> The asobo exporter does not support importing gltfs. It's for exporting only.

Seen youtube tutorials they use the MSFS 2020 models? How do they do that in Blender? What is my course of action? 
I will change the sim if I am not able to custumize my livery.
Tried Photoshop - same result ...

**Comment by y-khodja** [comment]
Hello,

The official MSFS importer/exporter does not support importing gltf already built in MSFS as mentionned in the readmea here:
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/bd8a659c-e1a6-4a68-adb9-ebf546015f8e)
