### ISSUE TITLE
Feature Request - RTC animations and cameras export

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#305]
### Current Behavior

None

### Expected Behavior

Add the ability for the exporter to create RTC animation file and the ASOBO extension "ASOBO_property_animation" per the
RTC SDK documentation.

https://docs.flightsimulator.com/flighting/html/Samples_And_Tutorials/Samples/SimObjects_Aircraft/RTCAircraft.htm

### Steps To Reproduce

Enhancement Request

### Environment

```markdown
- OS: Win 10
- Blender: 3.3.x
- glTF-Blender-IO-MSFS:next version
```

**Comment by y-khodja** [comment]
Hello, 

There is not need of an extension to export camera animation, you can already do it with the blender exporter by ticking "camera" here:
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/1f656c34-a4db-41c2-b654-aea378587310)
As long as it's animated it will get exported.

**Comment by ronh991** [comment]
AH thank you

**Comment by ronh991** [comment]
Ok
