### ISSUE TITLE
Emissive - Node structure incorrect

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#306]
### Current Behavior

The node links are are from the Emissive RGB node (Emissive factor) is connected to the Factor input of the Emissive Multiplier.

### Expected Behavior

The node links are are from the Emissive RGB node (Emissive factor) should be connected to Color2 input of the Emissive Multiplier. The Factor should be set to 1.0

### Steps To Reproduce

open blender
shade window
make a standard - material. Add an emissive texture to the emissive texture slot. See links change

### Environment

```markdown
- OS:win 10
- Blender:3.3.15
- glTF-Blender-IO-MSFS:1.3.2
```

### Anything else?

change code in msfs_material_function.py

to
```        
        # Links
        self.link(emissiveTexNode.outputs[0], emissiveMulNode.inputs[1])
        self.link(emissiveColorNode.outputs[0], principledBSDFNode.inputs[MSFS_PrincipledBSDFInputs.emission.value])
        self.link(emissiveScaleNode.outputs[0], principledBSDFNode.inputs[MSFS_PrincipledBSDFInputs.emissionStrength.value])
        # Factor Input
        emissiveMulNode.inputs[0].default_value = 1.0

```
in
defaultShadersTree

and

```
        # emissive
        if nodeEmissiveTex.image:
            self.link(nodeEmissiveColor.outputs[0], nodeMulEmissive.inputs[2])
            self.link(nodeEmissiveTex.outputs[0], nodeMulEmissive.inputs[1])
            self.link(nodeMulEmissive.outputs[self.outputs0], nodePrincipledBSDF.inputs[MSFS_PrincipledBSDFInputs.emission.value])
        else:
            self.link(nodeEmissiveColor.outputs[0], nodePrincipledBSDF.inputs[MSFS_PrincipledBSDFInputs.emission.value])

```

in
updateEmissiveLinks

![DA40CGDFQ_2024 02 11_11h23m58s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/3dbe18e0-5702-45c4-881f-0628ddffa275)

![DA40CGDFQ_2024 02 11_11h24m30s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/a2be4801-ec6d-49dd-b309-d35858965732)

**Comment by Pyscen312** [comment]
Seems to be working without these changes for me.

**Comment by ronh991** [comment]
> Seems to be working without these changes for me.

yes it does work, however there are slight changes between the two ways.  It's just that a 3 values color vector as output is interfaced to a single value factor is just not right in my mind.

Other multiplier nodes use the two colors and set the factor to 1.

**Comment by Pyscen312** [comment]
Since Asobo is no longer using this site to enhance or update the add-on. and not compiling new developments made by outsiders.   It would be best that any update be made in a new GitHub location.

**Comment by y-khodja** [comment]
Hello,

It will be fixed in the next update ^^!

Thank you for your report !

**Comment by SirComand** [comment]
> Hello,
> 
> It will be fixed in the next update ^^!
> 
> Thank you for your report !

When will it be updated and what version of blender will it be updated to.

**Comment by y-khodja** [comment]
Hello,

It will be updated soon and should support Blender 3.6 LTS version from then.
