### ISSUE TITLE
blender package

### ISSUE THREAD

**Issue by alexcaussades** [AsoboStudio/glTF-Blender-IO-MSFS#307]
### Current Behavior

Problem importing the file into blender 

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/27455689/06d8614c-6425-4fe2-949b-f6b7bd6727fd)

### Expected Behavior

No 

### Steps To Reproduce

no

### Environment

```markdown
- OS: W11
- Blender: 4.0
- glTF-Blender-IO-MSFS: last
```

**Comment by ronh991** [comment]
Does not work with 3.6 or higher.  per the read me.  need to use 3.3
