### ISSUE TITLE
GLTF texture error 

### ISSUE THREAD

**Issue by erasam** [AsoboStudio/glTF-Blender-IO-MSFS#308]
### Current Behavior

Once exported to MSFS the fuselage textures are shown jagged in the SIM.
In Blender they are looking perfect. 
There is no issue in the material or in the texture file as I tested it applying them to another similar model
It seems when the model is exported in gltf something goes wrong with UV map positions
![immagine](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/77914970/973fb468-1b90-466e-80c2-f3d9609ceb3c)

### Expected Behavior

Fuselage textures should be seen in the SIM as they are shown in blender

### Steps To Reproduce

It is just enough to test this behaviour using my aircraft model, then exporting it to the SIM

### Environment

```markdown
- OS: Windows 11
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.6 or 1.3.2 (tested with both)
```

### Anything else?

![immagine](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/77914970/ca2310ef-4b97-4fcf-8fad-74308df594ed)
![immagine](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/77914970/25fed74a-03cf-4693-a9c6-76cb22e5b4a3)

**Comment by ronh991** [comment]
Are you "Applying Modifiers" in the export settings?  is it checked.
![DA40CGDFQ_2024 02 22_11h7m56s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/d4c0636a-312f-4d37-9766-2d56a8e6fdf8)

**Comment by erasam** [comment]
Hi, I have applied all the modifiers before exporting it
Actually I'm facing exactly the same issue as reported here https://docs.flightsimulator.com/html/mergedProjects/How_To_Make_An_Aircraft/Contents/Modelling/Airframe/Texturing.htm?rhhlterm=UV%20unwrap&rhsearch=UV%20unwrap but it's not clear to me how to solve it

**Comment by erasam** [comment]
I have re-imported in Blender the GLTF file created by the Asobo exporter and the texture are fine
I have then re-imported in Blender the GLTF created by the package builder and the texture are broken (jagged): I checked the UV map and it is definitely the package builder destroying it

**Comment by y-khodja** [comment]
Hello,

As said in the readme the plugin does not support importing gltf that has been built in the sim.
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/3a9522cd-2afb-4a9d-9518-59ab944768e5)

Thank you for your report
