### ISSUE TITLE
Error installing GLTF

### ISSUE THREAD

**Issue by dkgolfnut5192** [AsoboStudio/glTF-Blender-IO-MSFS#310]
### Current Behavior

I get an error when i try to enable the plugin. photo attached

### Expected Behavior

the plugin to install without an error

### Steps To Reproduce

open blender 3.6.9.0
EDIT>Preferences>ADDONS>INSTALL
navigate to the io_scene_gltf2_msfs location of the zip file
click Install Addon

### Environment

```markdown
- OS:WIN 11
- Blender:3.6.9.0_x64
- glTF-Blender-IO-MSFS:1.3.2
```

### Anything else?

<img width="701" alt="Screenshot 2024-03-08 115357" src="https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/77357155/8d11bf9f-e1e2-4288-8ef7-fa23209adc6e">

**Comment by tradmangh** [comment]
The latest version is only compatible with Blender 3.3

**Comment by dkgolfnut5192** [comment]
I tried on 3.3 and had the same issueSent from my iPhoneOn Mar 9, 2024, at 6:21 AM, tradmangh ***@***.***> wrote:﻿
The latest version is only compatible with Blender 3.3

**Comment by dkgolfnut5192** [comment]
I will try installing again on 3.3Sent from my iPhoneOn Mar 9, 2024, at 6:21 AM, tradmangh ***@***.***> wrote:﻿
The latest version is only compatible with Blender 3.3

**Comment by SirComand** [comment]
I find it strange that it has not been updated for 7 months now. Why is that?

**Comment by y-khodja** [comment]
Hello,

A new version of the exporter compatible with Blender 3.6 is now available with the latest release of the plugin.

Thank you for your report.
