### ISSUE TITLE
Multi Exporter - export path error

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#313]
### Current Behavior

You get an export path error on the multi exporter

### Expected Behavior

No error

### Steps To Reproduce

open Blender 3.6.x - use cube
group by collection
set export path
check collection 
file name CollectionLOD0
click on Export

get
Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 225, in execute
    exportPath = bpy.path.abspath(exportPath)
UnboundLocalError: local variable 'exportPath' referenced before assignment
Error: Python: Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 225, in execute
    exportPath = bpy.path.abspath(exportPath)
UnboundLocalError: local variable 'exportPath' referenced before assignment

### Environment

```markdown
- OS:win 10
- Blender: 3.6.11
- glTF-Blender-IO-MSFS:1.3.3

msfs_multi_export.py
            for lod_group in lod_groups:
                # Generate XML if needed
                export_folder_path = lod_group.folder_path
                if export_folder_path == '//\\':
                        export_folder_path = export_folder_path.rsplit('\\')[0]
                exportPath = bpy.path.abspath(exportPath)
                if lod_group.generate_xml:
                    xml_path = os.path.join(export_folder_path, lod_group.group_name + ".xml")
                    found_guid = None


I assume this line is in error

                exportPath = bpy.path.abspath(exportPath)


change to ???

                exportPath = bpy.path.abspath(export_folder_path)
```

**Comment by erasam** [comment]
Same here

**Comment by SV001R** [comment]
I got same symptom with latest Blender 3.6 LTS

**Comment by SV001R** [comment]
I've just found solution for the problem.
1. Open msfs_multi_export.py file in Blender\3.6\scripts\addons\io_scene_gltf2_msfs\io with any text editor
2. Go to line 225 and change exportPath = bpy.path.abspath(exportPath) to exportPath = bpy.path.abspath(export_folder_path)
3. Open your Blender file and go to Multi-exporter gltf 2.0 tab
4. Copy and paste full path of the exporting directory like the screenshot shows
![화면 캡처 2024-03-23 213747](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/139863156/5644b5a3-0a5f-445c-b439-a96d4f22d3ad)
5. Then export it

But another problem encountered. Animation of magneto switch and propeller are not exported.

**Comment by y-khodja** [comment]
Hello,

It's fixed ! Thank you !
