### ISSUE TITLE
Core Khronos gltf changes tif to png

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#319]
### Current Behavior

The core Khronos code changes any tif texture file to png.  Is this an issue?  I thought tif files are better for say instrument decals etc.  Since tif get changes to dds in the final build, again is this a reduction in resolution?

### Expected Behavior

The 3DS max  exporter seems to allow tif as the uri in its functionality.  I was hoping the Blender exporter would to.
Using "keep original" does not work as expected.  You get this and no tif file would be copied to the PackageSources folder.

The work around could be to manually change the gltf image uri from png to tif and copy the tif manually

### Steps To Reproduce

add tif to texture slot and export cube - see a png in gltf

### Environment

```markdown
- OS:win 10
- Blender: 3.6.x
- glTF-Blender-IO-MSFS:1.3.3 update 3d7c
```

### Anything else?

Using a hook to image or texture does not allow access to image data and hence the uri data, A hook may not be possible.

posted a question in Khronos

https://github.com/KhronosGroup/glTF-Blender-IO/issues/2212

**Comment by y-khodja** [comment]
Hello,

The core Khronos Exporter does convert tif to png but when you have "keep originals" checked the tifs are referenced in the gltf. I can't repro the issue with Blender 3.6, here is my output test example :
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/7778ae74-7711-4fc3-aa42-a949ad7f23c9)

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/793ba95c-f4cc-4bd2-a849-97527a01ab98)

![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/114567493/df42e10b-3f61-4610-a6cb-a6e23da6bc92)

**Comment by ronh991** [comment]
Keep original does not work in the sense that the tif files are NOT exported to the texture folder. the user must do this manually.  If you check the "keep original" you will notice that the textbox for the texture folder is no longer active.

**Comment by ronh991** [comment]
Khronos - may add a hook to allow manipulation
https://github.com/KhronosGroup/glTF-Blender-IO/issues/2215

**Comment by y-khodja** [comment]
Good to know, thank you !
