### ISSUE TITLE
Cannot install the Exporter

### ISSUE THREAD

**Issue by lyonheart001** [AsoboStudio/glTF-Blender-IO-MSFS#320]
### Current Behavior

Hello Team,

I downloaded this installer Zip, went into Blender 3.6 LTS (zip file version, not Windows installed) and when trying to install the Exporter, it wouldnt show in the Apps list.  Nothing.  I then downloaded Blender 3.3 and tried that one, same thing.  I can install the other versions of Exporters and they show up properly, but when trying to install this one, with the others cleared out, it will not show.

Could I be doing something wrong?  I just read through the installation instructions and have done all of that.  I am using the 'install' version installation, not the copy/paste.

Thanks in advance for your help.

Bill
Lionheart Creations

### Expected Behavior

Exporter should show up in the App install list and be clickable to activate/deactivate.  It does not show in the list, after clicking the Install.  Nothing.... 

### Steps To Reproduce

Download Exporter
Open Blender
Go to Preferences and click Install
Find Exporter by Asobo, click on it
It should show up, but does not.

### Environment

```markdown
- OS: WINDOWS 10
- Blender: 3.3 and 3.6 latest of each version, ZIP version, not Windows Installer versions.
- glTF-Blender-IO-MSFS: 1.3.0  (The latest one you have here.  I downloaded it last night, Sunday night).
```

### Anything else?

Thank you all for making this exporter for us.  I know its not been easy.  Keep up the great work.  I love Blender.  Its so much more powerful then Max.

Bill

**Comment by Pyscen312** [comment]
You may not be downloading the correct zip file.    From the Codes tab:

 
![GitHub_page-1](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/71974404/7bf08914-d76a-4a03-96db-bb999840d158)

You will need to click on "Release 1.3.3 Latest: and then:

![GitHub_page-2](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/71974404/0dd83c50-de4e-4a87-bf04-6d4ce3ed1c3a)

At the bottom of the page where it states "Assets", click on "io_scene_gltf2_msfs.zip".  Do not change the filename.

**Comment by lyonheart001** [comment]
Many thanks.  Working now.  That did it.

**Comment by Pyscen312** [comment]
I'm glad... close this issue please.
