### ISSUE TITLE
Export Option to include/produce XML and GUID with exporting scene for Scenery use in MSFS

### ISSUE THREAD

**Issue by lyonheart001** [AsoboStudio/glTF-Blender-IO-MSFS#321]
### Current Behavior

No settings for including an XML and GUID on export of models that will be used for Scenery objects in MSFS, such as airport, scenery objects.

### Expected Behavior

There should be two option boxes you can tick on to create the XML and GUID's for things exported that will be used for scenery.  From tutorials I have seen online, this existed in the Blender 2.8 exporter system.  I do not see this in the newest Asobo 1.3.3 Exporter.  Am I perhaps missing it?

### Steps To Reproduce

Go to export a Cube and go through the selection options in the export settings window.  On mine that I installed today, latest Asobo exporter 1.3.3 and in Blender 3.3.x, I see no options for XML and GUID exporting.  They should be near the top.

### Environment

```markdown
- OS:  Windows 10
- Blender:  3.3.x
- glTF-Blender-IO-MSFS:  1.3.3
```

**Comment by lyonheart001** [comment]
Ah soooo....!  Many thanks.  Clicking the LOD button reveals those bits.  Thanks Pyscen312.  Very grateful.

When you export scenery, would you do it all from that small export center?  Just put in the Folder export target and export?  (My apologies, totally new to me.  Usually I am only exporting planes).

**Comment by y-khodja** [comment]
Hello,

Yes, you should use the objects panel to export your scenery objects, you can find more information here : https://docs.flightsimulator.com/html/Asset_Creation/Blender_Plugin/The_Blender_Exporter.htm

Thank you for your report
