### ISSUE TITLE
Is there a way to get around the MSFT_texture_dds not available with this addon?

### ISSUE THREAD

**Issue by sealam12** [AsoboStudio/glTF-Blender-IO-MSFS#329]
### Current Behavior

Whenever I use the addon and I try to import a file (787-10) it says MSFT_texture_dds not available with this addon. I do not care about the textures. I JUST WANT THE MODEL. I don't want a fix to make it import textures, I just want the model. That's all I care about.

### Expected Behavior

Import 3D gltf model

### Steps To Reproduce

Install addon as per instructions
Enable addon
Choose File / Import / gltf
Choose gltf file, Import fails (even the stock c152 LOD0 fails)

### Environment

```markdown
- OS: Windows 11
- Blender: 3.4
- glTF-Blender-IO-MSFS: 1.3.1
```

**Comment by Pyscen312** [comment]
This Addon does not allow for imports.  Documentation and here states it does not import models of any kind.

**Comment by y-khodja** [comment]
Hello,

This plugin cannot import glTF files that have been built into a Microsoft Flight Simulator package through the Sim's Package Builder. You can import only gltf that has been exported by this Blender exporter or the 3dsmax flightsim exporter.

Thank you for your report

**Comment by Treata11** [comment]
> This Addon does not allow for imports. Documentation and here states: it does not import models of any kind.

Just wanted to ask if there's a way to actually import the glTF files that have been built into a MSFS package in Blender?

**Comment by y-khodja** [comment]
Hello !

⚠️ This plugin cannot import glTF files that have been built into a Microsoft Flight Simulator package through the Sim's Package Builder.


> > This Addon does not allow for imports. Documentation and here states: it does not import models of any kind.
> 
> Just wanted to ask if there's a way to actually import the glTF files that have been built into a MSFS package in Blender?

**Comment by Treata11** [comment]
> ⚠️ This plugin cannot import glTF files that have been built into a Microsoft Flight Simulator package through the Sim's Package Builder.

Sure @y-khodja 
I saw your previous comment.

I was asking for different packages & solutions; If anyone would know any...

I actually found one:
https://github.com/bestdani/msfs2blend/releases/tag/v0.4
and it worked for me.

**Comment by y-khodja** [comment]
> > ⚠️ This plugin cannot import glTF files that have been built into a Microsoft Flight Simulator package through the Sim's Package Builder.
> 
> Sure @y-khodja I had seen your previous comment.
> 
> I was asking for different packages & solutions; If anyone would know any...
> 
> I actually found one: https://github.com/bestdani/msfs2blend/releases/tag/v0.4 and it worked for me.

As far as i know, this one works fine. I don't know any other tool that has been updated since.
