### ISSUE TITLE
Detail ORM node structure - looks incorrect

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#330]
### Current Behavior

I have put a note on dev hub

https://devsupport.flightsimulator.com/t/question-detail-color-and-detail-orm/8152/2

Nodes are not biased as described in the SDK docs.

### Expected Behavior

Developed a proposed node structure.

![DA40CGDFQ_2024 07 11_10h57m58s](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/19254353/5c9ad1d5-3900-49b2-9223-7b88e4ca25a3)

The detail ORM texture values for RGB are multiplied by 2 and then subtract 1. - That part makes sense.

However the NodeMapRange node has the from and to ranges the same - so this node does nothing. And I feel it’s in the wrong place.

As an example - the lower bound and upper bound of the two previous nodes - -1 and +1 (Minus 1 and Plus 1) then the map node has a from of 0 to 1 - so anything less that zero input is mapped to 0. This does not agree with the documentation description I quoted in the OP.

To continue then the output of 0 to 1 is ADDED to the main ORM node data - so potentially the RGB result can be greater than 1 if you just add.

I understand that the node structure here has nothing to do with the result displayed in the sim and the blender node structure is only helping in displaying an approximation to the sim rendering. But it would be nice to have a closer representation.

Blender 3.6 ASOBO 1.3.3 nodes

### Steps To Reproduce

ORM and Detail ORM textures

### Environment

```markdown
- OS:win10
- Blender:3.6.12
- glTF-Blender-IO-MSFS:1.3.3
```

**Comment by y-khodja** [comment]
Hello,

you should not change the values in the shader nodes, the map il used to clamp the resulted value between 0 and 1. The result is the closest as we have in-game.

Thank you for your report

**Comment by ronh991** [comment]
Just seemed incorrect to me - testing both does not really make too much difference.  The SDK description is confusing to me.

**Comment by y-khodja** [comment]
Hello,

I have pushed in a new branch a more accurate fix in this case.

Thank you for your report !

**Comment by ronh991** [comment]
Thanks - I will review

**Comment by ronh991** [comment]
Tested branch - works ok
