### ISSUE TITLE
file name uri - has ../texture in name

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#47]
the uri for the texture file names is "funny" 
        {
            "mimeType" : "image/png",
            "name" : "testplanepanel_normal",
            "uri" : "../texture/testplanepanel_normal.png"
        },
why the ../texture - as this is the export folder name that the textures goes into - should not be part of the file name - I get this warning in sim build.
![DA40CGDFQ_March 1, 2022_11h43m00s](https://user-images.githubusercontent.com/19254353/156211324-1974b408-bd0e-49bc-b50b-c7f6310654ed.png)

**Comment by pepperoni505** [comment]
This should have been fixed in 484a839ccf6e1b4542359c4ec8e9d15790940850. Please make sure you're using Blender 3.1
