### ISSUE TITLE
Anisotropic material : missing nodes

### ISSUE THREAD

**Issue by btronquo** [AsoboStudio/glTF-Blender-IO-MSFS#53]
### Current Behavior

The Anisotropic and Anisotropic Rotation in the principled bsdf are not connected when we choose and put a texture on Anisotropic Direction (Material: Anisotropic).

### Expected Behavior

create and connect correct nodes

### Steps To Reproduce

1. Check the shading nodes
2. Choose Anisotropic material
3. Put image into the slot **Anisotropic Direction (RG)**
4. The Anisotropic and Anisotropic Rotation in the principled bsdf are not connected

![image](https://user-images.githubusercontent.com/5455001/156936363-0e3218ce-aa03-4dab-9fd1-e97e1064cd2d.png)

### Environment

```markdown
- OS: win10
- Blender: 3.0.1
- glTF-Blender-IO-MSFS: 1.0.5
```

### Anything else?

[test.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8193247/test.zip)

I'm in the process to debug this for the MSFSToolkit as this is the same issue

**Comment by btronquo** [comment]
Any news / infos / tips ? ;)

**Comment by pepperoni505** [comment]
This is fixed in #69
