### ISSUE TITLE
Texture are exported in root folder 

### ISSUE THREAD

**Issue by mamu82** [AsoboStudio/glTF-Blender-IO-MSFS#55]
### Current Behavior

Texture are exported in root folder (the folder where the Blender file Is)

### Expected Behavior

Texture should be exported to /texture folder
Otherwise gonna show Pink checker in msfs

### Steps To Reproduce

Export with multiexporter

### Environment

```markdown
- OS: win 10 ita
- Blender: 3.0.1
- glTF-Blender-IO-MSFS: 1.0.5
```

**Comment by pepperoni505** [comment]
This should be fixed in #52
