### ISSUE TITLE
Build error when using Anisotropic material

### ISSUE THREAD

**Issue by BlueMeshs** [AsoboStudio/glTF-Blender-IO-MSFS#65]
### Current Behavior

When we're using the Anisotropic material the textures are correctly exported, but it create an error to build the package.

![Capture](https://user-images.githubusercontent.com/96650516/158418165-af716833-0ae7-44d5-8238-e689f909fbd4.JPG)

### Expected Behavior

it should not cause any error

### Steps To Reproduce

- Add a simple mesh with an Anisotropic Material
- Select Abd, Comp, Norm and Anisotropic RG textures
- Export it
- Then build the package

### Environment

```markdown
- OS: Windows 10
- Blender: 3.1.0
- glTF-Blender-IO-MSFS:1.0.0
```

### Anything else?

[Anisotropic_test (2).zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8255122/Anisotropic_test.2.zip)

**Comment by lpierabella** [comment]
this is an issue on the engine side..it will be fixed on next update
