### ISSUE TITLE
duplicate node in shader tree nodeDetailNormal

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#70]
### Current Behavior

seems a duplicate or two nodes are on top of each other.

        self.nodeDetailNormal = self.addNode(
            "ShaderNodeTexImage",
            {
                "name": MSFS_ShaderNodes.detailNormalTex.value,
                "location": (-500, -1300.0),
            },
        )
        

............

        self.nodeDetailNormalTex = self.addNode(
            "ShaderNodeTexImage",
            {
                "name": MSFS_ShaderNodes.detailNormalTex.value,
                "location": (-500, -1300.0),
            },
        )

file ismsfs_material_function lines 282 on.

### Expected Behavior

no dupe?

### Steps To Reproduce

look at code

### Environment

```markdown
- OS:win 10
- Blender: 3.1
- glTF-Blender-IO-MSFS:March 16
```

**Comment by lpierabella** [comment]
fixed on #71
