### ISSUE TITLE
Add to migrate materials - legacy bsdf values for metallic, roughness, emissive and alpha

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#74]
### Current Behavior

migrate does not use metallic, roughness, emissive and alpha from legacy bsdf 

### Expected Behavior

Use those values and update new scale nodes

### Steps To Reproduce

click migrate on bsfd colr  materials

### Environment

```markdown
- OS:win 10
- Blender:3.1
- glTF-Blender-IO-MSFS:1.1.2
```

**Comment by pepperoni505** [comment]
Can you elaborate on this?

**Comment by ronh991** [comment]
https://youtu.be/YKpHpC4978Q

**Comment by lpierabella** [comment]
the error is no longer there in the last versions
metallic and roughness are currently properly migrated

alpha:
currently, the property msfs_color_alpha_mix is migrated too
in your file, you have two type of alpha, the msfs_color_alpha_mix, and the bsdf alpha input
after some test seems to me that even with Vitus exporter setting the alpha input in the BSDF manually it is not a good practice.
the Vitus exporter was connecting msfs_color_alpha_mix to the alpha when the blend mode was different from opaque

![image](https://user-images.githubusercontent.com/77288191/162418113-0508e2bf-e13d-4e22-864a-43ce6ef695bc.png)

so to be more, 
we have two alpha there the importer is migrating only msfs_color_alpha_mix

**Comment by lpierabella** [comment]
@ronh991 if this is ok for you we can close this PR and open a new one to solve the emission issue

**Comment by ronh991** [comment]
what is the emissive issue? can someone else open an issue?

**Comment by lpierabella** [comment]
Emissive in 3ds max exporter can exceed RGB value of 1, in Blender this is not possible.
But this is a design issue on MSFS side as the glTF standard does not allow to exceed RGB values of 1.
So what Max does is not correct.
It will be handled internally so there is no issue to open on this project

**Comment by ronh991** [comment]
closed
