### ISSUE TITLE
Migrate materials - legacy msfs_env_occluder, msfs_invisible type not found

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#75]
### Current Behavior

missing msfs_env_occluder and msfs_invisible not showing

### Expected Behavior

change legacy name msfs_env_occluder from msfs_environment_occluder

### Steps To Reproduce

example legacy occluder

### Environment

```markdown
- OS:10
- Blender:3.1
- glTF-Blender-IO-MSFS:1.1.2
```

**Comment by pepperoni505** [comment]
Can you provide a blend file?

**Comment by ronh991** [comment]
the materials that need to be migrated don't show as "migratable"  no button
![DA40CGDFQ_March 20, 2022_17h09m13s](https://user-images.githubusercontent.com/19254353/159186094-97827d9b-7016-455b-a9bc-142d569bb757.png)

**Comment by ronh991** [comment]
[TestPlane6-1_MSFS_v23_ver3_forwindshield.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8312194/TestPlane6-1_MSFS_v23_ver3_forwindshield.zip)

**Comment by ronh991** [comment]
fixed in migration fix branch
