### ISSUE TITLE
Exporting multiple collections as a single object

### ISSUE THREAD

**Issue by anthony031** [AsoboStudio/glTF-Blender-IO-MSFS#78]
When building an aircraft I like to separate each component (wings, elevator, panel etc) into an individual collection. This makes it easier to work with a large project which can have over a thousand parts. There doesn't seem to be any way to export these collections as a single model. The exporter forces each collection to be exported as a separate model which may be fine for working with scenery but is less than ideal for exporting aircraft.

**Comment by pepperoni505** [comment]
Hi,

You're in luck! This feature already exists. Here's how to use it:
- Open the Multi-Exporter (located in the N-panel)
- Switch to the `Presets` tab
- Click `Add Preset` and tick the `Enabled` option
- Set proper name and export path
- Press `Edit Layers`
- Enable the collections you want to export in the file and press `OK`
- Press `Export`!

Hopefully this is what you were looking for.

**Comment by myphysicalworld** [comment]
However, this only creates a .bin and .glTF but zero .xml.

**Comment by pepperoni505** [comment]
The `Presets` tab is not intended to create an XML.

**Comment by myphysicalworld** [comment]
I understand that. If we use the Presets for multiple collections (which I like btw), do we just have to create our own .xml and generate a guid ourselves?

**Comment by pepperoni505** [comment]
At the moment, yes. We can look into officially supporting XML generation for the presets tab. I will keep you posted

**Comment by myphysicalworld** [comment]
Awesome.....
Simple question (maybe)...I have a spot light (had them in my previous scenery ...Blender 2.9) and migrated it over to Blender 3.1....however, it no longer works in the sim after exporting it from 3.1.....is this a 3.1 issue. Sometimes I feel I am on this Blender 3.1/Asobo Exporter planet by myself and pushing the limits....LOL...I tried punctual lights checkbox but it errored out during my sim build.

**Comment by pepperoni505** [comment]
> Awesome..... Simple question (maybe)...I have a spot light (had them in my previous scenery ...Blender 2.9) and migrated it over to Blender 3.1....however, it no longer works in the sim after exporting it from 3.1.....is this a 3.1 issue.

Is this issue similar to #93? If not, please make a new issue
> Sometimes I feel I am on this Blender 3.1/Asobo Exporter planet by myself and pushing the limits....LOL...I tried punctual lights checkbox but it errored out during my sim build.

We recently fixed a bug that would cause errors with lights. Can you please try using our latest release?

**Comment by myphysicalworld** [comment]
Not exactly.....mine do not light at all.....I will first test with latest version (1.1.3) of exporter and experiment before I submit an issue.
You have been great, thank you!

**Comment by anthony031** [comment]
I have found a workaround for this problem (I don't think pepperoni's solution would work at all).

I repurpose the LOD function to export interior and exterior models. Create a Collection and called it name_LOD0 (the _LOD0 is the important part, the name can be anything you like), put all the Collections for the interior model inside name_LOD0. Create another Collection and call it name_LOD1 (this name should be the same as the name in name_LOD0) and put all the Collections for the exterior inside name_LOD1.

Now check that Grouped By Collections is ticked and you should have name_LOD0 and name_LOD1 appear under "name". Tick name_LOD0 and name_LOD1 and set their filenames and your export folder. All the other collections will also appear in the list but they should be unticked so you can just ignore them. Now when you export it should export the name_LOD0 and name_LOD1 collections and sub-collections as two separate models.

It's not intuitive but it seems to work. Just make sure you use the _LODx suffix for your top level Collection and the exporter seems to be able to group any sub-collections based on that suffix.

More information and a picture of the setup can be found at fsdeveloper:

https://www.fsdeveloper.com/forum/threads/msfs-asobo-official-blender-exporter.454146/page-2#post-900372

**Comment by myphysicalworld** [comment]
> > Awesome..... Simple question (maybe)...I have a spot light (had them in my previous scenery ...Blender 2.9) and migrated it over to Blender 3.1....however, it no longer works in the sim after exporting it from 3.1.....is this a 3.1 issue.
> 
> Is this issue similar to #93? If not, please make a new issue
> 
> > Sometimes I feel I am on this Blender 3.1/Asobo Exporter planet by myself and pushing the limits....LOL...I tried punctual lights checkbox but it errored out during my sim build.
> 
> We recently fixed a bug that would cause errors with lights. Can you please try using our latest release?

WE HAVE LIGHTS! I installed 1.1.3 and re-exported with "punctual lights" checked (again) and it worked......you guys are awesome! What a difference a new day makes
![LightsOn](https://user-images.githubusercontent.com/69404541/159938812-ea35b74d-b6ef-4eac-a406-88b31879a75e.png)
!

**Comment by pepperoni505** [comment]
Can this issue be closed?

**Comment by myphysicalworld** [comment]
Yes.
