### ISSUE TITLE
file naming in the <LODs> section is wrong

### ISSUE THREAD

**Issue by mamu82** [AsoboStudio/glTF-Blender-IO-MSFS#79]
### Current Behavior

When exporting multiple lods, the file naming in the <LODs> section is wrong (only the last lod name is used)

`<LODS>
		<LOD minSize="100" ModelFile="x2_bigOjbect.gltf"/>
		<LOD minSize="50" ModelFile="x2_bigOjbect.gltf"/>
		<LOD minSize="20" ModelFile="x2_bigOjbect.gltf"/>
	</LODS>`

### Expected Behavior
`<LODS>
		<LOD minSize="100" ModelFile="x0_bigOjbect.gltf"/>
		<LOD minSize="50" ModelFile="x1_bigOjbect.gltf"/>
		<LOD minSize="20" ModelFile="x2_bigOjbect.gltf"/>
	</LODS>
`

### Steps To Reproduce

create any multi lod in Blender and export

### Environment

```markdown
- OS:win10
- Blender:3.1.0
- glTF-Blender-IO-MSFS:1.1.2
```

### Anything else?

[bigObject.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8310976/bigObject.zip)
![Screenshot (366)](https://user-images.githubusercontent.com/101219759/159157228-1e43dd20-15aa-4763-92b2-a73abe577a82.jpg)

**Comment by Mikeaat** [comment]
can confirm this.

Just for your information you can create the groops with collections too. then you dont have to parent everything to emptys.
![2022-03-20 11_49_15-](https://user-images.githubusercontent.com/46610319/159158850-7b4ff984-fa74-4159-a9be-b6702c51c5f4.jpg)

**Comment by pepperoni505** [comment]
Fixed in #81
