### ISSUE TITLE
Export a model with lights cause a error in the msfs compiler 

### ISSUE THREAD

**Issue by Mikeaat** [AsoboStudio/glTF-Blender-IO-MSFS#82]
### Current Behavior

when you make a object with a spotlight and export it the exporter is adding this extension: KHR_lights_punctual 
because of this you get this message from the compiler:
![2022-03-20 18_51_57-unknown png (1079×101)](https://user-images.githubusercontent.com/46610319/159175802-e7c9d788-e224-4b72-b76d-d1a99a924880.jpg)

It looks like the rotation / orientation of the spot is exported with the wrong extension.

 `"extensionsUsed" : [
        "ASOBO_normal_map_convention",
        "KHR_lights_punctual",
        "ASOBO_macro_light"
    ],
    "extensionsRequired" : [
        "KHR_lights_punctual"
    ],
    "extensions" : {
        "KHR_lights_punctual" : {
            "lights" : [
                {
                    "color" : [
                        1,
                        0.9425290822982788,
                        0.854992687702179
                    ],
                    "intensity" : 150,
                    "spot" : {
                        "innerConeAngle" : 0.8901179370451118,
                        "outerConeAngle" : 1.0471975803375244
                    },
                    "type" : "spot",
                    "name" : "Spot"
                }
            ]
        }
    },
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                0,
                2
            ]
        }
    ],
    "nodes" : [
        {
            "mesh" : 0,
            "name" : "x01_Main.001",
            "translation" : [
                0.8182962536811829,
                1.0000004768371582,
                0.9419757723808289
            ]
        },
        {
            "extensions" : {
                "KHR_lights_punctual" : {
                    "light" : 0
                }
            },
            "name" : "Spot_Orientation",
            "rotation" : [
                -0.7071067690849304,
                0,
                0,
                0.7071067690849304
            ]
        },
        {
            "children" : [
                1
            ],
            "extensions" : {
                "ASOBO_macro_light" : {
                    "color" : [
                        1,
                        0.9425290822982788,
                        0.854992687702179
                    ],
                    "intensity" : 150,
                    "cone_angle" : 120.00000333930423,
                    "has_symmetry" : false,
                    "flash_frequency" : 0,
                    "flash_duration" : 0,
                    "flash_phase" : 0,
                    "rotation_speed" : 0,
                    "day_night_cycle" : true
                }
            },
            "name" : "Spot",
            "translation" : [
                -6.666948318481445,
                2.705559730529785,
                13.863369941711426
            ]
        }
    ],`

### Expected Behavior

something like this:

`"extensionsUsed" : [
        "ASOBO_normal_map_convention",
        "ASOBO_macro_light"
    ],
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                0,
                1,
                2,
                3,
                4
            ]
        }
    ],
    "nodes" : [
        {
            "mesh" : 0,
            "name" : "Cube"
        },
        {
            "mesh" : 1,
            "name" : "Cube.001",
            "scale" : [
                0.20000000298023224,
                0.02600245177745819,
                0.20000000298023224
            ],
            "translation" : [
                11.680688858032227,
                4.844680309295654,
                8.398731231689453
            ]
        },
        {
            "extensions" : {
                "ASOBO_macro_light" : {
                    "color" : [
                        1,
                        0.7716997265815735,
                        0.6500170826911926
                    ],
                    "intensity" : 80,
                    "cone_angle" : 120.00000333930423,
                    "has_simmetry" : false,
                    "flash_frequency" : 0,
                    "flash_duration" : 0,
                    "flash_phase" : 0,
                    "rotation_speed" : 0,
                    "day_night_cycle" : true
                }
            },
            "name" : "Spot",
            "rotation" : [
                0.7071067690849304,
                0,
                0,
                0.7071068286895752
            ],
            "translation" : [
                11.690343856811523,
                4.592289924621582,
                8.399174690246582
            ]
        },`

### Steps To Reproduce

1. add a spot lamp
2. export
3. look into the gltf 
4. compile in msfs to see the message

### Environment

```markdown
- OS: Win 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.2
```

**Comment by pepperoni505** [comment]
Fixed in #85
