### ISSUE TITLE
migrate windshield material with textures - missing Details Scratches Icing Mask Fingerprints texture

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#87]
### Current Behavior

the texture for Details Scratches, ics, fingerprints is not carried over for windshield material.

### Expected Behavior

Carry over the texture.

### Steps To Reproduce

add windshield material with textures as required

### Environment

```markdown
- OS:10
- Blender:3.1
- glTF-Blender-IO-MSFS:1.1.2
```

### Anything else?

![DA40CGDFQ_March 20, 2022_17h19m36s](https://user-images.githubusercontent.com/19254353/159186429-882d6fd3-19d9-4a9a-ac63-08b31830ef4a.png)
![DA40CGDFQ_March 20, 2022_17h20m08s](https://user-images.githubusercontent.com/19254353/159186434-9aa885c3-5f40-4493-b9c3-dc7f3b7dbfb4.png)

**Comment by ronh991** [comment]
[TestPlane6-1_MSFS_v23_ver3_forwindshield.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8312202/TestPlane6-1_MSFS_v23_ver3_forwindshield.zip)

**Comment by scheny** [comment]
I just ran into the same problem and couldn't fix it even with support of the GOT-friends group. Seems to be a bug.

Please fix, as this is a major --> windshields are 100% translucent and look as if they are missing in MSFS.

**Comment by lpierabella** [comment]
this should be fixed in 0ef1f2c7a72c492e3c00370d8ca902a4b1c25da1

**Comment by ronh991** [comment]
fixed in migration fix branch
