### ISSUE TITLE
Windshield texture cause error in export

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#9]
having icing dirt finger prints etc cause error in blender export.
21:32:37 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.
gather_material_hook fails on <io_scene_gltf2_msfs.glTF2ExportUserExtension object at 0x0000023BD94B9BB0>
gather_texture_info() missing 1 required positional argument: 'export_settings'
![DA40CGDFQ_January 5, 2022_16h35m33s](https://user-images.githubusercontent.com/19254353/148292870-9aee5478-e553-49fe-b45f-b6835b9aec9b.png)

**Comment by pepperoni505** [comment]
This issue should be fixed now

**Comment by ronh991** [comment]
closed -fixed.
