### ISSUE TITLE
Comp (occ, rough, mat) texture slot color space

### ISSUE THREAD

**Issue by Mikeaat** [AsoboStudio/glTF-Blender-IO-MSFS#90]
### Current Behavior

the color space of this node is currently set to srgb this is resulting in too shiny materials.
![2022-03-22 22_32_05-Blender_  D__BlendFiles_Community_LOXZ_31c_LOXZ_31c blend](https://user-images.githubusercontent.com/46610319/159580145-aad9fba6-ca0f-44ef-a995-fb9a4c16bcc7.jpg)

### Expected Behavior

if it is set to "non-color" the result is way better
![2022-03-22 22_31_32-Blender_  D__BlendFiles_Community_LOXZ_31c_LOXZ_31c blend](https://user-images.githubusercontent.com/46610319/159580193-58983f8e-ddcd-48f2-afbc-d96f20dd319d.jpg)

### Steps To Reproduce

1. add a pbr material
2. check the roughness

### Environment

```markdown
- OS: win 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: main branch from 21.03.2022
```

**Comment by mamu82** [comment]
+1

The same for the Normal map, the node Is created as sRgb 
while the correct rendering Is obtained with nonColor

**Comment by Mikeaat** [comment]
in version 1.1.3 the normal map color space is already fixed. 
1.1.3 is available now. @mamu82

**Comment by mamu82** [comment]
> in version 1.1.3 the normal map color space is already fixed. 
> 1.1.3 is available now. @mamu82 

Splendid, thank Mikea and Pepperoni 😅
