### ISSUE TITLE
LOD order in the .xml file

### ISSUE THREAD

**Issue by Mikeaat** [AsoboStudio/glTF-Blender-IO-MSFS#91]
### Current Behavior

LOD lines are ASC by the min size
![2022-03-22 22_48_46-LOXZ_31c xml - Visual Studio Code](https://user-images.githubusercontent.com/46610319/159582915-b54be789-7cea-47ef-8294-49b14981dfdc.jpg)
in this order the more detailed models are not loading.

i exported with grouped collections

### Expected Behavior

LOD lines DSC by the min size
![2022-03-22 22_49_19-LOXZ_31c xml - Visual Studio Code](https://user-images.githubusercontent.com/46610319/159583096-ff646aef-7a1d-491b-a33e-5551a97b3458.jpg)

### Steps To Reproduce

1. export multiple lods

### Environment

```markdown
- OS: win 10
- Blender: 3.1
- glTF-Blender-IO-MSFS: main branch 21.03.2022
```

**Comment by realModsWanted** [comment]
Yes, can confirm this, had the same issue today. When I exported mit the Exporter, LODs didn't work.
Then I opened the gltf in N++ and saw, that the order was wrong.

So from top to bottom it has to be highest LOD to lowest LOD and VERY IMPORTANT, no "minSize" entry in the lowest (last/most bottom)  LOD entry.
