### ISSUE TITLE
Suggestion: Define 'Windsock' ?

### ISSUE THREAD

**Issue by azgoodaz** [AsoboStudio/glTF-Blender-IO-MSFS#94]
I don't know if this is possible via the SDK limitations of the game (if it's not possible, maybe bring it up to Asobo), but is there a way to define via a toggle in 'Render' or 'Gameplay' parameters if an object is a Windsock or not?

I feel like this will cut the need for custom animations and just have this object rely on in-game weather for animations instead of exporting animations and the tedious process.

**Comment by pepperoni505** [comment]
This suggestion is probably best to be posted to https://devsupport.flightsimulator.com/index.html

**Comment by Mikeaat** [comment]
there is a windsock library on flightsim.to if you dont want to do this fizzy stuff yourself :) it's called "windy things". @azgoodaz

**Comment by azgoodaz** [comment]
> there is a windsock library on flightsim.to if you dont want to do this fizzy stuff yourself :) it's called "windy things". @azgoodaz

If you want to post on the marketplace, this library isn't very useful. Sadly, this isn't a good workaround.

**Comment by azgoodaz** [comment]
> This suggestion is probably best to be posted to https://devsupport.flightsimulator.com/index.html. However, you will still have to manually rig the windsock (assuming your suggestion goes through)

Oh didn't know that. Thanks, just submitted the idea/suggestion.
