### ISSUE TITLE
Blender Lights Not Exporting to glTF

### ISSUE THREAD

**Issue by myphysicalworld** [AsoboStudio/glTF-Blender-IO-MSFS#95]
### Current Behavior

Added Spot and area lights do not export. They all export fine with Blender2MSFS and Blender 2.9. I noticed this with my airport scenery so I decided to create a small scene containing 2 cubes (one cube has been divided to take 3 faces with glass texturing), 2 spots, and 1 icosphere (with emission).
When I export using 1.1.3 when I load it in the sim all lights are not there, however the emission on the icosphere is good.
When I export the exact same blend file from Blender 2.9 using Blender2MSFS, everything shows up in the sim.
I opened both glTF files in Notepad++ and noticed that the one (made a text file of the gltf called....TestBlock.txt) from Blender2MSFS exporter has the lights but the Asobo exporter glTF (made a text file of the gltf called...TestBlockX.txt) does not
[TestBlock.txt](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8337172/TestBlock.txt)
[TestBlockX.txt](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8337174/TestBlockX.txt)
.

### Expected Behavior

All added lights should be turned on based on the settings for day/night. I have some lights on all the time and some set to day/night.

### Steps To Reproduce

1. in Blender 3.1
2. Make Collection called TestBlock
3. Add two cubes
4. Add two spot lights with 100W White light (default settings)
5. Add two area lights with 100W white light (default settings)
6. save
7. Export using Multi-Export glTF 2.0 using "by Collection" and Generate XML
8. Build using MSFS SDK
9. Open same blend file in Blender 2.9
10. Export using Blender2MSFS
11. Build using MSFS SDK

### Environment

```markdown
- OS: Window 10 Pro
- Blender: 3.1
- glTF-Blender-IO-MSFS: 1.1.3
```

### Anything else?

I tried to attach the .blend file here but it would not allow it.

**Comment by Mikeaat** [comment]
Did you also activate the "punctual lights" checkbox in the exporter / settings? 
![unknown-12.png](https://user-images.githubusercontent.com/46610319/159835848-620cd0e3-438d-46b7-83c9-72fea0ac5faf.png)

**Comment by myphysicalworld** [comment]
I did on a previous export but the Build process failed due to "punctual light extension not supported".
