### ISSUE TITLE
"Current Frame" export ignores Delta Transform

### ISSUE THREAD

**Issue by Wombii** [AsoboStudio/glTF-Blender-IO-MSFS#98]
### Current Behavior

Background: I have hangar doors animated, but I would like to export them static in a partially open position. I move playback to a specific frame and export with "current frame" enabled in the exporter settings. This works with normal Transform (Both rotation and Location). Delta transform makes it so much easier to animate and reposition than absolute transform.
Delta transform works if I activate the animation as autoplay in the xml, but not for static "Current Frame" export.

Issue: "Current frame" exporter setting ignores "Delta Transform".

### Expected Behavior

Delta transform works when the animation is playing, so I would expect it to also work when exporting a static "Current Frame".

### Steps To Reproduce

Green box in attached screenshot and blender file:
Make an animation on an object from 1-101 with location or rotation transform and make NLA track.
Select a frame in the playback, tick the "Current Frame" checkbox in the exporter settings.
Observe in MSFS that the object is positioned correctly according to the playback frame in Blender.

Red box in attached screenshot and blender file:
Make an animation on an object from 1-101 with Delta Transform location or rotation and make NLA track.
Select a frame in the playback, tick the "Current Frame" checkbox in the exporter settings.
Observe in MSFS that the object is positioned as frame 0, no animation applied
![Screenshot 2022-03-25 134813](https://user-images.githubusercontent.com/60835350/160123572-007307cb-b7c5-466a-861c-43661e69c0c3.jpg)
.

### Environment

```markdown
- OS:Windows 10
- Blender: 3.1.0
- glTF-Blender-IO-MSFS:
```

### Anything else?

![image](https://user-images.githubusercontent.com/60835350/160124573-7ab50bd4-6219-4835-972e-52941945023f.png)
![image](https://user-images.githubusercontent.com/60835350/160124604-44273b6c-06ae-49d8-b10e-7d56d040ef8f.png)

Example Blender file:
[BlendfileanimationtestDelta.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/8350688/BlendfileanimationtestDelta.zip)

**Comment by pepperoni505** [comment]
Hi,

Thanks for reporting this issue! Unfortunately, this is out of the scope of our repository. We extend the base Blender glTF IO. Please open an issue on [their repo](https://github.com/KhronosGroup/glTF-Blender-IO) for this issue to be fixed

**Comment by Wombii** [comment]
Thank you for the response!

**Comment by pepperoni505** [comment]
Would you mind closing this issue?
